-- Spell data for CastTracker.lua, keyed by the spell name exactly as the
-- esES combat log prints it:
--   castSpells:     cast time (t, milliseconds) and icon name of spells
--                   cast by other units;
--   castInterrupts: spells that break a cast when they hit or land on
--                   the caster (kicks, stuns, fears, bombs).
-- Extracted verbatim from pfUI's spell database (env/locales_esES.lua,
-- tables "spells" and "interrupts"; MIT License, Copyright (c)
-- 2016-2021 Eric Mauser (Shagu)).

local E = unpack(ElvUI)
local UF = E.UnitFrames

-- Overwrites whatever enUS.lua may have set, whichever file ran first.
if GetLocale() ~= "esES" then return end

UF.castSpells = {
  ['"Desplumado" mantiene forma de pollo']={t=1000,icon='Ability_Racial_BearForm'},
  ['Abrazo de la viuda']={t=500,icon='Spell_Arcane_Blink'},
  ['Abrellamas']={t=2500,icon='Spell_Fire_Fire'},
  ['Abriendo']={t=5000,icon='Temp'},
  ['Abriendo - Sin texto']={t=5000,icon='Temp'},
  ['Abriendo arca']={t=5000,icon='Temp'},
  ['Abriendo arca de escarabajo']={t=5000,icon='Temp'},
  ['Abriendo arca de reliquias']={t=5000,icon='Temp'},
  ['Abriendo arca oscura']={t=5000,icon='Temp'},
  ['Abriendo barrera de termitas']={t=5000,icon='Temp'},
  ['Abriendo buzón de Stratholme']={t=5000,icon='Temp'},
  ['Abriendo caja']={t=5000,icon='Temp'},
  ['Abriendo caja de seguridad']={t=5000,icon='Temp'},
  ['Abriendo caja fuerte']={t=5000,icon='Temp'},
  ['Abriendo caja fuerte secreta']={t=5000,icon='Temp'},
  ['Abriendo caja fuerte segura']={t=5000,icon='Temp'},
  ['Abriendo cofre de Benedict']={t=5000,icon='Temp'},
  ['Abriendo cofre del botín']={t=5000,icon='Temp'},
  ['Abriendo gran arca de escarabajo']={t=5000,icon='Temp'},
  ['Abriendo puerta de taberna']={t=5000,icon='Temp'},
  ['Aceite bendito de zahorí']={t=3000,icon='Temp'},
  ['Aceite brillante de zahorí']={t=3000,icon='Temp'},
  ['Aceite de Escarcha']={t=3000,icon='Temp'},
  ['Aceite de las Sombras']={t=3000,icon='Temp'},
  ['Aceite de maná resplandeciente']={t=3000,icon='Temp'},
  ['Aceite de zahorí']={t=3000,icon='Temp'},
  ['Aceite inferior de maná']={t=3000,icon='Temp'},
  ['Aceite inferior de zahorí']={t=3000,icon='Temp'},
  ['Aceite menor de maná']={t=3000,icon='Temp'},
  ['Aceite menor de zahorí']={t=3000,icon='Temp'},
  ['Acometida']={t=2500,icon='Spell_Holy_HolySmite'},
  ['Acometida Sagrada']={t=2500,icon='Spell_Holy_HolySmite'},
  ['Activar defensas']={t=5000,icon='Temp'},
  ['Adorno brillante']={t=5000,icon='INV_Misc_Orb_03'},
  ['Adornos brillantes']={t=5000,icon='INV_Misc_Orb_03'},
  ['Afilar arma: crítica']={t=3000,icon='Temp'},
  ['Agilidad deteriorada']={t=2000,icon='Spell_Holy_HarmUndeadAura'},
  ['Aguijonero de veneno']={t=2000,icon='INV_Misc_MonsterTail_03'},
  ['Ahuyentar a no-muerto']={t=1500,icon='Spell_Holy_TurnUndead'},
  ['Ajustar actitud']={t=2000,icon='INV_Gizmo_01'},
  ['Aliento de Escarcha']={t=250,icon='Spell_Frost_FrostNova'},
  ['Aliento de arena']={t=2000,icon='Spell_Fire_WindsofWoe'},
  ['Aliento de llamarada']={t=1700,icon='Spell_Fire_Fire'},
  ['Aliento de relámpagos']={t=2000,icon='Spell_Nature_Lightning'},
  ['Aliento escalofriante']={t=1000,icon='Spell_Frost_Wisp'},
  ['Ametralladora']={t=500,icon='Ability_Marksmanship'},
  ['Amplificar daño']={t=2000,icon='Spell_Nature_AbolishMagic'},
  ['Amplificar llamas']={t=1000,icon='Spell_Fire_Fireball'},
  ['Ansia de sangre rápida']={t=2000,icon='Spell_Nature_BloodLust'},
  ['Antorcha de invocación demoníaca']={t=3000,icon='Temp'},
  ['Antorcha de la falla']={t=2000,icon='Spell_Nature_AbolishMagic'},
  ['Antorcha lanzable']={t=1000,icon='Spell_Fire_Flare'},
  ['Aparición de Desafío para Urok']={t=2000,icon='Temp'},
  ['Aprisionar']={t=10000,icon='Spell_Shadow_Teleport'},
  ['Ardilla mecánica']={t=1000,icon='Spell_Shadow_Metamorphosis'},
  ['Arma consagrada']={t=3000,icon='Temp'},
  ['Armadura elemental']={t=1000,icon='Spell_Frost_Frost'},
  ['Arrullo de encantamiento']={t=1000,icon='Spell_Shadow_SoothingKiss'},
  ['Artista del escape']={t=500,icon='Ability_Rogue_Trip'},
  ['Aspecto de Neptulón']={t=1000,icon='Temp'},
  ['Astucia del raptor']={t=3000,icon='INV_Misc_MonsterClaw_02'},
  ['Ataque con bomba de aturdimiento']={t=2000,icon='Spell_Fire_SelfDestruct'},
  ['Ataque de Nefarius 001']={t=1000,icon='Temp'},
  ['Atraepeces acuadinámico']={t=5000,icon='INV_Misc_Orb_03'},
  ['Aullador Lobo Gélido']={t=3000,icon='Ability_Mount_WhiteDireWolf'},
  ['Aullido de terror']={t=2000,icon='Spell_Shadow_DeathScream'},
  ['Aullido sangriento']={t=1000,icon='Spell_Shadow_LifeDrain'},
  ['Aumentar reputación']={t=1000,icon='Temp'},
  ['Autodestrucción']={t=7000,icon='Spell_Fire_SelfDestruct'},
  ['Autodetonación']={t=7000,icon='Spell_Fire_SelfDestruct'},
  ['Autoresurrección']={t=5000,icon='Temp'},
  ['Autorizar mascota']={t=500,icon='Spell_Shadow_DeathPact'},
  ['Ayuda']={t=7000,icon='Temp'},
  ['Babosa enferma']={t=2000,icon='Spell_Shadow_CreepingPlague'},
  ['Balas inferno']={t=3000,icon='Spell_Fire_SelfDestruct'},
  ['Bandera de Kadrak']={t=2000,icon='INV_Banner_03'},
  ['Barrera de luz']={t=2000,icon='Temp'},
  ['Barrera giratoria']={t=1500,icon='INV_Spear_05'},
  ['Barrido']={t=1500,icon='Spell_Nature_Thorns'},
  ['Barrido de gusanos']={t=1000,icon='INV_Misc_MonsterScales_05'},
  ['Barrido extenso']={t=4000,icon='Ability_Whirlwind'},
  ['Barroso oscuro']={t=5000,icon='Spell_Shadow_CreepingPlague'},
  ['Bastón principal de Uldaman']={t=5000,icon='Temp'},
  ['Beber poción']={t=3000,icon='Spell_Holy_Heal'},
  ['Beber poción menor']={t=3000,icon='Spell_Holy_Heal'},
  ['Bebida inteligente de Mebok']={t=3000,icon='Temp'},
  ['Bendición de Julie']={t=2000,icon='Spell_Holy_Renew'},
  ['Bendición de Shahram']={t=1000,icon='Spell_Holy_LayOnHands'},
  ['Bestia temible']={t=1500,icon='Ability_Druid_Cower'},
  ['Bola de Fuego']={t=3500,icon='Spell_Fire_FlameBolt'},
  ['Bola de relámpagos']={t=1000,icon='Spell_Lightning_LightningBolt01'},
  ['Bomba']={t=2000,icon='Spell_Fire_SelfDestruct'},
  ['Bomba Arcana']={t=1500,icon='Spell_Holy_Silence'},
  ['Bomba Hierro Negro']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Bomba altamente explosiva']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Bomba de aturdimiento']={t=2000,icon='Spell_Fire_SelfDestruct'},
  ['Bomba de fragmentación de mitril']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Bomba de gas']={t=1000,icon='INV_Misc_Ammo_Bullet_01'},
  ['Bomba del Sindicato']={t=3000,icon='Spell_Shadow_MindBomb'},
  ['Bomba dura de cobre']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Bomba grande de bronce']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Bomba grande de cobre']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Bomba grande de hierro']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Bomba pequeña de bronce']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Bombardeo']={t=3000,icon='Ability_GolemStormBolt'},
  ['Bombardeo II']={t=3000,icon='Ability_GolemStormBolt'},
  ['Bramido amenazante']={t=1000,icon='Ability_Racial_Cannibalize'},
  ['Bramido desalentador']={t=1000,icon='Ability_Racial_Cannibalize'},
  ['Bramido funesto']={t=1000,icon='Ability_Racial_Cannibalize'},
  ['Bramido intimidador']={t=1000,icon='Ability_Racial_Cannibalize'},
  ['Bumerán de Linken']={t=500,icon='INV_Weapon_ShortBlade_10'},
  ['Burbuja de agua']={t=1000,icon='Spell_Frost_Wisp'},
  ['Buscar fragmento de reliquia']={t=5000,icon='Temp'},
  ['Bórrame']={t=4000,icon='INV_Scroll_02'},
  ['Caballo de combate esquelético morado']={t=3000,icon='Ability_Mount_Undeadhorse'},
  ['Caballo de combate rojo esquelético']={t=3000,icon='Ability_Mount_Undeadhorse'},
  ['Caballo esquelético']={t=3000,icon='Ability_Mount_Undeadhorse'},
  ['Caballo esquelético azul']={t=3000,icon='Ability_Mount_Undeadhorse'},
  ['Caballo esquelético marrón']={t=3000,icon='Ability_Mount_Undeadhorse'},
  ['Caballo marrón']={t=3000,icon='Ability_Mount_RidingHorse'},
  ['Caballo pinto']={t=3000,icon='Ability_Mount_RidingHorse'},
  ['Caballo rojo esquelético']={t=3000,icon='Ability_Mount_Undeadhorse'},
  ['Cadena de relámpagos']={t=2500,icon='Spell_Nature_ChainLightning'},
  ['Cadenas de hielo']={t=1300,icon='Spell_Frost_ChainsOfIce'},
  ['Calmar animal']={t=1500,icon='Ability_Hunter_BeastSoothe'},
  ['Calor intenso']={t=1000,icon='Spell_Shadow_ShadowWordPain'},
  ['Cambio de forma de Ruul Garrescarcha (DND)']={t=1000,icon='Temp'},
  ['Cambio de polaridad']={t=3000,icon='Spell_Nature_Lightning'},
  ['Campana de Shay']={t=4500,icon='Temp'},
  ['Capturando termitas']={t=5000,icon='Temp'},
  ['Capturar Grark']={t=3000,icon='Temp'},
  ['Capturar cachorro de lupo']={t=2500,icon='Temp'},
  ['Carga de gran marforio']={t=5000,icon='Temp'},
  ['Carga pequeña de seforio']={t=5000,icon='Temp'},
  ['Carga potente de seforio']={t=5000,icon='Temp'},
  ['Cargador de batalla de Pico Tormenta']={t=3000,icon='Ability_Mount_MountainRam'},
  ['Cargador de la Muerte']={t=3000,icon='Ability_Mount_Undeadhorse'},
  ['Cargando']={t=5000,icon='Spell_Shadow_EvilEye'},
  ['Carnero azul']={t=3000,icon='Ability_Mount_MountainRam'},
  ['Carnero blanco']={t=3000,icon='Ability_Mount_MountainRam'},
  ['Carnero blanco veloz']={t=3000,icon='Ability_Mount_MountainRam'},
  ['Carnero de Escarcha']={t=3000,icon='Ability_Mount_MountainRam'},
  ['Carnero de guerra negro']={t=3000,icon='Ability_Mount_MountainRam'},
  ['Carnero gris']={t=3000,icon='Ability_Mount_MountainRam'},
  ['Carnero gris veloz']={t=3000,icon='Ability_Mount_MountainRam'},
  ['Carnero marrón']={t=3000,icon='Ability_Mount_MountainRam'},
  ['Carnero marrón veloz']={t=3000,icon='Ability_Mount_MountainRam'},
  ['Carnero negro']={t=3000,icon='Ability_Mount_MountainRam'},
  ['Carámbano']={t=1500,icon='Spell_Frost_FrostBolt02'},
  ['Cascada de rosas']={t=500,icon='INV_Misc_Dust_04'},
  ['Cañon de disparo del Mar Sur']={t=5000,icon='Spell_Fire_FireBolt02'},
  ['Cañón de Fuego']={t=2000,icon='Temp'},
  ['Cañón de llamas']={t=1500,icon='Spell_Fire_FlameBolt'},
  ['Cebo de Miblon']={t=2000,icon='INV_Misc_Food_50'},
  ['Cegación de cristal']={t=2000,icon='Spell_Shadow_Teleport'},
  ['Cerrando']={t=1000,icon='Temp'},
  ['Cerveza negra de Kreeg']={t=1000,icon='INV_Drink_05'},
  ['Chamuscar']={t=1500,icon='Spell_Fire_SoulBurn'},
  ['Chispa']={t=2000,icon='Spell_Nature_Lightning'},
  ['Choque']={t=1000,icon='Temp'},
  ['Choque de olas']={t=2000,icon='Spell_Frost_FrostNova'},
  ['Clamor bramante']={t=1500,icon='Spell_Fire_Fire'},
  ['Clamor glacial']={t=1000,icon='Spell_Frost_FrostNova'},
  ['Clon']={t=2500,icon='Spell_Shadow_BlackPlague'},
  ['Cocina de Chefita']={t=2000,icon='Spell_Holy_Heal'},
  ['Colocando antorcha de almenara']={t=2300,icon='Temp'},
  ['Colocando estandarte']={t=2300,icon='Temp'},
  ['Colocando explosivos de Smokey']={t=3000,icon='Temp'},
  ['Colocando la antorcha de Guse']={t=5000,icon='Temp'},
  ['Colocando la antorcha de Ichman']={t=5000,icon='Temp'},
  ['Colocando la antorcha de Jeztor']={t=5000,icon='Temp'},
  ['Colocando la antorcha de Mulverick']={t=5000,icon='Temp'},
  ['Colocando la antorcha de Ryson']={t=5000,icon='Temp'},
  ['Colocando la antorcha de Slidore']={t=5000,icon='Temp'},
  ['Colocando la antorcha de Vipore']={t=5000,icon='Temp'},
  ['Colocando trampa para osos']={t=2000,icon='Temp'},
  ['Colocar boya Arcana']={t=2000,icon='Temp'},
  ['Colocar cebo']={t=4000,icon='Temp'},
  ['Combinar antorcha']={t=5000,icon='Temp'},
  ['Comienzo de brasadivino']={t=5000,icon='Spell_Nature_EarthBindTotem'},
  ['Comprobando temperatura']={t=2000,icon='Temp'},
  ['Conexión con cámara gnómica']={t=3000,icon='Temp'},
  ['Conexión con cámara goblin']={t=3000,icon='Temp'},
  ['Congelación']={t=4000,icon='Spell_Frost_Glacier'},
  ['Congelar huevo grajero']={t=500,icon='Temp'},
  ['Congelar huevo grajero: prototipo']={t=500,icon='Temp'},
  ['Conjurar Altar de Invocación']={t=10000,icon='Temp'},
  ['Conjurar Corcel Nefasto Furis MUÑECO DND']={t=5000,icon='Temp'},
  ['Conjurar Círculo de llamamiento']={t=10000,icon='Temp'},
  ['Conjurar grieta del sueño']={t=10000,icon='Temp'},
  ['Conjuro de aparición de Arugal']={t=2000,icon='Temp'},
  ['Consecución veraz']={t=500,icon='Spell_Shadow_Charm'},
  ['Consumo de alma']={t=4000,icon='Ability_Racial_Cannibalize'},
  ['Contar un chiste']={t=2000,icon='Spell_Shadow_LifeDrain'},
  ['Contrahechizo de Dios malvado']={t=300000,icon='Temp'},
  ['Control mental']={t=3000,icon='Spell_Shadow_ShadowWordDominate'},
  ['Corazón de Hakkar:']={t=2000,icon='Temp'},
  ['Corcel blanco veloz']={t=3000,icon='Ability_Mount_RidingHorse'},
  ['Corcel de guerra esquelético verde']={t=3000,icon='Ability_Mount_Undeadhorse'},
  ['Corcel de guerra negro']={t=3000,icon='Ability_Mount_NightmareHorse'},
  ['Corcel esquelético']={t=3000,icon='Ability_Mount_Undeadhorse'},
  ['Corcel marrón veloz']={t=3000,icon='Ability_Mount_RidingHorse'},
  ['Corrupción']={t=2000,icon='Spell_Shadow_AbominationExplosion'},
  ['Cosechar vida']={t=1000,icon='Spell_Shadow_Requiem'},
  ['Crear PX83-Enigmatrón']={t=2000,icon='INV_Misc_Bowl_01'},
  ['Crear agua de los profetas']={t=5000,icon='Spell_Shadow_LifeDrain'},
  ['Crear arca de contención']={t=500,icon='Temp'},
  ['Crear arca de contención llena']={t=2000,icon='Temp'},
  ['Crear conjunto de lanzacohetes']={t=2000,icon='INV_Misc_EngGizmos_03'},
  ['Crear conjunto de tótem Secacorteza']={t=2000,icon='Spell_Lightning_LightningBolt01'},
  ['Crear cuenco de visión']={t=2500,icon='INV_Misc_Bowl_01'},
  ['Crear fisura']={t=3000,icon='Temp'},
  ['Crear lanzacohetes de Fuegos artificiales']={t=2000,icon='INV_Musket_04'},
  ['Crear orbe de mago']={t=4000,icon='Temp'},
  ['Crear paquete de reliquia']={t=1000,icon='Temp'},
  ['Crear pergamino']={t=5000,icon='INV_Scroll_05'},
  ['Crear piedra de salud']={t=3000,icon='INV_Stone_04'},
  ['Crear piedra de salud (inferior)']={t=3000,icon='INV_Stone_04'},
  ['Crear piedra de salud (menor)']={t=3000,icon='INV_Stone_04'},
  ['Crear piedra de salud (sublime)']={t=3000,icon='INV_Stone_04'},
  ['Crear piedra de salud (superior)']={t=3000,icon='INV_Stone_04'},
  ['Crear sapta']={t=3000,icon='INV_Misc_Food_09'},
  ['Crear toga de mago']={t=4000,icon='Temp'},
  ['Crear trituradora']={t=1000,icon='INV_Misc_Gear_01'},
  ['Crear tótem purificador']={t=5000,icon='Spell_Shadow_LifeDrain'},
  ['Crear visualización de objeto (DND)']={t=5000,icon='Spell_Shadow_SoulGem'},
  ['Crema muy aframbuesada']={t=1000,icon='INV_ValentinesChocolate02'},
  ['Crinesnavaja']={t=1000,icon='Spell_Nature_Thorns'},
  ['Cristal de resonita encantado']={t=5000,icon='Temp'},
  ['Curación en cadena']={t=2500,icon='Spell_Nature_HealingWaveGreater'},
  ['Curación en masa']={t=1000,icon='Spell_Holy_GreaterHeal'},
  ['Curación inferior']={t=2500,icon='Spell_Holy_LesserHeal'},
  ['Curación superior']={t=3000,icon='Spell_Holy_GreaterHeal'},
  ['Curar']={t=3000,icon='Spell_Holy_Heal02'},
  ['Curar a Tharnariun 1']={t=750,icon='Spell_Nature_RemoveDisease'},
  ['Curar enfermedad']={t=2500,icon='Spell_Holy_NullifyDisease'},
  ['Curar hiedra tallovil']={t=500,icon='Temp'},
  ['Custodia de Escarcha rápida']={t=1500,icon='Spell_Fire_SealOfFire'},
  ['Custodia de curación']={t=2000,icon='Spell_Holy_LayOnHands'},
  ['Custodia de llama rápida']={t=1500,icon='Spell_Fire_SealOfFire'},
  ['Custodia excelente de curación']={t=2000,icon='Spell_Holy_LayOnHands'},
  ['Cántico de manifestación']={t=2000,icon='Spell_Magic_LesserInvisibilty'},
  ['Círculo curativo']={t=3000,icon='Spell_Holy_BlessingOfProtection'},
  ['Cólera']={t=2000,icon='Spell_Nature_AbolishMagic'},
  ['Cólera de Thule']={t=1500,icon='Spell_Shadow_UnholyFrenzy'},
  ['Cólera sagrada']={t=2000,icon='Spell_Holy_Excorcism'},
  ['Dañar vehículo']={t=2000,icon='Spell_Fire_Fire'},
  ['Debilidad Arcana']={t=5000,icon='INV_Misc_QirajiCrystal_01'},
  ['Debilidad a la Escarcha']={t=5000,icon='INV_Misc_QirajiCrystal_04'},
  ['Debilidad a las Sombras']={t=5000,icon='INV_Misc_QirajiCrystal_05'},
  ['Debilidad de Fuego']={t=5000,icon='INV_Misc_QirajiCrystal_02'},
  ['Debilidad natural']={t=5000,icon='INV_Misc_QirajiCrystal_03'},
  ['Defensa de Valiente']={t=3000,icon='Spell_Holy_BlessingOfProtection'},
  ['Defibrilar']={t=4000,icon='Spell_Nature_Purge'},
  ['Deflagración Arcana']={t=1500,icon='Spell_Nature_WispSplode'},
  ['Dejando colgante']={t=5000,icon='Temp'},
  ['Dejar augurador']={t=3000,icon='Temp'},
  ['Dejar espada sin templar']={t=1000,icon='Temp'},
  ['Dejar imán fantasma']={t=1500,icon='Temp'},
  ['Dejar restos de león']={t=2500,icon='INV_Misc_Bowl_01'},
  ['Dejar restos de trillanodonte']={t=2500,icon='INV_Misc_Bowl_01'},
  ['Dejar sello sin forjar']={t=500,icon='Temp'},
  ['Delicia mantecada']={t=1000,icon='INV_ValentinesChocolate01'},
  ['Denaje de alma']={t=2000,icon='Spell_Shadow_LifeDrain02'},
  ['Desactivar trampa']={t=2000,icon='Spell_Shadow_GrimWard'},
  ['Desaparición de espíritu']={t=500,icon='Temp'},
  ['Desbloqueo de Ashcrombe']={t=4000,icon='Spell_Nature_MoonKey'},
  ['Desbloqueo de Khadgar']={t=10000,icon='INV_Misc_Key_14'},
  ['Descarga Arcana']={t=1000,icon='Spell_Arcane_StarFire'},
  ['Descarga Arcana cargada']={t=7000,icon='Spell_Arcane_StarFire'},
  ['Descarga abisal']={t=3000,icon='Spell_Shadow_ShadowBolt'},
  ['Descarga de Escarcha']={t=3000,icon='Spell_Frost_FrostBolt02'},
  ['Descarga de Fuego']={t=2000,icon='Spell_Fire_FireBolt'},
  ['Descarga de Fuego II']={t=3000,icon='Spell_Fire_FireBolt02'},
  ['Descarga de Fuego III']={t=3000,icon='Spell_Fire_FireBolt02'},
  ['Descarga de Fuego IV']={t=3000,icon='Spell_Fire_FireBolt02'},
  ['Descarga de babosa']={t=2500,icon='Spell_Nature_CorrosiveBreath'},
  ['Descarga de hielo']={t=2000,icon='Spell_Frost_FrostBolt02'},
  ['Descarga de lagartija']={t=2000,icon='Spell_Nature_Lightning'},
  ['Descarga de las Sombras']={t=3000,icon='Spell_Shadow_ShadowBolt'},
  ['Descarga de radiación']={t=3000,icon='Spell_Shadow_CorpseExplode'},
  ['Descarga de relámpagos']={t=3000,icon='Spell_Nature_Lightning'},
  ['Descarga de veneno']={t=2500,icon='Spell_Nature_CorrosiveBreath'},
  ['Descarga débil de hielo']={t=2200,icon='Spell_Frost_FrostBolt02'},
  ['Descarga en cadena']={t=2500,icon='Spell_Nature_ChainLightning'},
  ['Descarga tormentosa']={t=1000,icon='INV_Hammer_01'},
  ['Descarga tóxica']={t=2500,icon='Spell_Nature_CorrosiveBreath'},
  ['Descomponer el alma']={t=2000,icon='Spell_Holy_HarmUndeadAura'},
  ['Descorazonado']={t=10000,icon='INV_Misc_Rune_01'},
  ['Desencantar']={t=3000,icon='Spell_Holy_RemoveCurse'},
  ['Deseo oscuro']={t=1000,icon='INV_ValentinesChocolate04'},
  ['Desollando']={t=2000,icon='INV_Misc_Pelt_Wolf_01'},
  ['Despedazar alma']={t=2000,icon='Spell_Fire_Fire'},
  ['Despertar al Guarda de la cámara acorazada']={t=5000,icon='Spell_Nature_Earthquake'},
  ['Despertar al Rompealmas']={t=5000,icon='Temp'},
  ['Despertar de Archaedas visual (DND)']={t=1500,icon='Spell_Nature_Earthquake'},
  ['Despertar de eneno pétro visual']={t=1500,icon='Spell_Nature_Earthquake'},
  ['Desplazar fisura temporal']={t=5000,icon='Temp'},
  ['Destello curativo']={t=1500,icon='Spell_Holy_FlashHeal'},
  ['Destello de Luz']={t=1500,icon='Spell_Holy_FlashHeal'},
  ['Destello de las Sombras']={t=500,icon='Spell_Shadow_DetectLesserInvisibility'},
  ['Desterrar']={t=1500,icon='Spell_Shadow_Cripple'},
  ['Desterrar exiliado acuoso']={t=1000,icon='Spell_Shadow_LifeDrain'},
  ['Desterrar exiliado ardiente']={t=1000,icon='Spell_Shadow_LifeDrain'},
  ['Desterrar exiliado de trueno']={t=1000,icon='Spell_Shadow_LifeDrain'},
  ['Destruir huevo']={t=3000,icon='INV_Misc_MonsterClaw_02'},
  ['Destruir magneto fantasma']={t=10000,icon='Temp'},
  ['Destruir tienda']={t=2500,icon='Temp'},
  ['Desvanecimiento de esbirros de Urok']={t=2000,icon='Temp'},
  ['Desvío de hechizos (NYI)']={t=1000,icon='Temp'},
  ['Detonación']={t=5000,icon='Spell_Fire_SelfDestruct'},
  ['Detonación remota']={t=1000,icon='INV_Misc_StoneTablet_04'},
  ['Detonar']={t=2000,icon='Temp'},
  ['Dientes de sable dorado']={t=3000,icon='Ability_Mount_JungleTiger'},
  ['Dientes de sable pardo']={t=3000,icon='Ability_Mount_JungleTiger'},
  ['Dinamita']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Dinamita Ez-Thro']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Dinamita de las Minas de la Muerte']={t=2000,icon='Spell_Fire_SelfDestruct'},
  ['Dinamita densa']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Dinamita dura']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Dinamita gruesa']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Dinamita pesada']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Dinamita pura']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Disfraz de campesino']={t=3000,icon='Ability_Rogue_Disguise'},
  ['Disfraz de enano Hierro Negro']={t=3000,icon='Ability_Rogue_Disguise'},
  ['Disfraz de peón']={t=3000,icon='Ability_Rogue_Disguise'},
  ['Disfraz de pirata de los Mares del Sur']={t=3000,icon='Ability_Rogue_Disguise'},
  ['Disfraz de zahorí de Dalaran']={t=3000,icon='Ability_Rogue_Disguise'},
  ['Disfraz defias']={t=3000,icon='Ability_Rogue_Disguise'},
  ['Disfraz del Sindicato']={t=3000,icon='Ability_Rogue_Disguise'},
  ['Disfraz trogg de rompecantos']={t=3000,icon='Ability_Rogue_Disguise'},
  ['Disipación de masa']={t=1000,icon='Spell_Shadow_Teleport'},
  ['Disipar']={t=1000,icon='Spell_Holy_DispelMagic'},
  ['Disipar superior']={t=4000,icon='Spell_Arcane_StarFire'},
  ['Disipar veneno']={t=2000,icon='Spell_Holy_Purify'},
  ['Disparar arco']={t=1000,icon='Ability_Marksmanship'},
  ['Disparar arma de fuego']={t=1000,icon='Ability_Marksmanship'},
  ['Disparar ballesta']={t=1000,icon='Ability_Marksmanship'},
  ['Disparar cohete']={t=3000,icon='INV_Ammo_Bullet_03'},
  ['Disparar misil']={t=3000,icon='INV_Ammo_Bullet_03'},
  ['Disparo de puntería']={t=3000,icon='INV_Spear_07'},
  ['Disparo de veneno']={t=2000,icon='Ability_Poisons'},
  ['Disparo enfermo']={t=2000,icon='Spell_Shadow_CallofBone'},
  ['Disparo explosivo']={t=1000,icon='Spell_Fire_Fireball02'},
  ['Disparo explotante']={t=1000,icon='Spell_Fire_Fireball02'},
  ['Disparo falso']={t=2000,icon='Ability_Marksmanship'},
  ['Dolor abrasador']={t=1500,icon='Spell_Fire_SoulBurn'},
  ['Dolor entumecedor']={t=1500,icon='Spell_Nature_CorrosiveBreath'},
  ['Dominación']={t=1000,icon='Spell_Shadow_ShadowWordDominate'},
  ['Dominar mente']={t=2000,icon='Spell_Shadow_ShadowWordDominate'},
  ['Dominio del alma']={t=3000,icon='Spell_Shadow_ShadowWordDominate'},
  ['Dormir']={t=1500,icon='Spell_Nature_Sleep'},
  ['Draco-encarcenadora 900']={t=2000,icon='Temp'},
  ['Drenar exclavo']={t=1000,icon='Spell_Shadow_ChillTouch'},
  ['Efecto de Segra Espinoscura']={t=3000,icon='Temp'},
  ['Efecto de polvo de reno']={t=8000,icon='Temp'},
  ['Efecto de ritual de condena']={t=10000,icon='Spell_Arcane_PortalDarnassus'},
  ['Efecto de ritual de invocación']={t=5000,icon='Temp'},
  ['El despertar de Merithra']={t=2000,icon='Temp'},
  ['El grande']={t=3000,icon='Spell_Fire_SelfDestruct'},
  ['Elemental de Fuego']={t=3000,icon='Ability_Temp'},
  ['Elemental de tierra']={t=3000,icon='Ability_Temp'},
  ['Elementales de Sarilus']={t=3000,icon='Spell_Shadow_RaiseDead'},
  ['Eliminar bomba fétida']={t=5000,icon='Temp'},
  ['Embate']={t=1500,icon='Ability_Warrior_DecisiveStrike'},
  ['Emblema de sanción']={t=1000,icon='INV_Shield_19'},
  ['Empapador afinado']={t=2000,icon='Spell_Holy_SearingLight'},
  ['Encadenar no-muerto']={t=1500,icon='Spell_Nature_Slow'},
  ['Encantamiento Mor\'rogal']={t=1300,icon='Temp'},
  ['Encantar Anales de Villa Darrow']={t=3500,icon='Temp'},
  ['Encoger']={t=3000,icon='Spell_Shadow_AntiShadow'},
  ['Enervar']={t=1500,icon='Ability_Creature_Poison_03'},
  ['Enfocando']={t=5000,icon='Temp'},
  ['Engullidor de energía']={t=1500,icon='Spell_Shadow_Cripple'},
  ['Enjambre de Nozdormu +1000']={t=1000,icon='Temp'},
  ['Enjambre de langostas']={t=3000,icon='Spell_Nature_InsectSwarm'},
  ['Enjaular']={t=2000,icon='Spell_Shadow_Teleport'},
  ['Enredaderas']={t=1500,icon='Spell_Nature_StrangleVines'},
  ['Ensanchar']={t=2000,icon='Spell_Nature_Strength'},
  ['Enseñar el Rugir del apocalipsis']={t=1000,icon='Temp'},
  ['Enterrar restos de Samuel']={t=2000,icon='Temp'},
  ['Envenenar herida']={t=3000,icon='INV_Misc_Herb_16'},
  ['Equilibrio de la Naturaleza']={t=3000,icon='Temp'},
  ['Equilibrio del fracaso natural']={t=10000,icon='Temp'},
  ['Equipo de dibujo']={t=7000,icon='Temp'},
  ['Esbirro de Morganth']={t=2500,icon='Spell_Totem_WardOfDraining'},
  ['Esbirros de Malathrom']={t=1000,icon='Spell_Shadow_CorpseExplode'},
  ['Escape de la banda de Bly']={t=10000,icon='INV_Misc_Rune_01'},
  ['Escarabajos de la cripta']={t=1500,icon='Spell_Shadow_CarrionSwarm'},
  ['Esclavizar demonio']={t=3000,icon='Spell_Shadow_EnslaveDemon'},
  ['Escudo antimagia']={t=2000,icon='Spell_Shadow_AntiMagicShell'},
  ['Escudo de Fuego']={t=1000,icon='Spell_Fire_Immolation'},
  ['Escudo de Fuego II']={t=1000,icon='Spell_Fire_Immolation'},
  ['Escudo de Fuego III']={t=1000,icon='Spell_Fire_Immolation'},
  ['Escudo de Fuego IV']={t=1000,icon='Spell_Fire_Immolation'},
  ['Escudo de las Sombras']={t=1000,icon='Spell_Shadow_AntiShadow'},
  ['Escudo de refracción']={t=1000,icon='Spell_Shadow_Teleport'},
  ['Escupellamas']={t=3000,icon='Spell_Fire_FlameBolt'},
  ['Espada fanática']={t=1000,icon='Spell_Fire_Immolation'},
  ['EspecialCriatura']={t=2000,icon='Temp'},
  ['Espíritu Arcano II']={t=1000,icon='Spell_Holy_MagicalSentry'},
  ['Espíritu Arcano III']={t=1000,icon='Spell_Holy_MagicalSentry'},
  ['Espíritu Arcano IV']={t=1000,icon='Spell_Holy_MagicalSentry'},
  ['Espíritu Arcano V']={t=1000,icon='Spell_Holy_MagicalSentry'},
  ['Espíritu ancestral']={t=10000,icon='Spell_Nature_Regenerate'},
  ['Espíritu feral']={t=3000,icon='Spell_Nature_SpiritWolf'},
  ['Espíritu feral II']={t=3000,icon='Spell_Nature_SpiritWolf'},
  ['Espíritu manifiesto']={t=5000,icon='Spell_Totem_WardOfDraining'},
  ['Espíritus encantados']={t=2000,icon='Spell_Shadow_BlackPlague'},
  ['Establecer campana ritual (DND)']={t=3000,icon='Temp'},
  ['Establecer nodo ritual']={t=3000,icon='Temp'},
  ['Establecer vela ritual (DND)']={t=3000,icon='Temp'},
  ['Excavando en búsqueda de cobalto']={t=1500,icon='Temp'},
  ['Excavar']={t=1000,icon='Ability_Vanish'},
  ['Exorcisar Atiesh']={t=20000,icon='Temp'},
  ['Exorcisar espíritus']={t=4000,icon='Temp'},
  ['Explosiones de moco']={t=2000,icon='Temp'},
  ['Explosión de arena']={t=2000,icon='Spell_Nature_Cyclone'},
  ['Explosión de arrabio']={t=2000,icon='Spell_Fire_Fire'},
  ['Explosión de cohetes']={t=3000,icon='Temp'},
  ['Explosión de llamas']={t=7000,icon='Spell_Fire_SelfDestruct'},
  ['Explosión de magma']={t=1000,icon='Spell_Fire_FlameShock'},
  ['Explosión de minero esquelético']={t=5000,icon='Spell_Fire_SelfDestruct'},
  ['Explosión de relámpagos']={t=3200,icon='Spell_Nature_Lightning'},
  ['Explosión mental']={t=1500,icon='Spell_Shadow_UnholyFrenzy'},
  ['Explosión zapadora']={t=5000,icon='Spell_Fire_SelfDestruct'},
  ['Extinguir']={t=2000,icon='Temp'},
  ['Extinguir llama eterna']={t=1000,icon='Temp'},
  ['Extracción de la cardortiga']={t=2000,icon='Spell_Shadow_Haunting'},
  ['Fango negro']={t=3000,icon='Spell_Shadow_CallofBone'},
  ['Fantasmas encantados']={t=2000,icon='Spell_Shadow_BlackPlague'},
  ['Fatiga afiebrada']={t=3000,icon='Spell_Nature_NullifyDisease'},
  ['Festín de alas']={t=1000,icon='INV_Misc_MonsterScales_14'},
  ['Fiebre de grupo']={t=1000,icon='Spell_Shadow_DarkSummoning'},
  ['Filo cortante']={t=3000,icon='Temp'},
  ['Filo cortante II']={t=3000,icon='Temp'},
  ['Filo cortante III']={t=3000,icon='Temp'},
  ['Filo cortante IV']={t=3000,icon='Temp'},
  ['Filo cortante V']={t=3000,icon='Temp'},
  ['Flecha de Aynasha']={t=500,icon='Temp'},
  ['Flecha de cupido']={t=1000,icon='Temp'},
  ['Flecha negra']={t=2000,icon='Ability_TheBlackArrow'},
  ['Fogonazo']={t=3000,icon='Spell_Fire_SelfDestruct'},
  ['Forjar Puño de Verigan']={t=600,icon='Spell_Holy_RighteousFury'},
  ['Forma de buho']={t=5000,icon='Spell_Nature_RavenForm'},
  ['Forma de fúrbolg']={t=2000,icon='INV_Misc_MonsterClaw_04'},
  ['Forma del Acechalunas (sin invis)']={t=1000,icon='Ability_Hibernation'},
  ['Forma felina vipore DND']={t=1000,icon='Temp'},
  ['Fragmentos óseos']={t=500,icon='Spell_Shadow_ScourgeBuild'},
  ['Fuego Sagrado']={t=3500,icon='Spell_Holy_SearingLight'},
  ['Fuego artificial']={t=500,icon='Temp'},
  ['Fuego de alma']={t=6000,icon='Spell_Fire_Fireball02'},
  ['Fuego de cañón']={t=1000,icon='Spell_Fire_FireBolt02'},
  ['Fuego elemental']={t=500,icon='Spell_Fire_Fireball02'},
  ['Fuego estelar']={t=3500,icon='Spell_Arcane_StarFire'},
  ['Fuego feérico']={t=2000,icon='Spell_Nature_FaerieFire'},
  ['Fuerza Peloescarcha']={t=1000,icon='Spell_Nature_UndyingStrength'},
  ['Fuerza de Arko\'narin']={t=4000,icon='Spell_Nature_AstralRecal'},
  ['Fuerza de los tiempos']={t=2000,icon='Spell_Shadow_Requiem'},
  ['Fuerza deteriorada']={t=2000,icon='Spell_Holy_HarmUndeadAura'},
  ['Fundir mineral']={t=1500,icon='Spell_Fire_SelfDestruct'},
  ['Furia elemental']={t=1000,icon='Spell_Fire_FireArmor'},
  ['Fusión de armadura disgregada']={t=2000,icon='Spell_Fire_Incinerate'},
  ['Gambito del Alba']={t=1500,icon='Temp'},
  ['Ganzúa']={t=5000,icon='Spell_Nature_MoonKey'},
  ['Gapo abominable']={t=2500,icon='Spell_Nature_CorrosiveBreath'},
  ['Gapo de veneno']={t=2500,icon='Spell_Nature_CorrosiveBreath'},
  ['Gapo de veneno corrosivo']={t=2500,icon='Spell_Nature_CorrosiveBreath'},
  ['Gapo de ácido corrosivo']={t=3000,icon='Spell_Nature_Acid_01'},
  ['Gapo enfermo']={t=3000,icon='Spell_Shadow_CreepingPlague'},
  ['Gapo envenenado']={t=2000,icon='Spell_Nature_CorrosiveBreath'},
  ['Gapo tóxico']={t=2500,icon='Spell_Nature_CorrosiveBreath'},
  ['Gapo ácido']={t=3000,icon='Spell_Nature_Acid_01'},
  ['Garra de la bestia']={t=1000,icon='Spell_Nature_Regeneration'},
  ['Garra de la bestia II']={t=1000,icon='Spell_Nature_Regeneration'},
  ['Garra de la bestia III']={t=1000,icon='Spell_Nature_Regeneration'},
  ['Garramiedo']={t=1000,icon='Spell_Shadow_ShadowPact'},
  ['Gema abisal']={t=3000,icon='Temp'},
  ['Gema de la serpiente']={t=5000,icon='Temp'},
  ['Golpe de gárgola']={t=1500,icon='Spell_Shadow_ShadowBolt'},
  ['Golpear']={t=2000,icon='Temp'},
  ['Golpear el gong de Zul\'Farrak']={t=500,icon='Temp'},
  ['Gong']={t=500,icon='Temp'},
  ['Grabada de torio']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Gran curación']={t=4000,icon='Spell_Holy_Heal'},
  ['Gran kodo blanco']={t=3000,icon='Ability_Mount_Kodo_01'},
  ['Gran kodo gris']={t=3000,icon='Ability_Mount_Kodo_01'},
  ['Gran kodo marrón']={t=3000,icon='Ability_Mount_Kodo_03'},
  ['Gran lobo maderero']={t=3000,icon='Ability_Mount_BlackDireWolf'},
  ['Granada de hierro']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Grog verde de Gordok']={t=1000,icon='INV_Drink_03'},
  ['Grupo de teletransporte sencillo']={t=2000,icon='Spell_Magic_LesserInvisibilty'},
  ['Guardianes de Ilkrud']={t=5000,icon='Spell_Shadow_SummonVoidWalker'},
  ['Guardián abisario']={t=3000,icon='Spell_Shadow_SummonVoidWalker'},
  ['Gusano comecarne']={t=5000,icon='INV_Misc_Orb_03'},
  ['Géiser monumental']={t=1500,icon='Spell_Frost_SummonWaterElemental'},
  ['HECHIZO DE MISIÓN DE CHU']={t=4000,icon='Spell_Shadow_LifeDrain'},
  ['Habilidad de los Renegados']={t=2500,icon='Spell_Shadow_AntiShadow'},
  ['Habla con las cabezas']={t=5000,icon='Spell_Shadow_LifeDrain'},
  ['Harpón envenenado']={t=2000,icon='Ability_Poisons'},
  ['Haz ocular']={t=2000,icon='Spell_Nature_CallStorm'},
  ['Hechizo de aparación de cría de El Granjero']={t=500,icon='Temp'},
  ['Hechizo de prueba del editor']={t=250,icon='Temp'},
  ['Hender pilar']={t=5000,icon='Temp'},
  ['Hibernar']={t=1500,icon='Spell_Nature_Sleep'},
  ['Hilandera de sacrificios']={t=10000,icon='Temp'},
  ['Hoguera básica']={t=10000,icon='Spell_Fire_Fire'},
  ['Hoguera luminosa']={t=10000,icon='Spell_Fire_Fire'},
  ['Homenaje a Uther']={t=2000,icon='Temp'},
  ['Hongos Mirkfallon']={t=3000,icon='Spell_Holy_HarmUndeadAura'},
  ['Humus espeluznante']={t=3000,icon='Spell_Shadow_CreepingPlague'},
  ['Identificar linaje']={t=10000,icon='Spell_Lightning_LightningBolt01'},
  ['Ignición de la carne']={t=2000,icon='Spell_Fire_Fire'},
  ['Ilusión permanente Tyrion']={t=3000,icon='Ability_Rogue_Disguise'},
  ['Ilusión permanente superiora Tyriona']={t=3000,icon='Ability_Rogue_Disguise'},
  ['Ilustración']={t=2000,icon='Spell_Shadow_Fumble'},
  ['Imbuir arma: bestiacida']={t=5000,icon='Spell_Holy_GreaterHeal'},
  ['Imbuir capa: protección inferior']={t=5000,icon='Spell_Holy_GreaterHeal'},
  ['Imbuir capa: resistencia menor']={t=5000,icon='Spell_Holy_GreaterHeal'},
  ['Imbuir pechera: absorber']={t=5000,icon='Spell_Holy_GreaterHeal'},
  ['Imbuir pechera: absorber inferior']={t=5000,icon='Spell_Holy_GreaterHeal'},
  ['Imbuir pechera: espíritu inferior']={t=5000,icon='Spell_Holy_GreaterHeal'},
  ['Imbuir pechera: espíritu menor']={t=5000,icon='Spell_Holy_GreaterHeal'},
  ['Impacto de tirador']={t=2000,icon='Ability_Marksmanship'},
  ['Implosión']={t=10000,icon='Spell_Fire_SelfDestruct'},
  ['Incendiar área']={t=3000,icon='Spell_Fire_SelfDestruct'},
  ['Incineración']={t=5000,icon='Temp'},
  ['Incinerar']={t=2000,icon='Spell_Shadow_ChillTouch'},
  ['Inculcar espíritu de Lord Valthalak DND']={t=5000,icon='Temp'},
  ['Induciendo visión']={t=30000,icon='Spell_Shadow_LifeDrain'},
  ['Infección volátil']={t=2000,icon='Spell_Holy_HarmUndeadAura'},
  ['Inferno']={t=2000,icon='Spell_Shadow_SummonInfernal'},
  ['Inmersión visual']={t=1500,icon='Spell_Fire_Volcano'},
  ['Inmolar']={t=2000,icon='Spell_Fire_Immolation'},
  ['Interrumpir huevo grajero']={t=1000,icon='Temp'},
  ['Inutilizar']={t=3000,icon='Spell_Shadow_Cripple'},
  ['Invis colocando trampa para osos']={t=2000,icon='Temp'},
  ['Invisibilidad']={t=3000,icon='Spell_Nature_Invisibilty'},
  ['Invisibilidad inferior']={t=3000,icon='Spell_Magic_LesserInvisibilty'},
  ['Invisibilidad superior']={t=3000,icon='Spell_Nature_Invisibilty'},
  ['Invitación Lunar']={t=5000,icon='Spell_Arcane_TeleportMoonglade'},
  ['Invocación PNJ muñeco']={t=20000,icon='Spell_Shadow_UnsummonBuilding'},
  ['Invocar']={t=1000,icon='Spell_Arcane_Blink'},
  ['Invocar a Ancona']={t=1000,icon='Ability_Seal'},
  ['Invocar a Aquementas']={t=2000,icon='Temp'},
  ['Invocar a Ar\'lia']={t=2500,icon='Spell_Nature_GroundingTotem'},
  ['Invocar a Bombay']={t=1000,icon='Ability_Seal'},
  ['Invocar a Cicloniano']={t=10000,icon='Spell_Nature_EarthBind'},
  ['Invocar a Cockatiel']={t=1000,icon='Ability_Seal'},
  ['Invocar a Cockatoo']={t=1000,icon='Ability_Seal'},
  ['Invocar a Cockroach']={t=1000,icon='Ability_Seal'},
  ['Invocar a Dagun']={t=5000,icon='Temp'},
  ['Invocar a Diablo']={t=1000,icon='Ability_Seal'},
  ['Invocar a Echeyakee']={t=500,icon='Spell_Shadow_LifeDrain'},
  ['Invocar a Edana Garraodio']={t=4000,icon='Temp'},
  ['Invocar a Faeling']={t=1000,icon='Ability_Seal'},
  ['Invocar a Garraluna']={t=3000,icon='Temp'},
  ['Invocar a Gurky']={t=1000,icon='Ability_Seal'},
  ['Invocar a Horda del tesoro']={t=1500,icon='Temp'},
  ['Invocar a Horda del tesoro visual']={t=1500,icon='Temp'},
  ['Invocar a Ishamuhale']={t=2000,icon='Spell_Shadow_LifeDrain'},
  ['Invocar a Jubling']={t=1000,icon='Ability_Seal'},
  ['Invocar a Maine Coon']={t=1000,icon='Ability_Seal'},
  ['Invocar a Mostachia']={t=1000,icon='Ability_Seal'},
  ['Invocar a Murki']={t=1000,icon='Ability_Seal'},
  ['Invocar a Murky']={t=1000,icon='Ability_Seal'},
  ['Invocar a Myzrael']={t=10000,icon='Spell_Shadow_LifeDrain'},
  ['Invocar a Poley']={t=1000,icon='Ability_Seal'},
  ['Invocar a Ragnaros']={t=10000,icon='Spell_Fire_LavaSpawn'},
  ['Invocar a Rapidín']={t=1000,icon='Ability_Seal'},
  ['Invocar a Razelikh']={t=10000,icon='Temp'},
  ['Invocar a Senegal']={t=1000,icon='Ability_Seal'},
  ['Invocar a Siamés']={t=1000,icon='Ability_Seal'},
  ['Invocar a Tenebrosa']={t=10000,icon='Temp'},
  ['Invocar a Terky']={t=1000,icon='Ability_Seal'},
  ['Invocar a Thelrin DND']={t=1000,icon='Temp'},
  ['Invocar a Tronadora']={t=10000,icon='Temp'},
  ['Invocar a Vergonzoso-Rotam']={t=2500,icon='Temp'},
  ['Invocar a Zergling']={t=1000,icon='Ability_Seal'},
  ['Invocar a abisario']={t=10000,icon='Spell_Shadow_SummonVoidWalker'},
  ['Invocar a aguila lechuáguila']={t=1000,icon='Ability_Seal'},
  ['Invocar a alarmobot']={t=250,icon='INV_Gizmo_08'},
  ['Invocar a aliados Antárbol']={t=1500,icon='Spell_Nature_ForceOfNature'},
  ['Invocar a aparición de Bael\'Gar']={t=4000,icon='Spell_Fire_LavaSpawn'},
  ['Invocar a brizna élfica']={t=1000,icon='Ability_Seal'},
  ['Invocar a caballo de combate']={t=3000,icon='Spell_Nature_Swiftness'},
  ['Invocar a cachorro de tigre blanco']={t=1000,icon='Ability_Seal'},
  ['Invocar a cargador']={t=3000,icon='Ability_Mount_Charger'},
  ['Invocar a conejo Pataneve']={t=1000,icon='Ability_Seal'},
  ['Invocar a conejo rabo de algodón']={t=1000,icon='Ability_Seal'},
  ['Invocar a corcel de la muerte']={t=3000,icon='Ability_Mount_Dreadsteed'},
  ['Invocar a corcel de la muerte de Xorothian']={t=5000,icon='Temp'},
  ['Invocar a corcel nefasto']={t=3000,icon='Spell_Nature_Swiftness'},
  ['Invocar a cría azur']={t=1000,icon='Ability_Seal'},
  ['Invocar a cría de bronce']={t=1000,icon='Ability_Seal'},
  ['Invocar a cría de la Torre']={t=2000,icon='Temp'},
  ['Invocar a cría de tiburón']={t=1000,icon='Ability_Seal'},
  ['Invocar a cría esmeralda']={t=1000,icon='Ability_Seal'},
  ['Invocar a crío oscura']={t=1000,icon='Ability_Seal'},
  ['Invocar a demonio del orbe']={t=5000,icon='Temp'},
  ['Invocar a devastador Magram']={t=4000,icon='Spell_Shadow_RaiseDead'},
  ['Invocar a diablillo']={t=10000,icon='Spell_Shadow_SummonImp'},
  ['Invocar a duendecejo dardo']={t=1000,icon='Ability_Seal'},
  ['Invocar a elemental de agua']={t=2000,icon='Spell_Shadow_SealOfKings'},
  ['Invocar a esbirro']={t=500,icon='Temp'},
  ['Invocar a esbirro de Tervosh']={t=4000,icon='Spell_Frost_Wisp'},
  ['Invocar a escarabajo carroñero']={t=2000,icon='Spell_Shadow_CarrionSwarm'},
  ['Invocar a espectro del sindicato']={t=1000,icon='Spell_Shadow_Twilight'},
  ['Invocar a espíritu de jabalí']={t=1500,icon='Spell_Magic_PolymorphPig'},
  ['Invocar a espíritu de viejo']={t=4000,icon='Spell_Nature_Purge'},
  ['Invocar a espíritu del pantano']={t=1500,icon='Spell_Nature_AbolishMagic'},
  ['Invocar a espíritu estridador']={t=2000,icon='Temp'},
  ['Invocar a esqueleto']={t=2000,icon='Spell_Shadow_RaiseDead'},
  ['Invocar a esqueleto delicado']={t=10000,icon='Spell_Shadow_RaiseDead'},
  ['Invocar a fantasma ilusorio']={t=2000,icon='Spell_Fire_SealOfFire'},
  ['Invocar a faz de Gunther']={t=2000,icon='Temp'},
  ['Invocar a felino plateado']={t=1000,icon='Ability_Seal'},
  ['Invocar a gallina de corral']={t=1000,icon='Ability_Seal'},
  ['Invocar a gallina de pradera']={t=1000,icon='Ability_Seal'},
  ['Invocar a gallina mecánica']={t=1000,icon='Ability_Seal'},
  ['Invocar a gatito blanco']={t=1000,icon='Ability_Seal'},
  ['Invocar a gatito común']={t=2000,icon='INV_Box_PetCarrier_01'},
  ['Invocar a gatito corrupto']={t=1000,icon='Ability_Seal'},
  ['Invocar a gran cornolechuza']={t=1000,icon='Ability_Seal'},
  ['Invocar a grifo de montar']={t=3000,icon='Ability_BullRush'},
  ['Invocar a guacamayo de alas verdes']={t=1000,icon='Ability_Seal'},
  ['Invocar a guardia escudero']={t=5000,icon='Spell_Nature_Purge'},
  ['Invocar a guardián de hechizos']={t=5000,icon='Spell_Nature_Purge'},
  ['Invocar a gárgolas Ventorroca']={t=10000,icon='Spell_Shadow_UnsummonBuilding'},
  ['Invocar a gólem por control remoto']={t=3000,icon='Ability_Repair'},
  ['Invocar a hipogrifillo']={t=1000,icon='Ability_Seal'},
  ['Invocar a huérfano']={t=1000,icon='Ability_Seal'},
  ['Invocar a infracaminante']={t=4000,icon='Spell_Shadow_GatherShadows'},
  ['Invocar a lacayo resucitado']={t=2000,icon='Spell_Shadow_RaiseDead'},
  ['Invocar a lechuza de las nieves']={t=1000,icon='Ability_Seal'},
  ['Invocar a loro de sangre']={t=1000,icon='Ability_Seal'},
  ['Invocar a los espíritus ancestrales']={t=2000,icon='Temp'},
  ['Invocar a maderor']={t=3000,icon='Spell_Nature_ProtectionformNature'},
  ['Invocar a manáfago']={t=10000,icon='Spell_Shadow_SummonFelHunter'},
  ['Invocar a manáfago Secacorteza']={t=3000,icon='Spell_Shadow_SummonFelHunter'},
  ['Invocar a mascolupo']={t=1000,icon='Ability_Seal'},
  ['Invocar a mentorrompe']={t=3000,icon='Temp'},
  ['Invocar a moco del pantano']={t=2500,icon='Spell_Shadow_BlackPlague'},
  ['Invocar a moquito repulsivo']={t=1000,icon='Ability_Seal'},
  ['Invocar a oniroguardianes ilusorios']={t=1000,icon='Spell_Shadow_Teleport'},
  ['Invocar a panda']={t=1000,icon='Ability_Seal'},
  ['Invocar a papagayo Hyacinth']={t=1000,icon='Ability_Seal'},
  ['Invocar a pequeño dragón rojo']={t=1000,icon='Ability_Seal'},
  ['Invocar a pequeño dragón verde']={t=1000,icon='Ability_Seal'},
  ['Invocar a perro de pradera']={t=1000,icon='Ability_Seal'},
  ['Invocar a quijaforte']={t=1000,icon='Ability_Seal'},
  ['Invocar a quijaforte alconil']={t=1000,icon='Ability_Seal'},
  ['Invocar a quijaforte cuerospalda']={t=1000,icon='Ability_Seal'},
  ['Invocar a quijaforte leñobeza']={t=1000,icon='Ability_Seal'},
  ['Invocar a rana de la isla']={t=1000,icon='Ability_Seal'},
  ['Invocar a rana de árbol']={t=1000,icon='Ability_Seal'},
  ['Invocar a rana flecha']={t=1000,icon='Ability_Seal'},
  ['Invocar a rana maderera']={t=1000,icon='Ability_Seal'},
  ['Invocar a rex córnico']={t=1000,icon='Ability_Seal'},
  ['Invocar a robot']={t=1000,icon='Ability_Seal'},
  ['Invocar a serpiente Escarlata']={t=1000,icon='Ability_Seal'},
  ['Invocar a serpiente albina']={t=1000,icon='Ability_Seal'},
  ['Invocar a serpiente carmesí']={t=1000,icon='Ability_Seal'},
  ['Invocar a serpiente de agua verde']={t=1000,icon='Ability_Seal'},
  ['Invocar a serpiente marrón']={t=1000,icon='Ability_Seal'},
  ['Invocar a sriviente infernal']={t=2000,icon='Spell_Shadow_SummonInfernal'},
  ['Invocar a suenanariz']={t=2000,icon='Spell_Nature_ProtectionformNature'},
  ['Invocar a súcubo']={t=10000,icon='Spell_Shadow_SummonSuccubus'},
  ['Invocar a taumaturgo']={t=5000,icon='Spell_Shadow_RaiseDead'},
  ['Invocar a tejedor de tinieblas Puño Negro']={t=5000,icon='Spell_Nature_Purge'},
  ['Invocar a telabrasada']={t=1000,icon='Ability_Seal'},
  ['Invocar a teurgista']={t=5000,icon='Spell_Nature_Purge'},
  ['Invocar a veterano Puño Negro']={t=5000,icon='Spell_Nature_Purge'},
  ['Invocar a víbora']={t=1500,icon='Spell_Nature_ResistMagic'},
  ['Invocar a víbora jirones']={t=1000,icon='Ability_Seal'},
  ['Invocar a yeti mecánico tranquilo']={t=1000,icon='Ability_Seal'},
  ['Invocar a zombi']={t=2000,icon='Spell_Shadow_RaiseDead'},
  ['Invocar al Dios araña']={t=10000,icon='Spell_Shadow_LifeDrain'},
  ['Invocar al Sr. Contono']={t=1000,icon='Ability_Seal'},
  ['Invocar al esqueleto de Atal\'ai']={t=1000,icon='Spell_Shadow_RaiseDead'},
  ['Invocar ascuas']={t=2000,icon='Spell_Fire_Fire'},
  ['Invocar bomba']={t=1000,icon='Ability_Seal'},
  ['Invocar bomba goblin']={t=250,icon='Ability_Repair'},
  ['Invocar coche azul']={t=1000,icon='Ability_Seal'},
  ['Invocar conejo con pintas']={t=1000,icon='Ability_Seal'},
  ['Invocar cría carmansí']={t=1000,icon='Ability_Seal'},
  ['Invocar cría de Onyxia']={t=2000,icon='Temp'},
  ['Invocar efecto']={t=5000,icon='Spell_Shadow_AnimateDead'},
  ['Invocar espectro ilusorio']={t=1000,icon='Spell_Shadow_Teleport'},
  ['Invocar estandarte de Karang']={t=500,icon='Temp'},
  ['Invocar felino naranja']={t=1000,icon='Ability_Seal'},
  ['Invocar ilusionas lupinas']={t=1000,icon='Spell_Shadow_Teleport'},
  ['Invocar lechuhalcón']={t=1000,icon='Ability_Seal'},
  ['Invocar llama viva']={t=2000,icon='Spell_Fire_Fire'},
  ['Invocar minipestes de pétalo de sangre']={t=2000,icon='Spell_Shadow_DarkSummoning'},
  ['Invocar pesadilla ilusoria']={t=2000,icon='Spell_Fire_SealOfFire'},
  ['Invocar quijaforte oliva']={t=1000,icon='Ability_Seal'},
  ['Invocar roca blanca Plymouth']={t=1000,icon='Ability_Seal'},
  ['Invocar sapo quasi-real']={t=1000,icon='Ability_Seal'},
  ['Invocar serpiente reina negra']={t=1000,icon='Ability_Seal'},
  ['Invocar tanque de batalla amarillo Qiraji']={t=3000,icon='INV_Misc_QirajiCrystal_01'},
  ['Invocar tanque de batalla azul Quiraji']={t=3000,icon='INV_Misc_QirajiCrystal_04'},
  ['Invocar tanque de batalla negro Quiraji']={t=3000,icon='INV_Misc_QirajiCrystal_05'},
  ['Invocar tanque de batalla rojo Qiraji']={t=3000,icon='INV_Misc_QirajiCrystal_02'},
  ['Invocar tanque de batalla ver de Qiraji']={t=3000,icon='INV_Misc_QirajiCrystal_03'},
  ['Invocar títeres de Helcular']={t=3000,icon='Spell_Shadow_Haunting'},
  ['Invocar vara mágica']={t=2000,icon='INV_Staff_26'},
  ['Ira aullante']={t=5000,icon='Ability_BullRush'},
  ['J\'eevee invoca un objeto']={t=2000,icon='Temp'},
  ['Jefe de Uldaman bronca']={t=5000,icon='Spell_Nature_EarthBindTotem'},
  ['Juego de parches mecánicos']={t=2000,icon='INV_Gizmo_03'},
  ['Kalaran conjura una antorcha']={t=1000,icon='Temp'},
  ['Kerlonian despierto']={t=4500,icon='Temp'},
  ['Kev']={t=3000,icon='Spell_Fire_FireBolt'},
  ['Kodo azulado']={t=3000,icon='Ability_Mount_Kodo_02'},
  ['Kodo de guerra negro']={t=3000,icon='Ability_Mount_Kodo_01'},
  ['Kodo de montar']={t=3000,icon='INV_Misc_Head_Tauren_02'},
  ['Kodo gris']={t=3000,icon='Ability_Mount_Kodo_01'},
  ['Kodo marrón']={t=3000,icon='Ability_Mount_Kodo_03'},
  ['Kodo verde']={t=3000,icon='Ability_Mount_Kodo_02'},
  ['Kombobulador kodo']={t=5000,icon='Trade_Fishing'},
  ['Kroshius inflamado']={t=3000,icon='Temp'},
  ['La curación de Tharnariun']={t=500,icon='Spell_Nature_MagicImmunity'},
  ['Lamento de alma en pena']={t=2000,icon='Spell_Shadow_Possession'},
  ['Lanza de Nimboya']={t=2000,icon='Temp'},
  ['Lanzamiento de antorcha']={t=3000,icon='Spell_Fire_Fireball02'},
  ['Lanzamiento de poción']={t=2000,icon='Spell_Misc_Drink'},
  ['Lanzamiento fallado de descarga de las Sombras']={t=2000,icon='Spell_Shadow_ShadowBolt'},
  ['Lanzar bomba fétida']={t=2000,icon='INV_Misc_Bowl_01'},
  ['Lanzar cerveza Hierro Negro']={t=500,icon='Temp'},
  ['Lanzar dinamita']={t=2000,icon='Spell_Fire_SelfDestruct'},
  ['Lanzar flecha de cupido']={t=1000,icon='Temp'},
  ['Lanzar hacha']={t=1000,icon='INV_Axe_08'},
  ['Lanzar objeto de pesadilla']={t=2000,icon='Spell_Fire_SelfDestruct'},
  ['Lanzar roca']={t=3000,icon='Ability_GolemStormBolt'},
  ['Lanzar roca II']={t=3000,icon='Ability_GolemStormBolt'},
  ['Lapso de tiempo']={t=2000,icon='Spell_Arcane_PortalOrgrimmar'},
  ['Latigazo de llamas']={t=1000,icon='Spell_Fire_Fireball'},
  ['Lecho mortal']={t=2000,icon='Spell_Shadow_Twilight'},
  ['Lengua curativa']={t=1000,icon='Spell_Holy_Heal'},
  ['Lengua curativa II']={t=1000,icon='Spell_Holy_Heal'},
  ['Lentes de pesca acuadinámicas']={t=5000,icon='INV_Misc_Spyglass_01'},
  ['Leopardo']={t=3000,icon='Ability_Mount_JungleTiger'},
  ['Leopardo primigenio']={t=3000,icon='Ability_Mount_JungleTiger'},
  ['Levantar a los muertos']={t=1000,icon='Spell_Shadow_RaiseDead'},
  ['Levantar escarabajo muerto']={t=1000,icon='Spell_Shadow_Contagion'},
  ['Levantar sello']={t=2000,icon='Temp'},
  ['Liberación de Yenniku']={t=4000,icon='Spell_Shadow_LifeDrain'},
  ['Liberar a J\'eevee']={t=2000,icon='Temp'},
  ['Liberar a los canes']={t=2000,icon='Temp'},
  ['Liberar al Imp']={t=2000,icon='Temp'},
  ['Liberar al gatito de Winna']={t=1000,icon='Ability_Seal'},
  ['Liberar al yeti de Umi']={t=2000,icon='Temp'},
  ['Liberar moco corrupto']={t=5000,icon='INV_Potion_19'},
  ['Liberar pie de Maury']={t=5000,icon='Temp'},
  ['Liberar zarpa de cólera']={t=10000,icon='Temp'},
  ['Limo bombardero']={t=1000,icon='Temp'},
  ['Llama de las Sombras']={t=2000,icon='Spell_Fire_Incinerate'},
  ['Llama justa prendida']={t=4000,icon='Spell_Holy_InnerFire'},
  ['Llamada de Thund']={t=1500,icon='Spell_Frost_Wisp'},
  ['Llamada de la tumba']={t=2000,icon='Spell_Shadow_ChillTouch'},
  ['Llamada del infierno']={t=10000,icon='Temp'},
  ['Llamada del vacío']={t=3000,icon='Spell_Shadow_DeathCoil'},
  ['Llamado a Ivus']={t=10000,icon='Temp'},
  ['Llamar Anatema']={t=1000,icon='Temp'},
  ['Llamar Bendición']={t=1000,icon='Temp'},
  ['Llamar a Glifos de la Guarda']={t=3000,icon='Temp'},
  ['Llamar a barrera prismática']={t=10000,icon='Temp'},
  ['Llamar a los ancestros']={t=7000,icon='Temp'},
  ['Llamar a lupo esclavizante']={t=1300,icon='Spell_Shadow_ChillTouch'},
  ['Llamar a lupo lóbrego']={t=1300,icon='Spell_Shadow_ChillTouch'},
  ['Llamar a un horror lupino']={t=1300,icon='Spell_Shadow_ChillTouch'},
  ['Llamarada abrasadora']={t=3000,icon='Spell_Fire_SelfDestruct'},
  ['Llamas de Shahram']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Llamas de sanción']={t=3000,icon='Temp'},
  ['Llamas del Caos']={t=1000,icon='Spell_Fire_WindsofWoe'},
  ['Llamas envolventes']={t=1500,icon='Spell_Shadow_LifeDrain02'},
  ['Llamas infernales']={t=3000,icon='Spell_Fire_SelfDestruct'},
  ['Llamas infernales II']={t=3000,icon='Spell_Fire_SelfDestruct'},
  ['Llamas infernales III']={t=3000,icon='Spell_Fire_SelfDestruct'},
  ['Llamas punzantes']={t=2000,icon='Spell_Fire_Immolation'},
  ['Llanto de alma en pena']={t=1500,icon='Spell_Shadow_ShadowBolt'},
  ['Llave de jaula de pantera']={t=5000,icon='Temp'},
  ['Llave esqueleto de plata']={t=5000,icon='Temp'},
  ['Llave esqueleto de veraplata']={t=5000,icon='Temp'},
  ['Llave esquelética arcanita']={t=5000,icon='Temp'},
  ['Llave esquelética dorada']={t=5000,icon='Temp'},
  ['Llenar ampolla']={t=5000,icon='Temp'},
  ['Lluvia']={t=3000,icon='Ability_TheBlackArrow'},
  ['Lluvia II']={t=3000,icon='Ability_TheBlackArrow'},
  ['Lluvia de Fuego']={t=3000,icon='Spell_Shadow_RainOfFire'},
  ['Lluvia de arrabio']={t=2000,icon='Temp'},
  ['Lluvia de bolas de Fuego']={t=3000,icon='Spell_Fire_FlameBolt'},
  ['Lluvia de descarga de Escarcha']={t=2000,icon='Spell_Frost_FrostBolt02'},
  ['Lluvia de descarga de las Sombras']={t=3000,icon='Spell_Shadow_ShadowBolt'},
  ['Lluvia de puntas']={t=500,icon='Ability_ImpalingBolt'},
  ['Lobo Invernal']={t=3000,icon='Ability_Mount_WhiteDireWolf'},
  ['Lobo de guerra negro']={t=3000,icon='Ability_Mount_BlackDireWolf'},
  ['Lobo fantasmal']={t=3000,icon='Spell_Nature_SpiritWolf'},
  ['Lobo funesto']={t=3000,icon='Ability_Mount_WhiteDireWolf'},
  ['Lobo gris']={t=3000,icon='Ability_Mount_WhiteDireWolf'},
  ['Lobo gris veloz']={t=3000,icon='Ability_Mount_WhiteDireWolf'},
  ['Lobo maderero veloz']={t=3000,icon='Ability_Mount_WhiteDireWolf'},
  ['Lobo marrón']={t=3000,icon='Ability_Mount_BlackDireWolf'},
  ['Lobo marrón veloz']={t=3000,icon='Ability_Mount_BlackDireWolf'},
  ['Lobo negro']={t=3000,icon='Ability_Mount_BlackDireWolf'},
  ['Lobo rojo']={t=3000,icon='Ability_Mount_BlackDireWolf'},
  ['Lobo ártico']={t=3000,icon='Ability_Mount_WhiteDireWolf'},
  ['Lodo fangoso']={t=1000,icon='Spell_Nature_StrangleVines'},
  ['Lodo lanzado']={t=1000,icon='Spell_Nature_Sleep'},
  ['Luz Sagrada']={t=2500,icon='Spell_Holy_HolyBolt'},
  ['Luz de altar Atal\'ai visual (DND)']={t=1000,icon='Temp'},
  ['Machaque colosal']={t=5000,icon='Temp'},
  ['Maldición de Hakkar']={t=2500,icon='Spell_Shadow_GatherShadows'},
  ['Maldición de Shahram']={t=1000,icon='Spell_Magic_LesserInvisibilty'},
  ['Maldición de Stalvan']={t=1000,icon='Spell_Shadow_ShadowPact'},
  ['Maldición de Timmy']={t=1000,icon='Spell_Shadow_ShadowPact'},
  ['Maldición de alma en pena']={t=2000,icon='Spell_Nature_Drowsy'},
  ['Maldición de debilidad']={t=1000,icon='Spell_Shadow_CurseOfMannoroth'},
  ['Maldición de espinas']={t=2000,icon='Spell_Shadow_AntiShadow'},
  ['Maldición de la rata de la Peste']={t=1500,icon='Spell_Shadow_UnholyFrenzy'},
  ['Maldición de las tribus']={t=2000,icon='Spell_Shadow_CurseOfMannoroth'},
  ['Maldición de los Muertobosque']={t=2000,icon='Spell_Shadow_GatherShadows'},
  ['Maldición de los Pirotigma']={t=2000,icon='Ability_Creature_Cursed_03'},
  ['Maldición de sanación']={t=1000,icon='Spell_Shadow_AntiShadow'},
  ['Maldición de sangre']={t=2000,icon='Spell_Shadow_RitualOfSacrifice'},
  ['Maldición del Magram caído']={t=2000,icon='Spell_Shadow_UnholyFrenzy'},
  ['Maldición del maestro oscuro']={t=2000,icon='Spell_Shadow_AntiShadow'},
  ['Maldición profana']={t=1000,icon='Spell_Shadow_CurseOfMannoroth'},
  ['Maldición vil']={t=4000,icon='Temp'},
  ['Maldición vudú']={t=1000,icon='Spell_Shadow_CurseOfMannoroth'},
  ['Maleficio']={t=2000,icon='Spell_Nature_Polymorph'},
  ['Maleficio de Jammal\'an']={t=2000,icon='Spell_Shadow_Charm'},
  ['Mano de Iruxos']={t=5000,icon='Temp'},
  ['Manos moradas']={t=4000,icon='Spell_Shadow_SiphonMana'},
  ['Maná de anulación']={t=2000,icon='Spell_Shadow_DarkRitual'},
  ['Marca de las llamas']={t=1000,icon='Spell_Fire_Fireball'},
  ['Marchitar']={t=1500,icon='Spell_Nature_NullifyDisease'},
  ['Martillo de cólera']={t=1000,icon='Ability_ThunderClap'},
  ['Mecazancudo amarillo veloz']={t=3000,icon='Ability_Mount_MechaStrider'},
  ['Mecazancudo azul']={t=3000,icon='Ability_Mount_MechaStrider'},
  ['Mecazancudo azul de hielo']={t=3000,icon='Ability_Mount_MechaStrider'},
  ['Mecazancudo blanco']={t=3000,icon='Ability_Mount_MechaStrider'},
  ['Mecazancudo blanco veloz']={t=3000,icon='Ability_Mount_MechaStrider'},
  ['Mecazancudo de acero']={t=3000,icon='Ability_Mount_MechaStrider'},
  ['Mecazancudo despintado']={t=3000,icon='Ability_Mount_MechaStrider'},
  ['Mecazancudo morado']={t=3000,icon='Ability_Mount_MechaStrider'},
  ['Mecazancudo rojo']={t=3000,icon='Ability_Mount_MechaStrider'},
  ['Mecazancudo rojo y azul']={t=3000,icon='Ability_Mount_MechaStrider'},
  ['Mecazancudo verde']={t=3000,icon='Ability_Mount_MechaStrider'},
  ['Mecazancudo verde fluorescente']={t=3000,icon='Ability_Mount_MechaStrider'},
  ['Mecazancudo verde veloz']={t=3000,icon='Ability_Mount_MechaStrider'},
  ['Megavoltio']={t=2000,icon='Spell_Nature_ChainLightning'},
  ['Mejorar arma roma']={t=3000,icon='Temp'},
  ['Mejorar arma roma II']={t=3000,icon='Temp'},
  ['Mejorar arma roma III']={t=3000,icon='Temp'},
  ['Mejorar arma roma IV']={t=3000,icon='Temp'},
  ['Mejorar arma roma V']={t=3000,icon='Temp'},
  ['Mejunje inestable']={t=3000,icon='Spell_Fire_Incinerate'},
  ['Mellar']={t=2500,icon='Ability_Warrior_Cleave'},
  ['Mente de la Peste']={t=4000,icon='Spell_Shadow_CallofBone'},
  ['Mente débil']={t=1000,icon='Spell_Shadow_MindSteal'},
  ['Mente débil II']={t=1000,icon='Spell_Shadow_MindSteal'},
  ['Mente débil III']={t=1000,icon='Spell_Shadow_MindSteal'},
  ['Metal de arrabio']={t=2000,icon='Spell_Fire_Fireball'},
  ['Miedo']={t=1500,icon='Spell_Shadow_Possession'},
  ['Miedo (NYI)']={t=3000,icon='Spell_Shadow_Possession'},
  ['Mil hojas']={t=250,icon='INV-Sword_53'},
  ['Mina terrestre Hierro Negro']={t=1000,icon='Spell_Shadow_Metamorphosis'},
  ['Mina terrestre goblin']={t=1000,icon='Spell_Shadow_Metamorphosis'},
  ['Minería']={t=3200,icon='Trade_Mining'},
  ['Minipistola']={t=100,icon='INV_Musket_04'},
  ['Mirada']={t=500,icon='Temp'},
  ['Mirada amenazante']={t=2000,icon='Spell_Shadow_Charm'},
  ['Mirada de cristal']={t=2000,icon='Ability_GolemThunderClap'},
  ['Misión hechizo de Sergra Espinoscura']={t=3000,icon='Temp'},
  ['Misión: crear teletransporte']={t=1000,icon='Temp'},
  ['Misión: invocación visual de héroe trol']={t=30000,icon='Temp'},
  ['Misión: invocar antárbol']={t=3000,icon='Spell_Nature_NatureTouchGrow'},
  ['Mocos fusionados']={t=500,icon='INV_Potion_12'},
  ['Montura cromática']={t=3000,icon='INV_Misc_Head_Dragon_Black'},
  ['Mordisco del alma']={t=2000,icon='Spell_Shadow_SiphonMana'},
  ['Mortero gigante']={t=3000,icon='Temp'},
  ['Mortero goblin']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Mortero picante']={t=500,icon='Spell_Fire_Fireball02'},
  ['Muerte de Taelean']={t=2000,icon='Temp'},
  ['Muerte de Windsor DND']={t=1500,icon='Temp'},
  ['Muerte y descomposición']={t=2000,icon='Spell_Shadow_DeathAndDecay'},
  ['Muérdago']={t=1000,icon='INV_Misc_Branch_01'},
  ['Muñeco de nieve']={t=1500,icon='INV_Ammo_Snowball'},
  ['Mástil de celebración']={t=10000,icon='Spell_Shadow_Twilight'},
  ['Nacimiento']={t=2000,icon='Temp'},
  ['Nostalgia']={t=4000,icon='Spell_Shadow_LifeDrain'},
  ['Nova de las Sombras II']={t=3000,icon='Spell_Shadow_ShadeTrueSight'},
  ['Nube de la Peste']={t=2000,icon='Spell_Shadow_CallofBone'},
  ['Nube de polvo']={t=1500,icon='Ability_Hibernation'},
  ['Nube de relámpagos']={t=3000,icon='Spell_Nature_CallStorm'},
  ['Nube de veneno']={t=1000,icon='Spell_Nature_Regenerate'},
  ['Nuevo misil mágico (Test)']={t=2000,icon='Temp'},
  ['Obsequio de Arugal']={t=2500,icon='Spell_Shadow_ChillTouch'},
  ['Obsequios de los Xavian']={t=5000,icon='Spell_Holy_FlashHeal'},
  ['Ojo de Immol\'thar']={t=2000,icon='Spell_Shadow_AntiMagicShell'},
  ['Ojo de Kilrogg']={t=5000,icon='Spell_Shadow_EvilEye'},
  ['Ojo de Ryson en el cielo']={t=1000,icon='Ability_Hunter_EagleEye'},
  ['Ojo de Ryson que todo lo ve']={t=1000,icon='Ability_Ambush'},
  ['Ojo de Yesmur (PT)']={t=2000,icon='Temp'},
  ['Ojo malvado']={t=1500,icon='Spell_Shadow_Charm'},
  ['Ojos de la bestia']={t=2000,icon='Ability_EyeOfTheOwl'},
  ['Ola de choque']={t=2000,icon='Ability_Whirlwind'},
  ['Ola de curación']={t=3000,icon='Spell_Nature_MagicImmunity'},
  ['Ola de curación de Antu\'sul']={t=1000,icon='Spell_Holy_Heal02'},
  ['Ola inferior de curación']={t=1500,icon='Spell_Nature_HealingWaveLesser'},
  ['Orden de sonar la nariz']={t=1500,icon='Spell_Shadow_LifeDrain'},
  ['Oscurecer visión']={t=2000,icon='Spell_Shadow_Fumble'},
  ['Otro de teletransporte sencillo']={t=1000,icon='Spell_Magic_LesserInvisibilty'},
  ['Oveja explosiva']={t=2000,icon='Ability_Repair'},
  ['Palabra de deshielo']={t=5000,icon='Temp'},
  ['Palomino veloz']={t=3000,icon='Ability_Mount_RidingHorse'},
  ['Panecillo a fuego lento']={t=1000,icon='INV_Misc_Food_11'},
  ['Pantera']={t=3000,icon='Ability_Mount_BlackPanther'},
  ['Pantera moteada']={t=3000,icon='Ability_Mount_BlackPanther'},
  ['Parar tiempo']={t=3000,icon='Temp'},
  ['Parar tiempo visual DND']={t=3000,icon='Temp'},
  ['Parras enredadoras']={t=1000,icon='Spell_Nature_Earthquake'},
  ['Parásito']={t=2000,icon='Ability_Poisons'},
  ['Pastel de bayas']={t=1000,icon='INV_Misc_Food_10'},
  ['Perdón']={t=1000,icon='Temp'},
  ['Perturbación']={t=3000,icon='Temp'},
  ['Pesadilla de Naralex']={t=2000,icon='Spell_Nature_Sleep'},
  ['Pesadilla venenosa']={t=2000,icon='Temp'},
  ['Peste de fiebre']={t=4500,icon='Spell_Nature_NullifyDisease'},
  ['Peste repugnante']={t=2000,icon='Spell_Shadow_CallofBone'},
  ['Peste vagante']={t=2000,icon='Spell_Shadow_CallofBone'},
  ['Petrificado: Canalizar lanzamiento visual']={t=3000,icon='Spell_Nature_Cyclone'},
  ['Pez ralentizante']={t=1000,icon='Spell_Nature_SlowPoison'},
  ['Pica llameante']={t=3000,icon='Spell_Fire_SelfDestruct'},
  ['Piroexplosión']={t=6000,icon='Spell_Fire_Fireball02'},
  ['Pisotón de guerra']={t=500,icon='Ability_WarStomp'},
  ['Plantar habas mágicas']={t=2000,icon='INV_Misc_Food_Wheat_02'},
  ['Plantar la cabeza de Gor\'tesh']={t=5000,icon='Temp'},
  ['Plantar semillas']={t=5000,icon='Temp'},
  ['Pluma de raptor']={t=5000,icon='Temp'},
  ['Poción de amor de Nagmara']={t=1000,icon='Temp'},
  ['Poder de Ragnaros']={t=500,icon='Spell_Fire_SelfDestruct'},
  ['Poder de Shahram']={t=1000,icon='Spell_Nature_WispSplode'},
  ['Polimorfia']={t=1500,icon='Spell_Nature_Polymorph'},
  ['Polimorfia: cerdo']={t=1500,icon='Spell_Magic_PolymorphPig'},
  ['Polimorfia: tortuga']={t=1500,icon='Ability_Hunter_Pet_Turtle'},
  ['Polimorfia: vaca']={t=1500,icon='Spell_Nature_Polymorph_Cow'},
  ['Polvo Magatha Incendia']={t=1300,icon='Temp'},
  ['Polvo de incenciaria']={t=5000,icon='Temp'},
  ['Portal Escudo del Estigma']={t=1500,icon='Spell_Arcane_TeleportOrgrimmar'},
  ['Portal a Villadorada']={t=5000,icon='Temp'},
  ['Portal de demonios']={t=500,icon='Spell_Arcane_TeleportOrgrimmar'},
  ['Portal de invocación de la princesa']={t=10000,icon='Spell_Arcane_PortalIronForge'},
  ['Portal de las Sombras']={t=1000,icon='Spell_Shadow_SealOfKings'},
  ['Portal dimensional']={t=2000,icon='Temp'},
  ['Portal: Cima del Trueno']={t=10000,icon='Spell_Arcane_PortalThunderBluff'},
  ['Portal: Darnassus']={t=10000,icon='Spell_Arcane_PortalDarnassus'},
  ['Portal: Entrañas']={t=10000,icon='Spell_Arcane_PortalUnderCity'},
  ['Portal: Forjaz']={t=10000,icon='Spell_Arcane_PortalIronForge'},
  ['Portal: Karazhan']={t=10000,icon='Spell_Arcane_PortalUnderCity'},
  ['Portal: Orgrimmar']={t=10000,icon='Spell_Arcane_PortalOrgrimmar'},
  ['Portal: Ventormenta']={t=10000,icon='Spell_Arcane_PortalStormWind'},
  ['Pozo de Luz']={t=1500,icon='Spell_Holy_SummonLightwell'},
  ['Preparar carga NG-5 (azul)']={t=5000,icon='INV_Misc_Bomb_05'},
  ['Preparar carga NG-5 (roja)']={t=5000,icon='INV_Misc_Bomb_05'},
  ['Presencia de muerte']={t=1000,icon='Spell_Shadow_ShadeTrueSight'},
  ['Primeros auxilios']={t=3000,icon='Spell_Holy_GreaterHeal'},
  ['Prontitud encantada']={t=3000,icon='Spell_Nature_Invisibilty'},
  ['Prueba de conocimiento']={t=2000,icon='Spell_Nature_EarthBind'},
  ['Psicometría']={t=5000,icon='Spell_Holy_Restoration'},
  ['Puerto de las Sombras']={t=250,icon='Spell_Shadow_AntiShadow'},
  ['Pulverizador de tinta']={t=1000,icon='Spell_Nature_Sleep'},
  ['Pulverizallamas']={t=1700,icon='Spell_Fire_Fire'},
  ['Punta punteaguda']={t=500,icon='Ability_ImpalingBolt'},
  ['Puntos de honor +138']={t=1000,icon='Temp'},
  ['Puntos de honor +228']={t=1000,icon='Temp'},
  ['Puntos de honor +2388']={t=1000,icon='INV_BannerPVP_02'},
  ['Puntos de honor +378']={t=1000,icon='Temp'},
  ['Puntos de honor +398']={t=1000,icon='Temp'},
  ['Puntos de honor +50']={t=1000,icon='Temp'},
  ['Puntos de honor +82']={t=1000,icon='Temp'},
  ['Purga serpenteante']={t=30000,icon='Spell_Shadow_LifeDrain'},
  ['Purgación de manifestación']={t=4000,icon='Temp'},
  ['Purgar pozo Bravacrín']={t=10000,icon='Temp'},
  ['Purgar pozo Pezuña Invernal']={t=10000,icon='Temp'},
  ['Purgar pozo Tronacuerno']={t=10000,icon='Temp'},
  ['Purificar y dejar comida']={t=5000,icon='INV_Misc_Bowl_01'},
  ['Putrefacción mental']={t=2000,icon='Spell_Shadow_MindRot'},
  ['Puñetazo de fuerza']={t=1000,icon='INV_Gauntlets_31'},
  ['Puño de Shahram']={t=1000,icon='Ability_Whirlwind'},
  ['Púa de demonio']={t=5000,icon='Temp'},
  ['Quebrador de almas']={t=2000,icon='Spell_Shadow_Haunting'},
  ['Quemadura de Escarcha']={t=2000,icon='Spell_Frost_ChillingBlast'},
  ['Quemadura de maná']={t=3000,icon='Spell_Shadow_ManaBurn'},
  ['Quemadura en cadena']={t=3000,icon='Spell_Shadow_ManaBurn'},
  ['Quintaesencia acuática - Buscar runa del Núcleo de Magma']={t=1000,icon='Temp'},
  ['Quitar insignia']={t=1000,icon='Temp'},
  ['Racha de viento']={t=2000,icon='Spell_Nature_EarthBind'},
  ['Ragnaros se yergue']={t=2900,icon='Spell_Fire_LavaSpawn'},
  ['Raptor Razzashi veloz']={t=3000,icon='Ability_Mount_Raptor'},
  ['Raptor azul veloz']={t=3000,icon='Ability_Mount_Raptor'},
  ['Raptor de guerra negro']={t=3000,icon='Ability_Mount_Raptor'},
  ['Raptor de marfil']={t=3000,icon='Ability_Mount_Raptor'},
  ['Raptor esmeralda']={t=3000,icon='Ability_Mount_Raptor'},
  ['Raptor naranja veloz']={t=3000,icon='Ability_Mount_Raptor'},
  ['Raptor obsidiano']={t=3000,icon='Ability_Mount_Raptor'},
  ['Raptor oliva veloz']={t=3000,icon='Ability_Mount_Raptor'},
  ['Raptor rojo jaspeado']={t=3000,icon='Ability_Mount_Raptor'},
  ['Raptor tortuga']={t=3000,icon='Ability_Mount_Raptor'},
  ['Raptor violento']={t=3000,icon='Ability_Mount_Raptor'},
  ['Rastreador del Sindicato (MURP) DND']={t=1000,icon='Spell_Arcane_Blink'},
  ['Reabastecimiento']={t=2000,icon='Spell_Misc_Drink'},
  ['Recitar las palabras de Celebras']={t=3000,icon='Temp'},
  ['Recolectando radiación']={t=4000,icon='Temp'},
  ['Recolectar enjambre']={t=3000,icon='Spell_Holy_Dizzy'},
  ['Recolectar hierbas']={t=5000,icon='Spell_Nature_NatureTouchGrow'},
  ['Recolectar huevo grajero']={t=500,icon='Temp'},
  ['Recolectar huevo silítido']={t=5000,icon='Temp'},
  ['Reconstrucción']={t=3000,icon='Temp'},
  ['Recrecimiento']={t=2000,icon='Spell_Nature_ResistNature'},
  ['Recuperación oscura']={t=2000,icon='Ability_Hunter_MendPet'},
  ['Red de mala suerte']={t=500,icon='Ability_Ensnare'},
  ['Red electrificada']={t=500,icon='Ability_Ensnare'},
  ['Redención']={t=10000,icon='Spell_Holy_Resurrection'},
  ['Redes atrapantes']={t=2000,icon='Spell_Nature_EarthBind'},
  ['Regeneración salvaje']={t=3000,icon='Spell_Nature_Rejuvenation'},
  ['Rellamar']={t=10000,icon='Temp'},
  ['Rellenando']={t=3000,icon='Temp'},
  ['Relámpago bifurcado']={t=2000,icon='Spell_Nature_ChainLightning'},
  ['Relámpago impetuoso']={t=3000,icon='Spell_Nature_Lightning'},
  ['Renacer']={t=2000,icon='Spell_Nature_Reincarnation'},
  ['Renovar']={t=2000,icon='Spell_Holy_Renew'},
  ['Reparación de collar de Talvash']={t=4500,icon='Spell_Holy_Restoration'},
  ['Repartiendo mamporros']={t=1000,icon='INV_Ammo_Arrow_02'},
  ['Reponer espíritu']={t=3000,icon='Spell_Nature_MoonGlow'},
  ['Reponer espíritu II']={t=3000,icon='Spell_Nature_MoonGlow'},
  ['Reptanoches']={t=5000,icon='Trade_Fishing'},
  ['Reputación -  Vista Eterna +500']={t=1000,icon='Temp'},
  ['Reputación - Bahía del Botín +500']={t=1000,icon='Temp'},
  ['Reputación - Gadgetzan +500']={t=1000,icon='Temp'},
  ['Reputación - Jefe del templo de Ahn\'Qiraj']={t=1000,icon='Temp'},
  ['Reputación - Trinquete +500']={t=1000,icon='Temp'},
  ['Resistencia a la Escarcha']={t=1000,icon='Spell_Frost_WizardMark'},
  ['Resistencia a las Sombras']={t=1000,icon='Spell_Frost_WizardMark'},
  ['Respiración']={t=5000,icon='Spell_Fire_Fire'},
  ['Respiración de Sargeras']={t=2000,icon='Spell_Shadow_Metamorphosis'},
  ['Resurrección']={t=10000,icon='Spell_Holy_Resurrection'},
  ['Resurrección Escarlata']={t=2000,icon='Spell_Holy_Resurrection'},
  ['Resurrección con piedra de alma']={t=3000,icon='Spell_Shadow_SoulGem'},
  ['Resurrección de Yelestrón']={t=3000,icon='Spell_Totem_WardOfDraining'},
  ['Retirar mascota']={t=5000,icon='Spell_Nature_SpiritWolf'},
  ['Revivir a Ringo']={t=2500,icon='Temp'},
  ['Revivir mascota']={t=10000,icon='Ability_Hunter_BeastSoothe'},
  ['Revivir rata de excavación']={t=3000,icon='Spell_Holy_Resurrection'},
  ['Rey del Gordok']={t=1000,icon='INV_Crown_02'},
  ['Rezo a Elune']={t=1000,icon='Spell_Holy_Resurrection'},
  ['Rezo de curación']={t=3000,icon='Spell_Holy_PrayerOfHealing02'},
  ['Rimblat cultiva una flor DND']={t=2000,icon='Temp'},
  ['Ritual de condena']={t=10000,icon='Spell_Shadow_AntiMagicShell'},
  ['Ritual de invocación']={t=5000,icon='Spell_Shadow_Twilight'},
  ['Robar (PT)']={t=5000,icon='Temp'},
  ['Robar espíritu']={t=2000,icon='Spell_Shadow_Possession'},
  ['Robar vida']={t=1500,icon='Spell_Shadow_LifeDrain02'},
  ['Roca']={t=2000,icon='Ability_Throw'},
  ['Rociar con agua purificadora']={t=6000,icon='Temp'},
  ['Rocío ácido']={t=2000,icon='Spell_Nature_Acid_01'},
  ['Romper cosa']={t=2000,icon='Spell_Shadow_CurseOfAchimonde'},
  ['Romper cosa grande']={t=2000,icon='Spell_Shadow_CurseOfAchimonde'},
  ['Ron Rumsey']={t=1000,icon='INV_Drink_03'},
  ['Ron Rumsey blanco']={t=1000,icon='INV_Drink_08'},
  ['Ron Rumsey etiqueta negra']={t=1000,icon='INV_Drink_04'},
  ['Ron Rumsey tostado']={t=1000,icon='INV_Drink_04'},
  ['Rotar activador']={t=3000,icon='Temp'},
  ['Runa de apertura']={t=5000,icon='Temp'},
  ['Rutagrana corrupto']={t=2000,icon='Temp'},
  ['Ráfaga abrasadora']={t=1500,icon='Spell_Fire_FireBolt'},
  ['Rágada de llamas']={t=3000,icon='Spell_Fire_SelfDestruct'},
  ['Sabiduría Hacha Invernal']={t=1000,icon='Ability_Ambush'},
  ['Sable de Hielo a rayas']={t=3000,icon='Ability_Mount_WhiteTiger'},
  ['Sable de Hielo de la Cuna del Invierno']={t=3000,icon='Ability_Mount_PinkTiger'},
  ['Sable de Hielo moteado']={t=3000,icon='Ability_Mount_WhiteTiger'},
  ['Sable de Hielo veloz']={t=3000,icon='Ability_Mount_WhiteTiger'},
  ['Sable de hielo']={t=3000,icon='Ability_Mount_WhiteTiger'},
  ['Sable de la Nche a rayas']={t=3000,icon='Ability_Mount_BlackPanther'},
  ['Sable de la Niebla veloz']={t=3000,icon='Ability_Mount_BlackPanther'},
  ['Sable de la Tempestad veloz']={t=3000,icon='Ability_Mount_BlackPanther'},
  ['Sable de la noche']={t=3000,icon='Ability_Mount_BlackPanther'},
  ['Sable del Alba veloz']={t=3000,icon='Ability_Mount_JungleTiger'},
  ['Sacar glifo ancestral']={t=10000,icon='Temp'},
  ['Sacrificio']={t=1000,icon='Spell_Holy_DivineIntervention'},
  ['Sacudida virósica']={t=1500,icon='Spell_Nature_EarthBind'},
  ['Sacudón de llamas']={t=2200,icon='Spell_Fire_Fireball'},
  ['Safiro DND']={t=20000,icon='Temp'},
  ['Salchicha del solsticio de verano']={t=1000,icon='INV_Misc_Food_53'},
  ['Sales aromáticas potentes']={t=2000,icon='INV_Misc_Ammo_Gunpowder_01'},
  ['Saliva tóxica']={t=500,icon='Spell_Nature_CorrosiveBreath'},
  ['Salpicadura ácida']={t=1000,icon='INV_Drink_06'},
  ['Salud máxima']={t=1000,icon='Temp'},
  ['Sanación oscura']={t=3500,icon='Spell_Shadow_ChillTouch'},
  ['Sauce envolvente']={t=1000,icon='Spell_Nature_CorrosiveBreath'},
  ['Seducción']={t=1500,icon='Spell_Shadow_MindSteal'},
  ['Semental blanco']={t=3000,icon='Ability_Mount_RidingHorse'},
  ['Semental negro']={t=3000,icon='Ability_Mount_NightmareHorse'},
  ['Semental palomino']={t=3000,icon='Ability_Mount_RidingHorse'},
  ['Semilla de Gaia encantada']={t=5000,icon='Temp'},
  ['Sentidos agudizados']={t=1000,icon='Temp'},
  ['Silencio']={t=1500,icon='Spell_Holy_Silence'},
  ['Smorc tostado']={t=1000,icon='INV_SummerFest_Smorc'},
  ['Socavar']={t=2000,icon='Spell_Shadow_CurseOfMannoroth'},
  ['Sofocar']={t=5000,icon='Temp'},
  ['Sol H']={t=3000,icon='Spell_Frost_ManaRecharge'},
  ['Sol L']={t=3000,icon='Spell_Frost_ManaRecharge'},
  ['Sol M']={t=3000,icon='Spell_Frost_ManaRecharge'},
  ['Sol U']={t=3000,icon='Spell_Frost_ManaRecharge'},
  ['Solidificación gélida']={t=2500,icon='Spell_Frost_Glacier'},
  ['Solta niebla tóxica']={t=3000,icon='INV_Cask_01'},
  ['Sombra penetrante']={t=2000,icon='Spell_Shadow_ChillTouch'},
  ['Somnolencia cristalina']={t=2000,icon='Spell_Nature_Sleep'},
  ['Somnolencia del druida']={t=2500,icon='Spell_Nature_Sleep'},
  ['Somnolencia profunda']={t=1000,icon='Spell_Shadow_Cripple'},
  ['Sorpresa dulce']={t=1000,icon='INV_ValentinesChocolate03'},
  ['Subjefe de Uldaman bronca']={t=5000,icon='Spell_Nature_EarthBindTotem'},
  ['Supercristal']={t=6000,icon='Temp'},
  ['Susurros oscuros']={t=3000,icon='Spell_Shadow_Haunting'},
  ['Símbolo de la vida']={t=10000,icon='Spell_Holy_Resurrection'},
  ['Teletransporte']={t=1000,icon='Spell_Magic_LesserInvisibilty'},
  ['Teletransporte Abadía de Villanorte']={t=2000,icon='Temp'},
  ['Teletransporte Altar de las Olas']={t=2000,icon='Temp'},
  ['Teletransporte Bosque del Ocaso']={t=2000,icon='Temp'},
  ['Teletransporte Elwynn']={t=2000,icon='Temp'},
  ['Teletransporte Villa Oscura']={t=2000,icon='Temp'},
  ['Teletransporte Villadorada']={t=2000,icon='Temp'},
  ['Teletransporte Yunquemar']={t=2000,icon='Temp'},
  ['Teletransporte a Darnassus']={t=10000,icon='Spell_Arcane_TeleportDarnassus'},
  ['Teletransporte a Darnassus: Evento']={t=1000,icon='Temp'},
  ['Teletransporte a antárbol']={t=2000,icon='Temp'},
  ['Teletransporte a la Torre de Azshara']={t=1000,icon='Spell_Nature_AstralRecalGroup'},
  ['Teletransporte a los Páramos de Poniente']={t=2000,icon='Temp'},
  ['Teletransporte a: Cima del Trueno']={t=10000,icon='Spell_Arcane_TeleportThunderBluff'},
  ['Teletransporte a: Claro de la Luna']={t=10000,icon='Spell_Arcane_TeleportMoonglade'},
  ['Teletransporte a: Entrañas']={t=10000,icon='Spell_Arcane_TeleportUnderCity'},
  ['Teletransporte a: Forjaz']={t=10000,icon='Spell_Arcane_TeleportIronForge'},
  ['Teletransporte a: Orgrimmar']={t=10000,icon='Spell_Arcane_TeleportOrgrimmar'},
  ['Teletransporte a: Ventormenta']={t=10000,icon='Spell_Arcane_TeleportStormWind'},
  ['Teletransporte cementerio']={t=2000,icon='Temp'},
  ['Teletransporte cuarteles']={t=2000,icon='Temp'},
  ['Teletransporte de Ashcrombe']={t=2000,icon='Spell_Fire_SelfDestruct'},
  ['Teletransporte desde la torre de Azshara']={t=1000,icon='Spell_Nature_EarthBind'},
  ['Teletransporte faro']={t=2000,icon='Temp'},
  ['Teletransporte monasterio']={t=2000,icon='Temp'},
  ['Teletransporte sencillo']={t=1000,icon='Spell_Magic_LesserInvisibilty'},
  ['Teletransporte visual de mayordomo']={t=1000,icon='Spell_Arcane_Blink'},
  ['Teletransportel Arroyo de la Luna']={t=2000,icon='Temp'},
  ['Temblor mental']={t=2000,icon='Spell_Nature_Earthquake'},
  ['Test de hoja afilada']={t=3000,icon='Temp'},
  ['Tibia curva']={t=1500,icon='Temp'},
  ['Tiempo agotado']={t=7000,icon='INV_Gizmo_02'},
  ['Tierra lanzada']={t=1000,icon='Spell_Nature_Sleep'},
  ['Tigre']={t=3000,icon='Ability_Mount_JungleTiger'},
  ['Tigre Zulian veloz']={t=3000,icon='Ability_Mount_JungleTiger'},
  ['Tigre de guerra negro']={t=3000,icon='Ability_Mount_BlackPanther'},
  ['Tiro largo II']={t=4000,icon='Ability_Marksmanship'},
  ['Tiro largo III']={t=4000,icon='Ability_Marksmanship'},
  ['Toque curativo']={t=3500,icon='Spell_Nature_HealingTouch'},
  ['Toque de corvozarpa']={t=1500,icon='Spell_Shadow_Requiem'},
  ['Toque de la muerte']={t=3000,icon='Spell_Shadow_UnsummonBuilding'},
  ['Toque gélido de Trelane']={t=3000,icon='Spell_Shadow_UnsummonBuilding'},
  ['Toque marchito']={t=2000,icon='Spell_Nature_Drowsy'},
  ['Tormenta de Fuego']={t=2000,icon='Spell_Fire_SelfDestruct'},
  ['Tormenta de maná']={t=2000,icon='Spell_Frost_IceStorm'},
  ['Torpeza']={t=1000,icon='Spell_Shadow_Fumble'},
  ['Torpeza II']={t=1000,icon='Spell_Shadow_Fumble'},
  ['Torpeza III']={t=1000,icon='Spell_Shadow_Fumble'},
  ['Tortuga de montar']={t=3000,icon='Ability_Hunter_Pet_Turtle'},
  ['Toxina fangosa']={t=2000,icon='Spell_Nature_Regenerate'},
  ['Toxina instantánea']={t=3000,icon='INV_Potion_19'},
  ['Toxina letal']={t=3000,icon='Spell_Nature_CorrosiveBreath'},
  ['Traducción de Jarkal']={t=4500,icon='Spell_Holy_Restoration'},
  ['Trance zahorí']={t=5000,icon='Temp'},
  ['Transformación de Warosh']={t=1000,icon='Temp'},
  ['Transformación de dragón azul DND']={t=1000,icon='Temp'},
  ['Transformación de dragón rojo DND']={t=1000,icon='Temp'},
  ['Transformación de sala de observación de estudiantes - Efecto']={t=1000,icon='Temp'},
  ['Transformación en dragón verde DND']={t=1000,icon='Temp'},
  ['Transformación en víctima']={t=2000,icon='Spell_Magic_LesserInvisibilty'},
  ['Transportador Vista Eterna']={t=10000,icon='Spell_Fire_SelfDestruct'},
  ['Transportdor gnomo']={t=10000,icon='Temp'},
  ['Tributo a Grom']={t=2000,icon='Temp'},
  ['Tripulación borracha del foso']={t=2000,icon='Temp'},
  ['Tumba de hielo']={t=1500,icon='Spell_Frost_Glacier'},
  ['Tótem de relámpagos']={t=500,icon='Spell_Nature_Lightning'},
  ['Tótem pillaterra']={t=500,icon='Spell_Nature_NatureTouchDecay'},
  ['Untar bálsamo']={t=1300,icon='Temp'},
  ['Untar glándula de seducción']={t=2500,icon='INV_Misc_Bowl_01'},
  ['Urok invocado']={t=1000,icon='Temp'},
  ['Usar burbuja']={t=3000,icon='Temp'},
  ['Vaciar jarra festiva']={t=2000,icon='Temp'},
  ['Vela de Elune']={t=500,icon='Temp'},
  ['Velo de Sombras']={t=1500,icon='Spell_Shadow_GatherShadows'},
  ['Veneno corrosivo']={t=1500,icon='Spell_Nature_CorrosiveBreath'},
  ['Veneno de acción lenta']={t=1000,icon='Spell_Nature_SlowPoison'},
  ['Veneno de acción lenta II']={t=1000,icon='Spell_Nature_SlowPoison'},
  ['Veneno de aturdimiento mental']={t=3000,icon='Spell_Nature_NullifyDisease'},
  ['Veneno de aturdimiento mental II']={t=3000,icon='Spell_Nature_NullifyDisease'},
  ['Veneno de aturdimiento mental III']={t=3000,icon='Spell_Nature_NullifyDisease'},
  ['Veneno de trepador']={t=2000,icon='Spell_Nature_NullifyPoison'},
  ['Veneno instantáneo']={t=3000,icon='Ability_Poisons'},
  ['Veneno instantáneo II']={t=3000,icon='Ability_Poisons'},
  ['Veneno instantáneo III']={t=3000,icon='Ability_Poisons'},
  ['Veneno instantáneo IV']={t=3000,icon='Ability_Poisons'},
  ['Veneno instantáneo V']={t=3000,icon='Ability_Poisons'},
  ['Veneno instantáneo VI']={t=3000,icon='Ability_Poisons'},
  ['Veneno mortal']={t=3000,icon='Ability_Rogue_DualWeild'},
  ['Veneno mortal II']={t=3000,icon='Ability_Rogue_DualWeild'},
  ['Veneno mortal III']={t=3000,icon='Ability_Rogue_DualWeild'},
  ['Veneno mortal IV']={t=3000,icon='Ability_Rogue_DualWeild'},
  ['Veneno mortal V']={t=3000,icon='Ability_Rogue_DualWeild'},
  ['Veneno paralizante']={t=3000,icon='Ability_PoisonSting'},
  ['Venganza de Arygos']={t=2000,icon='Temp'},
  ['Ventisca']={t=2000,icon='Spell_Frost_IceStorm'},
  ['Viaje astral']={t=10000,icon='Spell_Nature_AstralRecal'},
  ['Vientos ardientes']={t=1000,icon='Spell_Nature_Cyclone'},
  ['Vientos envolventes']={t=2000,icon='Spell_Nature_Cyclone'},
  ['Viruela silítida']={t=2000,icon='Spell_Nature_NullifyDisease'},
  ['Visión a distancia']={t=1000,icon='Ability_TownWatch'},
  ['Visión lejana']={t=2000,icon='Spell_Nature_FarSight'},
  ['Visión lejana (PT)']={t=2000,icon='Temp'},
  ['Vista de mago']={t=3000,icon='Temp'},
  ['Visualización de curar (DND)']={t=3500,icon='Spell_Holy_Heal'},
  ['Visualización de teletransporte de Ivus (DND)']={t=1000,icon='Temp'},
  ['Visualizar a Ouro sumergido']={t=1500,icon='Spell_Fire_Volcano'},
  ['Volar muñeco']={t=2000,icon='Temp'},
  ['Volea']={t=1000,icon='Spell_Shadow_LifeDrain'},
  ['Voluntad de Shahram']={t=1000,icon='Spell_Holy_MindVision'},
  ['Vudú']={t=1000,icon='Spell_Shadow_AntiShadow'},
  ['Vínculos compartidos']={t=1500,icon='Spell_Shadow_UnsummonBuilding'},
  ['Windsor lee las tablas DND']={t=10000,icon='Temp'},
  ['Yegua zaina']={t=3000,icon='Ability_Mount_RidingHorse'},
  ['Zancudo de batalla negro']={t=3000,icon='Ability_Mount_MechaStrider'},
  ['[PH] Activador contrafuerte']={t=5000,icon='Temp'},
  ['[PH] Bazuca de cristal']={t=1000,icon='Temp'},
  ['[PH] Lanzar gasolina a hoguera']={t=500,icon='Temp'},
  ['[PH] Teletransporte a Auberdine']={t=2000,icon='Temp'},
  ['[PH] Teletransporte a Bahía del Botín']={t=2000,icon='Temp'},
  ['[PH] Teletransporte a Balthule']={t=2000,icon='Temp'},
  ['[PH] Teletransporte a Entrañas']={t=2000,icon='Temp'},
  ['[PH] Teletransporte a Frondavil']={t=2000,icon='Temp'},
  ['[PH] Teletransporte a Grom\'Gol']={t=2000,icon='Temp'},
  ['[PH] Teletransporte a Orgrimmar']={t=2000,icon='Temp'},
  ['[PH] Teletransporte a Puerto de Menethil']={t=2000,icon='Temp'},
  ['[PH] Teletransporte a Theramore']={t=2000,icon='Temp'},
  ['[PH] Teletransporte a Trinquete']={t=2000,icon='Temp'},
  ['piel de piedra']={t=6000,icon='Spell_Nature_EnchantArmor'},
  ['¡Cura de la lepra!']={t=2000,icon='Spell_Holy_FlashHeal'},
  ['¡Narain!']={t=3000,icon='INV_Misc_Head_Gnome_01'},
  ['Ácido corrosivo']={t=1500,icon='Spell_Nature_Acid_01'},
  ['Ácido de Hakkar']={t=1000,icon='Spell_Nature_Acid_01'},
  ['Árbol Tammra']={t=1300,icon='Temp'},
  ['Éxtasis melódico']={t=1000,icon='Temp'},
}

UF.castInterrupts = {
  ["Azote de escudo"] = true,
  ["Zurrar"] = true,
  ["Patada"] = true,
  ["Choque de tierra"] = true,
  ["Pisotón de guerra"] = true,
  ["Arremetida de conmoción"] = true,
  ["Embestida aturdidora"] = true,
  ["Aturdimiento de intercepción"] = true,
  ["Martillo de justicia"] = true,
  ["Golpe bajo"] = true,
  ["Incapacitación"] = true,
  ["Golpe en los riñones"] = true,
  ["Silencio"] = true,
  ["Contrahechizo"] = true,
  ["Contrahechizo: silenciado"] = true,
  ["Azote"] = true,
  ["Miedo"] = true,
  ["Aullido de terror"] = true,
  ["Alarido psíquico"] = true,
  ["Grito intimidador"] = true,
  ["Aturdimiento de fuego estelar"] = true,
  ["Aturdimiento de revancha"] = true,
  ["Disparo de conmoción mejorado"] = true,
  ["Impacto"] = true,
  ["Piroclasma"] = true,
  ["Desmayo"] = true,
  ["Aturdir"] = true,
  ["Efecto aturdidor de mazas"] = true,
  ["Sacudida de tierra"] = true,
  ["Arrepentimiento"] = true,
  ["Disparo disperso"] = true,
  ["Ceguera"] = true,
  ["Hibernar"] = true,
  ["Aguijón de dracoleón"] = true,
  ["Bomba dura de cobre"] = true,
  ["Bomba grande de cobre"] = true,
  ["Bomba pequeña de bronce"] = true,
  ["Bomba grande de bronce"] = true,
  ["Bomba grande de hierro"] = true,
  ["Bomba de fragmentación de mitril"] = true,
  ["Bomba altamente explosiva"] = true,
  ["Bomba Hierro Negro"] = true,
  ["Granada de hierro"] = true,
  ["Granada de fragmentación M73"] = true,
  ["Grabada de torio"] = true,
  ["Mortero goblin"] = true,
}
