-- Spell data for CastTracker.lua, keyed by the spell name exactly as the
-- ruRU combat log prints it:
--   castSpells:     cast time (t, milliseconds) and icon name of spells
--                   cast by other units;
--   castInterrupts: spells that break a cast when they hit or land on
--                   the caster (kicks, stuns, fears, bombs).
-- Extracted verbatim from pfUI's spell database (env/locales_ruRU.lua,
-- tables "spells" and "interrupts"; MIT License, Copyright (c)
-- 2016-2021 Eric Mauser (Shagu)).

local E = unpack(ElvUI)
local UF = E.UnitFrames

-- Overwrites whatever enUS.lua may have set, whichever file ran first.
if GetLocale() ~= "ruRU" then return end

UF.castSpells = {
  [' Пробуждение каменного дворфа - визуальный эффект']={t=1500,icon='Spell_Nature_Earthquake'},
  ['"Отчаянный" снова принимает облик цыпленка"']={t=1000,icon='Ability_Racial_BearForm'},
  ['[PH] Активатор Опоры']={t=5000,icon='Temp'},
  ['[PH] Телепорт в Аубердин']={t=2000,icon='Temp'},
  ['[PH] Телепорт в Гавань Менетил']={t=2000,icon='Temp'},
  ['[PH] Телепорт в Гром\'гол']={t=2000,icon='Temp'},
  ['[PH] Телепорт в Кабестан']={t=2000,icon='Temp'},
  ['[PH] Телепорт в Оргриммар']={t=2000,icon='Temp'},
  ['[PH] Телепорт в Оскверненный лес.']={t=2000,icon='Temp'},
  ['[PH] Телепорт в Пиратскую бухту']={t=2000,icon='Temp'},
  ['[PH] Телепорт в Подгород']={t=2000,icon='Temp'},
  ['[PH] Телепорт в Терамор']={t=2000,icon='Temp'},
  ['[PH] Телепорт к Балтулу']={t=2000,icon='Temp'},
  ['[PH] Хрустальная базука']={t=1000,icon='Temp'},
  ['Автоматический заплатный набор']={t=2000,icon='INV_Gizmo_03'},
  ['Агрессия ключевого противника Ульдамана']={t=5000,icon='Spell_Nature_EarthBindTotem'},
  ['Агрессия малого ключевого противника Ульдамана']={t=5000,icon='Spell_Nature_EarthBindTotem'},
  ['Адское Пламя']={t=3000,icon='Spell_Fire_SelfDestruct'},
  ['Адское Пламя II']={t=3000,icon='Spell_Fire_SelfDestruct'},
  ['Адское Пламя III']={t=3000,icon='Spell_Fire_SelfDestruct'},
  ['Аквадинамическая блесна']={t=5000,icon='INV_Misc_Spyglass_01'},
  ['Аквадинамический магнит для рыбы']={t=5000,icon='INV_Misc_Orb_03'},
  ['Активация защиты']={t=5000,icon='Temp'},
  ['Акуленок']={t=1000,icon='Ability_Seal'},
  ['Алая змея']={t=1000,icon='Ability_Seal'},
  ['Анконская курица']={t=1000,icon='Ability_Seal'},
  ['Антимагический щит']={t=2000,icon='Spell_Shadow_AntiMagicShell'},
  ['Арканитовая отмычка']={t=5000,icon='Temp'},
  ['Аспект Нептулона']={t=1000,icon='Temp'},
  ['Астральное возвращение']={t=10000,icon='Spell_Nature_AstralRecal'},
  ['Атака Нефариуса 001']={t=1000,icon='Temp'},
  ['Атака оглушающей бомбой.']={t=2000,icon='Spell_Fire_SelfDestruct'},
  ['Багровая змея']={t=1000,icon='Ability_Seal'},
  ['Барьер Света']={t=2000,icon='Temp'},
  ['Бегство отряда Блая']={t=10000,icon='INV_Misc_Rune_01'},
  ['Безмолвие']={t=1500,icon='Spell_Holy_Silence'},
  ['Белый баран']={t=3000,icon='Ability_Mount_MountainRam'},
  ['Белый жеребец']={t=3000,icon='Ability_Mount_RidingHorse'},
  ['Белый котенок']={t=1000,icon='Ability_Seal'},
  ['Белый механодолгоног модель Б']={t=3000,icon='Ability_Mount_MechaStrider'},
  ['Белый ром Ромси']={t=1000,icon='INV_Drink_08'},
  ['Белый тигренок']={t=1000,icon='Ability_Seal'},
  ['Бирюзовый кодо']={t=3000,icon='Ability_Mount_Kodo_02'},
  ['Бирюзовый ящер']={t=3000,icon='Ability_Mount_Raptor'},
  ['Благословение Шахрама']={t=1000,icon='Spell_Holy_LayOnHands'},
  ['Благословение Юлии']={t=2000,icon='Spell_Holy_Renew'},
  ['Благословленное волшебное масло']={t=3000,icon='Temp'},
  ['Блесна']={t=5000,icon='INV_Misc_Orb_03'},
  ['Блуждающие духи']={t=2000,icon='Spell_Shadow_BlackPlague'},
  ['Боевой скакун Грозовой Вершины']={t=3000,icon='Ability_Mount_MountainRam'},
  ['Божественная кара']={t=2500,icon='Spell_Holy_HolySmite'},
  ['Божественный транс']={t=5000,icon='Temp'},
  ['Болезненная усталость']={t=3000,icon='Spell_Nature_NullifyDisease'},
  ['Болезнетворный плевок']={t=3000,icon='Spell_Shadow_CreepingPlague'},
  ['Болезнетворный удар']={t=1500,icon='Spell_Nature_EarthBind'},
  ['Болотный яд']={t=2000,icon='Spell_Nature_Regenerate'},
  ['Большая бронзовая бомба']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Большая железная бомба']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Большая медная бомба']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Большая невидимость']={t=3000,icon='Spell_Nature_Invisibilty'},
  ['Большая рогатая сова']={t=1000,icon='Ability_Seal'},
  ['Большее рассеивание']={t=4000,icon='Spell_Arcane_StarFire'},
  ['Большой лесной волк']={t=3000,icon='Ability_Mount_BlackDireWolf'},
  ['Большой сефориевый заряд']={t=5000,icon='Temp'},
  ['Бомба']={t=2000,icon='Spell_Fire_SelfDestruct'},
  ['Бомба Синдиката']={t=3000,icon='Spell_Shadow_MindBomb'},
  ['Бомба из черного железа']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Бомбейская кошка']={t=1000,icon='Ability_Seal'},
  ['Бродячая чума']={t=2000,icon='Spell_Shadow_CallofBone'},
  ['Броня стихий']={t=1000,icon='Spell_Frost_Frost'},
  ['Бросить топливо в огонь']={t=500,icon='Temp'},
  ['Бросок бомбы-вонючки']={t=2000,icon='INV_Misc_Bowl_01'},
  ['Бросок грязью']={t=1000,icon='Spell_Nature_Sleep'},
  ['Бросок динамита']={t=2000,icon='Spell_Fire_SelfDestruct'},
  ['Бросок дротика Купидона']={t=1000,icon='Temp'},
  ['Бросок зелья']={t=2000,icon='Spell_Misc_Drink'},
  ['Бросок камня']={t=3000,icon='Ability_GolemStormBolt'},
  ['Бросок камня II']={t=3000,icon='Ability_GolemStormBolt'},
  ['Бросок кошмарного предмета']={t=2000,icon='Spell_Fire_SelfDestruct'},
  ['Бросок топора']={t=1000,icon='INV_Axe_08'},
  ['Бросок факела']={t=1000,icon='Spell_Fire_Flare'},
  ['Бросок эля Черного Железа']={t=500,icon='Temp'},
  ['Брызги пламени']={t=1700,icon='Spell_Fire_Fire'},
  ['Бузинный пирог']={t=1000,icon='INV_Misc_Food_10'},
  ['Бумеранг Линкена']={t=500,icon='INV_Weapon_ShortBlade_10'},
  ['Бурая змейка']={t=1000,icon='Ability_Seal'},
  ['Бурчаль']={t=1000,icon='Ability_Seal'},
  ['Бурый баран']={t=3000,icon='Ability_Mount_MountainRam'},
  ['Бурый кодо']={t=3000,icon='Ability_Mount_Kodo_03'},
  ['Буря маны']={t=2000,icon='Spell_Frost_IceStorm'},
  ['Быстрая Защита от магии льда']={t=1500,icon='Spell_Fire_SealOfFire'},
  ['Быстродействующая отрава']={t=3000,icon='INV_Potion_19'},
  ['Быстродействующий яд']={t=3000,icon='Ability_Poisons'},
  ['Быстродействующий яд II']={t=3000,icon='Ability_Poisons'},
  ['Быстродействующий яд III']={t=3000,icon='Ability_Poisons'},
  ['Быстродействующий яд IV']={t=3000,icon='Ability_Poisons'},
  ['Быстродействующий яд V']={t=3000,icon='Ability_Poisons'},
  ['Быстродействующий яд VI']={t=3000,icon='Ability_Poisons'},
  ['Быстрое исцеление']={t=1500,icon='Spell_Holy_FlashHeal'},
  ['Быстрый оберег от пламени']={t=1500,icon='Spell_Fire_SealOfFire'},
  ['Валун']={t=2000,icon='Ability_Throw'},
  ['Великан']={t=3000,icon='Spell_Fire_SelfDestruct'},
  ['Великое исцеление']={t=3000,icon='Spell_Holy_GreaterHeal'},
  ['Верховая черепаха']={t=3000,icon='Ability_Hunter_Pet_Turtle'},
  ['Верховой кодо']={t=3000,icon='INV_Misc_Head_Tauren_02'},
  ['Взлом замка']={t=5000,icon='Spell_Nature_MoonKey'},
  ['Взрыв']={t=10000,icon='Spell_Fire_SelfDestruct'},
  ['Взрыв Оззи']={t=2000,icon='Temp'},
  ['Взрыв разума']={t=1500,icon='Spell_Shadow_UnholyFrenzy'},
  ['Взрыв скелета-шахтера']={t=5000,icon='Spell_Fire_SelfDestruct'},
  ['Взрывной выстрел']={t=1000,icon='Spell_Fire_Fireball02'},
  ['Взрывоопасная овца']={t=2000,icon='Ability_Repair'},
  ['Визуальный эффект исчезновения Оуро']={t=1500,icon='Spell_Fire_Volcano'},
  ['Вихрь']={t=2000,icon='Spell_Nature_Cyclone'},
  ['Власть']={t=1000,icon='Spell_Shadow_ShadowWordDominate'},
  ['Вогнать пику Нимбойи с тролльими черепами']={t=2000,icon='Temp'},
  ['Водяной пузырь']={t=1000,icon='Spell_Frost_Wisp'},
  ['Возвращение']={t=10000,icon='Temp'},
  ['Воззвание к Айвусу']={t=10000,icon='Temp'},
  ['Возрождение']={t=2000,icon='Spell_Nature_Reincarnation'},
  ['Возрождение пещерной крысы']={t=3000,icon='Spell_Holy_Resurrection'},
  ['Вой Северного Волка']={t=3000,icon='Ability_Mount_WhiteDireWolf'},
  ['Вой банши']={t=2000,icon='Spell_Shadow_Possession'},
  ['Вой ужаса']={t=2000,icon='Spell_Shadow_DeathScream'},
  ['Волна исцеления']={t=3000,icon='Spell_Nature_MagicImmunity'},
  ['Волшебное масло']={t=3000,icon='Temp'},
  ['Волшебный огонь']={t=2000,icon='Spell_Nature_FaerieFire'},
  ['Воля Шахрама']={t=1000,icon='Spell_Holy_MindVision'},
  ['Вороной боевой скакун']={t=3000,icon='Ability_Mount_NightmareHorse'},
  ['Вороной жеребец']={t=3000,icon='Ability_Mount_NightmareHorse'},
  ['Ворчаль']={t=1000,icon='Ability_Seal'},
  ['Воскресение Алых']={t=2000,icon='Spell_Holy_Resurrection'},
  ['Воскресение Сквернстрома']={t=3000,icon='Spell_Totem_WardOfDraining'},
  ['Воскрешение']={t=10000,icon='Spell_Holy_Resurrection'},
  ['Воскрешение камнем души']={t=3000,icon='Spell_Shadow_SoulGem'},
  ['Воскрешение мертвых']={t=1000,icon='Spell_Shadow_RaiseDead'},
  ['Воскрешение нежити-скарабея']={t=1000,icon='Spell_Shadow_Contagion'},
  ['Воскрешение питомца']={t=10000,icon='Ability_Hunter_BeastSoothe'},
  ['Воспламенение Крошиуса']={t=3000,icon='Temp'},
  ['Воспламеняющий порошок']={t=5000,icon='Temp'},
  ['Воспламеняющий порошок Магаты']={t=1300,icon='Temp'},
  ['Воссоздание']={t=3000,icon='Temp'},
  ['Восстановление']={t=2000,icon='Spell_Nature_ResistNature'},
  ['Восстановление духа']={t=3000,icon='Spell_Nature_MoonGlow'},
  ['Восстановление духа II']={t=3000,icon='Spell_Nature_MoonGlow'},
  ['Всевидяшее Око Рисона']={t=1000,icon='Ability_Ambush'},
  ['Всецветный летун']={t=3000,icon='INV_Misc_Head_Dragon_Black'},
  ['Всплеск кислоты']={t=1000,icon='INV_Drink_06'},
  ['Всплеск лавы']={t=2000,icon='Spell_Fire_Fire'},
  ['Вспышка Света']={t=1500,icon='Spell_Holy_FlashHeal'},
  ['Вспышка магмы']={t=1000,icon='Spell_Fire_FlameShock'},
  ['Вспышка молнии']={t=3200,icon='Spell_Nature_Lightning'},
  ['Вспышка тени']={t=500,icon='Spell_Shadow_DetectLesserInvisibility'},
  ['Вуду']={t=1000,icon='Spell_Shadow_AntiShadow'},
  ['Вудуистский сглаз']={t=1000,icon='Spell_Shadow_CurseOfMannoroth'},
  ['Выброс огня']={t=1500,icon='Spell_Fire_FireBolt'},
  ['Выброс пламени']={t=3000,icon='Spell_Fire_SelfDestruct'},
  ['Выжигание участка']={t=3000,icon='Spell_Fire_SelfDestruct'},
  ['Вызов Аквамонтоса']={t=2000,icon='Temp'},
  ['Вызов Анафемы']={t=1000,icon='Temp'},
  ['Вызов Ар\'лии']={t=2500,icon='Spell_Nature_GroundingTotem'},
  ['Вызов Благословения']={t=1000,icon='Temp'},
  ['Вызов Вибрисса']={t=1000,icon='Ability_Seal'},
  ['Вызов Демона Бездны']={t=4000,icon='Spell_Shadow_GatherShadows'},
  ['Вызов Древних']={t=7000,icon='Temp'},
  ['Вызов Зубощелка']={t=3000,icon='Temp'},
  ['Вызов Ичияки']={t=500,icon='Spell_Shadow_LifeDrain'},
  ['Вызов Ишамухала']={t=2000,icon='Spell_Shadow_LifeDrain'},
  ['Вызов Лунокогтя']={t=3000,icon='Temp'},
  ['Вызов Охранных иероглифов']={t=3000,icon='Temp'},
  ['Вызов Разелиха']={t=10000,icon='Temp'},
  ['Вызов Телрина DND']={t=1000,icon='Temp'},
  ['Вызов Торопыги']={t=1000,icon='Ability_Seal'},
  ['Вызов Умки']={t=1000,icon='Ability_Seal'},
  ['Вызов Ши-Ротам']={t=2500,icon='Temp'},
  ['Вызов Эданы Коготь Ненависти']={t=4000,icon='Temp'},
  ['Вызов бесцветного ворга']={t=1300,icon='Spell_Shadow_ChillTouch'},
  ['Вызов бога-паука']={t=10000,icon='Spell_Shadow_LifeDrain'},
  ['Вызов боевого коня']={t=3000,icon='Spell_Nature_Swiftness'},
  ['Вызов восставшего лакея']={t=2000,icon='Spell_Shadow_RaiseDead'},
  ['Вызов гномского тревого-бота']={t=250,icon='INV_Gizmo_08'},
  ['Вызов гоблинской бомбы']={t=250,icon='Ability_Repair'},
  ['Вызов дракончика Гнездовья']={t=2000,icon='Temp'},
  ['Вызов древних духов']={t=2000,icon='Temp'},
  ['Вызов духа крикуна']={t=2000,icon='Temp'},
  ['Вызов желтого киражского боевого танка']={t=3000,icon='INV_Misc_QirajiCrystal_01'},
  ['Вызов зайчика-побегайчика']={t=1000,icon='Ability_Seal'},
  ['Вызов зеленого киражского боевого танка']={t=3000,icon='INV_Misc_QirajiCrystal_03'},
  ['Вызов знамени Каранга']={t=500,icon='Temp'},
  ['Вызов зомби']={t=2000,icon='Spell_Shadow_RaiseDead'},
  ['Вызов котенка']={t=2000,icon='INV_Box_PetCarrier_01'},
  ['Вызов красного киражского боевого танка']={t=3000,icon='INV_Misc_QirajiCrystal_02'},
  ['Вызов кровавого попугая']={t=1000,icon='Ability_Seal'},
  ['Вызов ксоротианского коня погибели']={t=5000,icon='Temp'},
  ['Вызов магического посоха']={t=2000,icon='INV_Staff_26'},
  ['Вызов малых кровоцветов-паразитов']={t=2000,icon='Spell_Shadow_DarkSummoning'},
  ['Вызов мистера Вертихрюша']={t=1000,icon='Ability_Seal'},
  ['Вызов омерзительного слизнюченыша']={t=1000,icon='Ability_Seal'},
  ['Вызов орды Сокровища']={t=1500,icon='Temp'},
  ['Вызов орды Сокровища - визуальный эффект']={t=1500,icon='Temp'},
  ['Вызов порождения Бал\'Гора']={t=4000,icon='Spell_Fire_LavaSpawn'},
  ['Вызов призматического барьера']={t=10000,icon='Temp'},
  ['Вызов прислужника']={t=500,icon='Temp'},
  ['Вызов разрушителя из племени Маграм']={t=4000,icon='Spell_Shadow_RaiseDead'},
  ['Вызов синего киражского боевого танка']={t=3000,icon='INV_Misc_QirajiCrystal_04'},
  ['Вызов сироты']={t=1000,icon='Ability_Seal'},
  ['Вызов скалокрылой горгульи']={t=10000,icon='Spell_Shadow_UnsummonBuilding'},
  ['Вызов скарабея-падальщика']={t=2000,icon='Spell_Shadow_CarrionSwarm'},
  ['Вызов скелета']={t=2000,icon='Spell_Shadow_RaiseDead'},
  ['Вызов слюнявого ворга']={t=1300,icon='Spell_Shadow_ChillTouch'},
  ['Вызов союзников-древней']={t=1500,icon='Spell_Nature_ForceOfNature'},
  ['Вызов темного чародея']={t=5000,icon='Spell_Shadow_RaiseDead'},
  ['Вызов хрупкого скелета']={t=10000,icon='Spell_Shadow_RaiseDead'},
  ['Выползки']={t=5000,icon='Trade_Fishing'},
  ['Выпустить Эшкромба']={t=4000,icon='Spell_Nature_MoonKey'},
  ['Высидеть яйцо из Гнездовья']={t=1000,icon='Temp'},
  ['Выстрел из лука']={t=1000,icon='Ability_Marksmanship'},
  ['Выстрел из пушки']={t=2000,icon='Temp'},
  ['Выстрел ракетой']={t=3000,icon='Temp'},
  ['Выстрел с арбалета']={t=1000,icon='Ability_Marksmanship'},
  ['Выстрел с огнестрельного оружия']={t=1000,icon='Ability_Marksmanship'},
  ['Вытягивание энергии']={t=1500,icon='Spell_Shadow_Cripple'},
  ['Газовая бомба']={t=1000,icon='INV_Misc_Ammo_Bullet_01'},
  ['Гиацинтовый ара']={t=1000,icon='Ability_Seal'},
  ['Глаз Йесмура (PT)']={t=2000,icon='Temp'},
  ['Глаз Рисона в небе']={t=1000,icon='Ability_Hunter_EagleEye'},
  ['Глоток зелья']={t=3000,icon='Spell_Holy_Heal'},
  ['Глоток малого зелья']={t=3000,icon='Spell_Holy_Heal'},
  ['Глубокая дремота']={t=1000,icon='Spell_Shadow_Cripple'},
  ['Гнев']={t=2000,icon='Spell_Nature_AbolishMagic'},
  ['Гнев деревьев']={t=1500,icon='Spell_Nature_StrangleVines'},
  ['Гнев небес']={t=2000,icon='Spell_Holy_Excorcism'},
  ['Гнедая кобыла']={t=3000,icon='Ability_Mount_RidingHorse'},
  ['Гнедой конь']={t=3000,icon='Ability_Mount_RidingHorse'},
  ['Гнедой конь-скелет']={t=3000,icon='Ability_Mount_Undeadhorse'},
  ['Гниение разума']={t=2000,icon='Spell_Shadow_MindRot'},
  ['Гномский транспортер']={t=10000,icon='Temp'},
  ['Гнущаяся берцовая кость']={t=1500,icon='Temp'},
  ['Гоблинская мина']={t=1000,icon='Spell_Shadow_Metamorphosis'},
  ['Гоблинская мортира']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Головокружительная боль']={t=1500,icon='Spell_Nature_CorrosiveBreath'},
  ['Голодный рой']={t=3000,icon='Spell_Holy_Dizzy'},
  ['Гонг']={t=500,icon='Temp'},
  ['Гонг из Зул\'Фаррака - гонг']={t=500,icon='Temp'},
  ['Горное дело']={t=3200,icon='Trade_Mining'},
  ['Горящие ветра']={t=1000,icon='Spell_Nature_Cyclone'},
  ['Господство над душой']={t=3000,icon='Spell_Shadow_ShadowWordDominate'},
  ['Господство над разумом']={t=2000,icon='Spell_Shadow_ShadowWordDominate'},
  ['Град огненных шаров']={t=3000,icon='Spell_Fire_FlameBolt'},
  ['Град стрел']={t=3000,icon='Ability_TheBlackArrow'},
  ['Град стрел II']={t=3000,icon='Ability_TheBlackArrow'},
  ['Грозовая туча']={t=3000,icon='Spell_Nature_CallStorm'},
  ['Грозовое дыхание']={t=2000,icon='Spell_Nature_Lightning'},
  ['Громовая поступь']={t=500,icon='Ability_WarStomp'},
  ['Грубая медная бомба']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Грубый динамит']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Гурчаль']={t=1000,icon='Ability_Seal'},
  ['Д\'жииви создает объект']={t=2000,icon='Temp'},
  ['Дальнее зрение']={t=2000,icon='Spell_Nature_FarSight'},
  ['Дальнее зрение (РТ)']={t=2000,icon='Temp'},
  ['Дальний выстрел II']={t=4000,icon='Ability_Marksmanship'},
  ['Дальний выстрел III']={t=4000,icon='Ability_Marksmanship'},
  ['Данные о температуре']={t=2000,icon='Temp'},
  ['Дар Аругала']={t=2500,icon='Spell_Shadow_ChillTouch'},
  ['Дар Ксавиана']={t=5000,icon='Spell_Holy_FlashHeal'},
  ['Двойник']={t=2500,icon='Spell_Shadow_BlackPlague'},
  ['Детеныш гиппогрифа']={t=1000,icon='Ability_Seal'},
  ['Детеныш панды']={t=1000,icon='Ability_Seal'},
  ['Дефибриллировать']={t=4000,icon='Spell_Nature_Purge'},
  ['Дикое восстановление']={t=3000,icon='Spell_Nature_Rejuvenation'},
  ['Динамит']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Динамит "Pro-100-брос"']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Динамит Мертвых копей']={t=2000,icon='Spell_Fire_SelfDestruct'},
  ['Дистанционный взрыв']={t=1000,icon='INV_Misc_StoneTablet_04'},
  ['Драко-инкарцинатор 900']={t=2000,icon='Temp'},
  ['Древесная лягушка']={t=1000,icon='Ability_Seal'},
  ['Древний ледопард']={t=3000,icon='Ability_Mount_WhiteTiger'},
  ['Древоголовый хрустогрыз']={t=1000,icon='Ability_Seal'},
  ['Друидская дремота']={t=2500,icon='Spell_Nature_Sleep'},
  ['Дурманящий яд']={t=3000,icon='Spell_Nature_NullifyDisease'},
  ['Дурманящий яд II']={t=3000,icon='Spell_Nature_NullifyDisease'},
  ['Дурманящий яд III']={t=3000,icon='Spell_Nature_NullifyDisease'},
  ['Дурной глаз']={t=1500,icon='Spell_Shadow_Charm'},
  ['Дух']={t=500,icon='Temp'},
  ['Дух дикого волка']={t=3000,icon='Spell_Nature_SpiritWolf'},
  ['Дух дикого волка II']={t=3000,icon='Spell_Nature_SpiritWolf'},
  ['Дух предков']={t=10000,icon='Spell_Nature_Regenerate'},
  ['Дух-целитель']={t=2000,icon='Spell_Holy_LayOnHands'},
  ['Душевный укус']={t=2000,icon='Spell_Shadow_SiphonMana'},
  ['Дыхание']={t=5000,icon='Spell_Fire_Fire'},
  ['Дыхание Саргераса']={t=2000,icon='Spell_Shadow_Metamorphosis'},
  ['Дыхание льда']={t=250,icon='Spell_Frost_FrostNova'},
  ['Дыхание песка']={t=2000,icon='Spell_Fire_WindsofWoe'},
  ['Едкий яд']={t=1500,icon='Spell_Nature_CorrosiveBreath'},
  ['Едкий ядовитый плевок']={t=2500,icon='Spell_Nature_CorrosiveBreath'},
  ['Жаблинг']={t=1000,icon='Ability_Seal'},
  ['Жареный сморк']={t=1000,icon='INV_SummerFest_Smorc'},
  ['Жгучая боль']={t=1500,icon='Spell_Fire_SoulBurn'},
  ['Жгучее пламя']={t=2000,icon='Spell_Fire_Immolation'},
  ['Железная граната']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Жертвенные паутинные железы']={t=10000,icon='Temp'},
  ['Жертвенный огонь']={t=2000,icon='Spell_Fire_Immolation'},
  ['Жертвоприношение']={t=1000,icon='Spell_Holy_DivineIntervention'},
  ['Жидкая руда']={t=1500,icon='Spell_Fire_SelfDestruct'},
  ['Жуки-трупоеды']={t=3000,icon='Spell_Nature_InsectSwarm'},
  ['Жуткокоготь']={t=1000,icon='Spell_Shadow_ShadowPact'},
  ['ЗАКЛИНАНИЕ ЗАДАНИЯ ЧУ']={t=4000,icon='Spell_Shadow_LifeDrain'},
  ['Задание - Вызов древня']={t=3000,icon='Spell_Nature_NatureTouchGrow'},
  ['Задание - Заклинание Сергры Черный Шип.']={t=3000,icon='Temp'},
  ['Задание - Появление вне телепорта']={t=1000,icon='Temp'},
  ['Задание - герой троллей']={t=30000,icon='Temp'},
  ['Закладка заряда NG-5 (красного)']={t=5000,icon='INV_Misc_Bomb_05'},
  ['Закладка заряда NG-5 (синего)']={t=5000,icon='INV_Misc_Bomb_05'},
  ['Заклинание вызова дракончика Гнездовья']={t=500,icon='Temp'},
  ['Заклинание появления Аругала']={t=2000,icon='Temp'},
  ['Заключение']={t=2000,icon='Spell_Shadow_Teleport'},
  ['Заколдованное семечко Геи']={t=5000,icon='Temp'},
  ['Закрытие']={t=1000,icon='Temp'},
  ['Залп ледяных стрел']={t=2000,icon='Spell_Frost_FrostBolt02'},
  ['Залп стрел Тьмы']={t=3000,icon='Spell_Shadow_ShadowBolt'},
  ['Залп шипов']={t=500,icon='Ability_ImpalingBolt'},
  ['Замедляющий яд']={t=1000,icon='Spell_Nature_SlowPoison'},
  ['Заморозить яйцо из Гнездовья']={t=500,icon='Temp'},
  ['Заморозить яйцо из Гнездовья - модель']={t=500,icon='Temp'},
  ['Запуск ракеты']={t=3000,icon='INV_Ammo_Bullet_03'},
  ['Запуск снаряда']={t=3000,icon='INV_Ammo_Bullet_03'},
  ['Заразная слизь']={t=2000,icon='Spell_Shadow_CreepingPlague'},
  ['Заразное веселье']={t=1000,icon='Spell_Shadow_DarkSummoning'},
  ['Заразный выстрел']={t=2000,icon='Spell_Shadow_CallofBone'},
  ['Зарядка']={t=5000,icon='Spell_Shadow_EvilEye'},
  ['Заряженная чародейская стрела']={t=7000,icon='Spell_Arcane_StarFire'},
  ['Засасывающая жижа']={t=1000,icon='Spell_Nature_StrangleVines'},
  ['Застревание']={t=10000,icon='Spell_Shadow_Teleport'},
  ['Засуха']={t=1500,icon='Spell_Nature_NullifyDisease'},
  ['Затмение зрения']={t=2000,icon='Spell_Shadow_Fumble'},
  ['Заточка клинка']={t=3000,icon='Temp'},
  ['Заточка клинка II']={t=3000,icon='Temp'},
  ['Заточка клинка III']={t=3000,icon='Temp'},
  ['Заточка клинка IV']={t=3000,icon='Temp'},
  ['Заточка клинка V']={t=3000,icon='Temp'},
  ['Заточка оружия - критическое поражение']={t=3000,icon='Temp'},
  ['Зачарование нагрудника - дух I']={t=5000,icon='Spell_Holy_GreaterHeal'},
  ['Зачарование нагрудника - малое поглощение']={t=5000,icon='Spell_Holy_GreaterHeal'},
  ['Зачарование плаща - малое сопротивление']={t=5000,icon='Spell_Holy_GreaterHeal'},
  ['Зачаровывание']={t=3500,icon='Temp'},
  ['Защита Праудмура']={t=3000,icon='Spell_Holy_BlessingOfProtection'},
  ['Заяц-беляк']={t=1000,icon='Ability_Seal'},
  ['Звездный огонь']={t=3500,icon='Spell_Arcane_StarFire'},
  ['Звенья молний']={t=1800,icon='Spell_Nature_ChainLightning'},
  ['Звериный глаз']={t=2000,icon='Ability_EyeOfTheOwl'},
  ['Зеленая водяная змея']={t=1000,icon='Ability_Seal'},
  ['Зеленокрылый ара']={t=1000,icon='Ability_Seal'},
  ['Зеленый боевой конь-скелет']={t=3000,icon='Ability_Mount_Undeadhorse'},
  ['Зеленый грог Гордока']={t=1000,icon='INV_Drink_03'},
  ['Зеленый кодо']={t=3000,icon='Ability_Mount_Kodo_02'},
  ['Зеленый механодолгоног']={t=3000,icon='Ability_Mount_MechaStrider'},
  ['Зерглинг']={t=1000,icon='Ability_Seal'},
  ['Злой Бог']={t=300000,icon='Temp'},
  ['Змеиное очищение']={t=30000,icon='Spell_Shadow_LifeDrain'},
  ['Змейка-альбинос']={t=1000,icon='Ability_Seal'},
  ['Знак Пламени']={t=1000,icon='Spell_Fire_Fireball'},
  ['Зов Бездны']={t=3000,icon='Spell_Shadow_DeathCoil'},
  ['Зов Пустоты']={t=10000,icon='Temp'},
  ['Зов могилы']={t=2000,icon='Spell_Shadow_ChillTouch'},
  ['Зов тунда']={t=1500,icon='Spell_Frost_Wisp'},
  ['Золотая отмычка']={t=5000,icon='Temp'},
  ['Золотой саблезуб']={t=3000,icon='Ability_Mount_JungleTiger'},
  ['Игреневый жеребец']={t=3000,icon='Ability_Mount_RidingHorse'},
  ['Игреневый конь']={t=3000,icon='Ability_Mount_RidingHorse'},
  ['Избирательное гашение']={t=2000,icon='Spell_Holy_SearingLight'},
  ['Изгнание']={t=1500,icon='Spell_Shadow_Cripple'},
  ['Изгнание грозового изгоя']={t=1000,icon='Spell_Shadow_LifeDrain'},
  ['Изгнание морского изгоя']={t=1000,icon='Spell_Shadow_LifeDrain'},
  ['Изгнание нежити']={t=1500,icon='Spell_Holy_TurnUndead'},
  ['Изгнание призраков']={t=4000,icon='Temp'},
  ['Изгнание пылающего изгоя']={t=1000,icon='Spell_Shadow_LifeDrain'},
  ['Излечение болезни']={t=2500,icon='Spell_Holy_NullifyDisease'},
  ['Изначальный леопард']={t=3000,icon='Ability_Mount_JungleTiger'},
  ['Изумрудный ящер']={t=3000,icon='Ability_Mount_Raptor'},
  ['Изучить Роковой рык']={t=1000,icon='Temp'},
  ['Инициатор вращения']={t=3000,icon='Temp'},
  ['Инфернал']={t=2000,icon='Spell_Shadow_SummonInfernal'},
  ['Инфернальный снаряд']={t=3000,icon='Spell_Fire_SelfDestruct'},
  ['Искажение времени']={t=2000,icon='Spell_Arcane_PortalOrgrimmar'},
  ['Искра']={t=2000,icon='Spell_Nature_Lightning'},
  ['Искупление']={t=10000,icon='Spell_Holy_Resurrection'},
  ['Испепеление']={t=2000,icon='Spell_Shadow_ChillTouch'},
  ['Использование приманки']={t=4000,icon='Temp'},
  ['Использовать блесну']={t=3000,icon='Temp'},
  ['Исправление отношения']={t=2000,icon='INV_Gizmo_01'},
  ['Исправление ритуального колокольчика (DND)']={t=3000,icon='Temp'},
  ['Исправление ритуального элемента']={t=3000,icon='Temp'},
  ['Исправление ритуальной свечи (DND)']={t=3000,icon='Temp'},
  ['Испытание знаний']={t=2000,icon='Spell_Nature_EarthBind'},
  ['Истинное счастье']={t=500,icon='Spell_Shadow_Charm'},
  ['Истощение души']={t=2000,icon='Spell_Shadow_LifeDrain02'},
  ['Исцеление']={t=3000,icon='Spell_Holy_Heal02'},
  ['Исцеление - визуальное (DND)']={t=3500,icon='Spell_Holy_Heal'},
  ['Исцеление гнусь-лозы']={t=500,icon='Temp'},
  ['Исцеление от проказы']={t=2000,icon='Spell_Holy_FlashHeal'},
  ['Исцеление тьмой']={t=3500,icon='Spell_Shadow_ChillTouch'},
  ['Исцеляющая волна Антусула']={t=1000,icon='Spell_Holy_Heal02'},
  ['Исцеляющая речь']={t=1000,icon='Spell_Holy_Heal'},
  ['Исцеляющая речь II']={t=1000,icon='Spell_Holy_Heal'},
  ['Исчезновение прислужников Урока']={t=2000,icon='Temp'},
  ['Калечащий яд']={t=3000,icon='Ability_PoisonSting'},
  ['Каменная Кожа']={t=6000,icon='Spell_Nature_EnchantArmor'},
  ['Камень возвращения']={t=10000,icon='INV_Misc_Rune_01'},
  ['Кара']={t=2500,icon='Spell_Holy_HolySmite'},
  ['Карманник (PT)']={t=5000,icon='Temp'},
  ['Касание смерти']={t=3000,icon='Spell_Shadow_UnsummonBuilding'},
  ['Касание увядания']={t=2000,icon='Spell_Nature_Drowsy'},
  ['Каскад роз']={t=500,icon='INV_Misc_Dust_04'},
  ['Квинтессенция воды - гашение руны Огненных Недр']={t=1000,icon='Temp'},
  ['Кев']={t=3000,icon='Spell_Fire_FireBolt'},
  ['Кирка демона']={t=5000,icon='Temp'},
  ['Кислота Хаккара']={t=1000,icon='Spell_Nature_Acid_01'},
  ['Кислотные брызги']={t=2000,icon='Spell_Nature_Acid_01'},
  ['Кислотный плевок']={t=3000,icon='Spell_Nature_Acid_01'},
  ['Клинок фанатика']={t=1000,icon='Spell_Fire_Immolation'},
  ['Ключ от клетки пантеры']={t=5000,icon='Temp'},
  ['Ключевой посох Ульдамана']={t=5000,icon='Temp'},
  ['Коварство ящера']={t=3000,icon='INV_Misc_MonsterClaw_02'},
  ['Коготь зверя']={t=1000,icon='Spell_Nature_Regeneration'},
  ['Когти зверя II']={t=1000,icon='Spell_Nature_Regeneration'},
  ['Когти зверя III']={t=1000,icon='Spell_Nature_Regeneration'},
  ['Кожеспинный хрустогрыз']={t=1000,icon='Ability_Seal'},
  ['Колдовской кристалл резонита']={t=5000,icon='Temp'},
  ['Колодец Света']={t=1500,icon='Spell_Holy_SummonLightwell'},
  ['Колокольчик Шая']={t=4500,icon='Temp'},
  ['Колоссальный удар']={t=5000,icon='Temp'},
  ['Кольцо Тьмы II']={t=3000,icon='Spell_Shadow_ShadeTrueSight'},
  ['Ком грязи']={t=1000,icon='Spell_Nature_Sleep'},
  ['Комок слизи']={t=2500,icon='Spell_Nature_CorrosiveBreath'},
  ['Контроль над разумом']={t=3000,icon='Spell_Shadow_ShadowWordDominate'},
  ['Концентрированный динамит']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Конь смерти Ривендера']={t=3000,icon='Ability_Mount_Undeadhorse'},
  ['Конь-скелет']={t=3000,icon='Ability_Mount_Undeadhorse'},
  ['Корелла']={t=1000,icon='Ability_Seal'},
  ['Коричневый волк']={t=3000,icon='Ability_Mount_BlackDireWolf'},
  ['Корниш-рекс']={t=1000,icon='Ability_Seal'},
  ['Король Гордока']={t=1000,icon='INV_Crown_02'},
  ['Котловина для колонны']={t=5000,icon='Temp'},
  ['Кошачий облик Змейера DND']={t=1000,icon='Temp'},
  ['Кошмар Наралекса']={t=2000,icon='Spell_Nature_Sleep'},
  ['Кража жизни']={t=1500,icon='Spell_Shadow_LifeDrain02'},
  ['Крапчатый красный ящер']={t=3000,icon='Ability_Mount_Raptor'},
  ['Красно-синий механодолгоног']={t=3000,icon='Ability_Mount_MechaStrider'},
  ['Красный боевой конь-скелет']={t=3000,icon='Ability_Mount_Undeadhorse'},
  ['Красный конь-скелет']={t=3000,icon='Ability_Mount_Undeadhorse'},
  ['Красный механодолгоног']={t=3000,icon='Ability_Mount_MechaStrider'},
  ['Кривоклювый хрустогрыз']={t=1000,icon='Ability_Seal'},
  ['Кровавый вой']={t=1000,icon='Spell_Shadow_LifeDrain'},
  ['Крошечная ходячая бомба']={t=1000,icon='Ability_Seal'},
  ['Крошечный зеленый дракончик']={t=1000,icon='Ability_Seal'},
  ['Крошечный красный дракончик']={t=1000,icon='Ability_Seal'},
  ['Крошка Дымок']={t=1000,icon='Ability_Seal'},
  ['Крутящийся заряд']={t=1500,icon='INV_Spear_05'},
  ['Кулак Шахрама']={t=1000,icon='Ability_Whirlwind'},
  ['Кусеница']={t=5000,icon='INV_Misc_Orb_03'},
  ['Кэларан создает факел']={t=1000,icon='Temp'},
  ['Лавовый дождь']={t=2000,icon='Temp'},
  ['Лазурный дракончик']={t=1000,icon='Ability_Seal'},
  ['Леденящее касание Трелана']={t=3000,icon='Spell_Shadow_UnsummonBuilding'},
  ['Ледниковый рев']={t=1000,icon='Spell_Frost_FrostNova'},
  ['Ледопард Зимних Ключей']={t=3000,icon='Ability_Mount_PinkTiger'},
  ['Ледяная могила']={t=1500,icon='Spell_Frost_Glacier'},
  ['Ледяная стрела']={t=3000,icon='Spell_Frost_FrostBolt02'},
  ['Ледяной ожог']={t=2000,icon='Spell_Frost_ChillingBlast'},
  ['Ледяные оковы']={t=1300,icon='Spell_Frost_ChainsOfIce'},
  ['Леопард']={t=3000,icon='Ability_Mount_JungleTiger'},
  ['Лесная лягушка']={t=1000,icon='Ability_Seal'},
  ['Летняя колбаска']={t=1000,icon='INV_Misc_Food_53'},
  ['Летучая зараза']={t=2000,icon='Spell_Holy_HarmUndeadAura'},
  ['Лечение Тарнариуна']={t=500,icon='Spell_Nature_MagicImmunity'},
  ['Ликвидация маны']={t=2000,icon='Spell_Shadow_DarkRitual'},
  ['Лиловый боевой конь-скелет']={t=3000,icon='Ability_Mount_Undeadhorse'},
  ['Лиловый механодолгоног']={t=3000,icon='Ability_Mount_MechaStrider'},
  ['Лишение сил']={t=1500,icon='Ability_Creature_Poison_03'},
  ['Ловля термитов']={t=5000,icon='Temp'},
  ['Ложная мишень НИП - призывание']={t=20000,icon='Spell_Shadow_UnsummonBuilding'},
  ['Ложная мишень дистанционной атаки']={t=2000,icon='Temp'},
  ['Луговая собачка']={t=1000,icon='Ability_Seal'},
  ['Луч ока']={t=2000,icon='Spell_Nature_CallStorm'},
  ['Льдисто-синий механодолгоног модель А']={t=3000,icon='Ability_Mount_MechaStrider'},
  ['Любвный эликсир Нагмары']={t=1000,icon='Temp'},
  ['Лютый волк']={t=3000,icon='Ability_Mount_WhiteDireWolf'},
  ['Лютый рык']={t=1000,icon='Ability_Racial_Cannibalize'},
  ['Магическое зрение']={t=3000,icon='Temp'},
  ['Майский шест']={t=10000,icon='Spell_Shadow_Twilight'},
  ['Малая волна исцеления']={t=1500,icon='Spell_Nature_HealingWaveLesser'},
  ['Маленький багровый дракончик']={t=1000,icon='Ability_Seal'},
  ['Маленький изумрудный дракончик']={t=1000,icon='Ability_Seal'},
  ['Маленький темный дракончик']={t=1000,icon='Ability_Seal'},
  ['Малое исцеление']={t=2500,icon='Spell_Holy_LesserHeal'},
  ['Малый сефориевый заряд']={t=5000,icon='Temp'},
  ['Маскировка батрака']={t=3000,icon='Ability_Rogue_Disguise'},
  ['Маскировка крестьянина']={t=3000,icon='Ability_Rogue_Disguise'},
  ['Маскировка под Даларанского волшебника']={t=3000,icon='Ability_Rogue_Disguise'},
  ['Маскировка под дворфа из клана Черного Железа']={t=3000,icon='Ability_Rogue_Disguise'},
  ['Маскировка под пирата Южных морей']={t=3000,icon='Ability_Rogue_Disguise'},
  ['Маскировка под трогга Осколка Камня']={t=3000,icon='Ability_Rogue_Disguise'},
  ['Маскировка под члена Братства Справедливости']={t=3000,icon='Ability_Rogue_Disguise'},
  ['Маскировка под члена Синдиката']={t=3000,icon='Ability_Rogue_Disguise'},
  ['Масло Тьмы']={t=3000,icon='Temp'},
  ['Масло льда']={t=3000,icon='Temp'},
  ['Массивный миномет']={t=3000,icon='Temp'},
  ['Массовое исцеление']={t=1000,icon='Spell_Holy_GreaterHeal'},
  ['Массовое рассеивание']={t=1000,icon='Spell_Shadow_Teleport'},
  ['Мастер побега']={t=500,icon='Ability_Rogue_Trip'},
  ['Маяк Ущелья']={t=2000,icon='Spell_Nature_AbolishMagic'},
  ['Мгновенный взрыв']={t=5000,icon='Spell_Fire_SelfDestruct'},
  ['Мегавольт']={t=2000,icon='Spell_Nature_ChainLightning'},
  ['Медленный яд']={t=1000,icon='Spell_Nature_SlowPoison'},
  ['Медленный яд II']={t=1000,icon='Spell_Nature_SlowPoison'},
  ['Месть Аригоса']={t=2000,icon='Temp'},
  ['Механическая белка']={t=1000,icon='Spell_Shadow_Metamorphosis'},
  ['Механическая курица']={t=1000,icon='Ability_Seal'},
  ['Мина клана Черного Железа']={t=1000,icon='Spell_Shadow_Metamorphosis'},
  ['Мини-Диабло']={t=1000,icon='Ability_Seal'},
  ['Миниружье']={t=100,icon='INV_Musket_04'},
  ['Мифриловая осколочная бомба']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Могильные скарабеи']={t=1500,icon='Spell_Shadow_CarrionSwarm'},
  ['Молитва Элуны']={t=1000,icon='Spell_Holy_Resurrection'},
  ['Молитва исцеления']={t=3000,icon='Spell_Holy_PrayerOfHealing02'},
  ['Молния']={t=3000,icon='Spell_Nature_Lightning'},
  ['Молния Бездны']={t=3000,icon='Spell_Shadow_ShadowBolt'},
  ['Молот бурь']={t=1000,icon='INV_Hammer_01'},
  ['Молот гнева']={t=1000,icon='Ability_ThunderClap'},
  ['Моровая лихорадка']={t=4500,icon='Spell_Nature_NullifyDisease'},
  ['Морозная слабость']={t=5000,icon='INV_Misc_QirajiCrystal_04'},
  ['Морозная стрела']={t=2000,icon='Spell_Frost_FrostBolt02'},
  ['Мощные ароматические соли']={t=2000,icon='INV_Misc_Ammo_Gunpowder_01'},
  ['Мощный сефориевый заряд']={t=5000,icon='Temp'},
  ['Мощный удар']={t=1500,icon='Ability_Warrior_DecisiveStrike'},
  ['Мощь Рагнароса']={t=500,icon='Spell_Fire_SelfDestruct'},
  ['Мощь Шахрама']={t=1000,icon='Spell_Nature_WispSplode'},
  ['Мрачноозерная поганка']={t=3000,icon='Spell_Holy_HarmUndeadAura'},
  ['Мудрость зимы']={t=1000,icon='Ability_Ambush'},
  ['Мурчаль']={t=1000,icon='Ability_Seal'},
  ['Мысленная дрожь']={t=2000,icon='Spell_Nature_Earthquake'},
  ['Мысленная чума']={t=4000,icon='Spell_Shadow_CallofBone'},
  ['Набор для рисования']={t=7000,icon='Temp'},
  ['Наксрамасский конь смерти']={t=3000,icon='Ability_Mount_Undeadhorse'},
  ['Наложение чар на нагрудник - поглощение l']={t=5000,icon='Spell_Holy_GreaterHeal'},
  ['Нанесение урона машине']={t=2000,icon='Spell_Fire_Fire'},
  ['Наполнение']={t=3000,icon='Temp'},
  ['Наполнить фиал']={t=5000,icon='Temp'},
  ['Напор волн']={t=2000,icon='Spell_Frost_FrostNova'},
  ['Нарайн!']={t=3000,icon='INV_Misc_Head_Gnome_01'},
  ['Нарушение природного равновесия']={t=10000,icon='Temp'},
  ['Настройка']={t=7000,icon='INV_Gizmo_02'},
  ['Начертание древних рун']={t=10000,icon='Temp'},
  ['Небольшая бронзовая бомба']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Невидимое размещение ловушки на медведя']={t=2000,icon='Temp'},
  ['Невидимость']={t=3000,icon='Spell_Nature_Invisibilty'},
  ['Неистовство стихий']={t=1000,icon='Spell_Fire_FireArmor'},
  ['Нейтрализация бомбы-вонючки']={t=5000,icon='Temp'},
  ['Нейтрализующий яд']={t=3000,icon='INV_Misc_Herb_16'},
  ['Некрашеный механодолгоног']={t=3000,icon='Ability_Mount_MechaStrider'},
  ['Неловкость']={t=1000,icon='Spell_Shadow_Fumble'},
  ['Неловкость II']={t=1000,icon='Spell_Shadow_Fumble'},
  ['Неловкость III']={t=1000,icon='Spell_Shadow_Fumble'},
  ['Ненадежное варево']={t=3000,icon='Spell_Fire_Incinerate'},
  ['Неотвязные призраки']={t=2000,icon='Spell_Shadow_BlackPlague'},
  ['Низкосортный динамит']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Новый магический снаряд (тест)']={t=2000,icon='Temp'},
  ['Ностальгия']={t=4000,icon='Spell_Shadow_LifeDrain'},
  ['Обезвреживание ловушки']={t=2000,icon='Spell_Shadow_GrimWard'},
  ['Облик Лунного охотника (без невидимости)']={t=1000,icon='Ability_Hibernation'},
  ['Облик совы']={t=5000,icon='Spell_Nature_RavenForm'},
  ['Обнаружение племени']={t=10000,icon='Spell_Lightning_LightningBolt01'},
  ['Обновление']={t=2000,icon='Spell_Holy_Renew'},
  ['Обостренные чувства']={t=1000,icon='Temp'},
  ['Образ фурболга']={t=2000,icon='INV_Misc_MonsterClaw_04'},
  ['Обсидиановый ящер']={t=3000,icon='Ability_Mount_Raptor'},
  ['Обстрел']={t=3000,icon='Ability_GolemStormBolt'},
  ['Обстрел II']={t=3000,icon='Ability_GolemStormBolt'},
  ['Обстрел слизи']={t=1000,icon='Temp'},
  ['Общие узы']={t=1500,icon='Spell_Shadow_UnsummonBuilding'},
  ['Объятие Вдовы']={t=500,icon='Spell_Arcane_Blink'},
  ['Обычный костер']={t=10000,icon='Spell_Fire_Fire'},
  ['Оглушающая бомба']={t=2000,icon='Spell_Fire_SelfDestruct'},
  ['Огненная буря']={t=2000,icon='Spell_Fire_SelfDestruct'},
  ['Огненная глыба']={t=6000,icon='Spell_Fire_Fireball02'},
  ['Огненная слабость']={t=5000,icon='INV_Misc_QirajiCrystal_02'},
  ['Огненная стрела']={t=2000,icon='Spell_Fire_FireBolt'},
  ['Огненная стрела II']={t=3000,icon='Spell_Fire_FireBolt02'},
  ['Огненная стрела III']={t=3000,icon='Spell_Fire_FireBolt02'},
  ['Огненная стрела IV']={t=3000,icon='Spell_Fire_FireBolt02'},
  ['Огненная трещина']={t=2500,icon='Spell_Fire_Fire'},
  ['Огненный ливень']={t=3000,icon='Spell_Shadow_RainOfFire'},
  ['Огненный плевок']={t=3000,icon='Spell_Fire_FlameBolt'},
  ['Огненный столб']={t=3000,icon='Spell_Fire_SelfDestruct'},
  ['Огненный шар']={t=3500,icon='Spell_Fire_FlameBolt'},
  ['Огненный щит']={t=1000,icon='Spell_Fire_Immolation'},
  ['Огненный щит II']={t=1000,icon='Spell_Fire_Immolation'},
  ['Огненный щит III']={t=1000,icon='Spell_Fire_Immolation'},
  ['Огненный щит IV']={t=1000,icon='Spell_Fire_Immolation'},
  ['Огромный белый кодо']={t=3000,icon='Ability_Mount_Kodo_01'},
  ['Огромный бурый кодо']={t=3000,icon='Ability_Mount_Kodo_03'},
  ['Огромный гейзер']={t=1500,icon='Spell_Frost_SummonWaterElemental'},
  ['Огромный серый кодо']={t=3000,icon='Ability_Mount_Kodo_01'},
  ['Оживление Ринго']={t=2500,icon='Temp'},
  ['Ожог']={t=1500,icon='Spell_Fire_SoulBurn'},
  ['Ожог души']={t=6000,icon='Spell_Fire_Fireball02'},
  ['Окаменение - направление заклинания']={t=3000,icon='Spell_Nature_Cyclone'},
  ['Око Бессмер\'тера']={t=2000,icon='Spell_Shadow_AntiMagicShell'},
  ['Око Килрогга']={t=5000,icon='Spell_Shadow_EvilEye'},
  ['Окрапление очищенной водой']={t=6000,icon='Temp'},
  ['Окунание']={t=5000,icon='Temp'},
  ['Оливковый хрустогрыз']={t=1000,icon='Ability_Seal'},
  ['Омела']={t=1000,icon='INV_Misc_Branch_01'},
  ['Оплетающие сети']={t=2000,icon='Spell_Nature_EarthBind'},
  ['Оплеуха']={t=1000,icon='Spell_Shadow_LifeDrain'},
  ['Определение Изначального Пламени']={t=1000,icon='Temp'},
  ['Орлиный взор']={t=1000,icon='Ability_TownWatch'},
  ['Освобождение Д\'жииви']={t=2000,icon='Temp'},
  ['Освобождение Йеннику']={t=4000,icon='Spell_Shadow_LifeDrain'},
  ['Освобождение Яростного Когтя']={t=10000,icon='Temp'},
  ['Освобождение беса']={t=2000,icon='Temp'},
  ['Освобождение едкой слизи']={t=5000,icon='INV_Potion_19'},
  ['Освобождение ищейки']={t=2000,icon='Temp'},
  ['Освобождение йети Юми']={t=2000,icon='Temp'},
  ['Освобождение котенка Винны']={t=1000,icon='Ability_Seal'},
  ['Освященное оружие']={t=3000,icon='Temp'},
  ['Осквернение Крассена']={t=2000,icon='Temp'},
  ['Оскверненный котенок']={t=1000,icon='Ability_Seal'},
  ['Осколки костей']={t=500,icon='Spell_Shadow_ScourgeBuild'},
  ['Ослабление']={t=2000,icon='Spell_Shadow_CurseOfMannoroth'},
  ['Ослабление ловкости']={t=2000,icon='Spell_Holy_HarmUndeadAura'},
  ['Ослабление силы']={t=2000,icon='Spell_Holy_HarmUndeadAura'},
  ['Особое существо']={t=2000,icon='Temp'},
  ['Остановка времени']={t=3000,icon='Temp'},
  ['Остановка времени: визуальный эффект DND']={t=3000,icon='Temp'},
  ['Острая грива']={t=1000,icon='Spell_Nature_Thorns'},
  ['Острый шип']={t=500,icon='Ability_ImpalingBolt'},
  ['Отделение души Лорда Вальтхалака DND']={t=5000,icon='Temp'},
  ['Отклонение заклинания (NYI)']={t=1000,icon='Temp'},
  ['Отковка кулака Веригана']={t=600,icon='Spell_Holy_RighteousFury'},
  ['Открытие']={t=5000,icon='Temp'},
  ['Открытие - без текста']={t=5000,icon='Temp'},
  ['Открытие большого сундука Скарабея']={t=5000,icon='Temp'},
  ['Открытие двери бара']={t=5000,icon='Temp'},
  ['Открытие дверцы реликвария']={t=5000,icon='Temp'},
  ['Открытие клетки']={t=5000,icon='Temp'},
  ['Открытие надежного сейфа']={t=5000,icon='Temp'},
  ['Открытие надежного сундука']={t=5000,icon='Temp'},
  ['Открытие потайного сейфа']={t=5000,icon='Temp'},
  ['Открытие почтового ящика Стратхольма']={t=5000,icon='Temp'},
  ['Открытие сейфа']={t=5000,icon='Temp'},
  ['Открытие сундука']={t=5000,icon='Temp'},
  ['Открытие сундука Бенедикта']={t=5000,icon='Temp'},
  ['Открытие сундука Скарабея']={t=5000,icon='Temp'},
  ['Открытие сундука с добычей']={t=5000,icon='Temp'},
  ['Открытие термитной бочки']={t=5000,icon='Temp'},
  ['Открытие черного ящика']={t=5000,icon='Temp'},
  ['Открыть ногу Мори']={t=5000,icon='Temp'},
  ['Отмычка Кадгара']={t=10000,icon='INV_Misc_Key_14'},
  ['Отмычка из истинного серебра']={t=5000,icon='Temp'},
  ['Отношение - Кабестан +500']={t=1000,icon='Temp'},
  ['Отношение - Круговзор +500']={t=1000,icon='Temp'},
  ['Отношение - Пиратская Бухта +500']={t=1000,icon='Temp'},
  ['Отношение - Прибамбасск +500']={t=1000,icon='Temp'},
  ['Отношение - храм Ан\'Киража']={t=1000,icon='Temp'},
  ['Отпирание']={t=5000,icon='Temp'},
  ['Отпугивание зверя']={t=1500,icon='Ability_Druid_Cower'},
  ['Отравляющий плевок']={t=2500,icon='Spell_Nature_CorrosiveBreath'},
  ['Отравляющий удар']={t=2500,icon='Spell_Nature_CorrosiveBreath'},
  ['Очень ягодный крем']={t=1000,icon='INV_ValentinesChocolate02'},
  ['Очередь на медобслуживание']={t=7000,icon='Temp'},
  ['Очистить и положить еду']={t=5000,icon='INV_Misc_Bowl_01'},
  ['Очищение колодца Буйногривых']={t=10000,icon='Temp'},
  ['Очищение колодца Громового Рога']={t=10000,icon='Temp'},
  ['Очищение колодца Заиндевевшего Копыта']={t=10000,icon='Temp'},
  ['Очищение явления']={t=4000,icon='Temp'},
  ['Очки чести +138']={t=1000,icon='Temp'},
  ['Очки чести +228']={t=1000,icon='Temp'},
  ['Очки чести +2388']={t=1000,icon='INV_BannerPVP_02'},
  ['Очки чести +378']={t=1000,icon='Temp'},
  ['Очки чести +398']={t=1000,icon='Temp'},
  ['Очки чести +50']={t=1000,icon='Temp'},
  ['Очки чести +82']={t=1000,icon='Temp'},
  ['Палевый ящер']={t=3000,icon='Ability_Mount_Raptor'},
  ['Пантера']={t=3000,icon='Ability_Mount_BlackPanther'},
  ['Панцирь Тени']={t=1000,icon='Spell_Shadow_AntiShadow'},
  ['Паразит']={t=2000,icon='Ability_Poisons'},
  ['Паучок Дымной Паутины']={t=1000,icon='Ability_Seal'},
  ['Пегий конь']={t=3000,icon='Ability_Mount_RidingHorse'},
  ['Пелена Тени']={t=1500,icon='Spell_Shadow_GatherShadows'},
  ['Первая помощь']={t=3000,icon='Spell_Holy_GreaterHeal'},
  ['Первородный огонь']={t=500,icon='Spell_Fire_Fireball02'},
  ['Перевод Джаркала']={t=4500,icon='Spell_Holy_Restoration'},
  ['Перемещение временной аномалии']={t=5000,icon='Temp'},
  ['Перо ящера']={t=5000,icon='Temp'},
  ['Перцовая пушка']={t=500,icon='Spell_Fire_Fireball02'},
  ['Пестрая лента']={t=1000,icon='Ability_Seal'},
  ['Песчаный вихрь']={t=2000,icon='Spell_Nature_Cyclone'},
  ['Пламенная вспышка']={t=7000,icon='Spell_Fire_SelfDestruct'},
  ['Пламенная пушка']={t=1500,icon='Spell_Fire_FlameBolt'},
  ['Пламенное дыхание']={t=1700,icon='Spell_Fire_Fire'},
  ['Пламенный кнут']={t=1000,icon='Spell_Fire_Fireball'},
  ['Пламенный шип']={t=3000,icon='Spell_Fire_SelfDestruct'},
  ['Пламя Хаоса']={t=1000,icon='Spell_Fire_WindsofWoe'},
  ['Пламя Шахрама']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Пламя воздаяния']={t=3000,icon='Temp'},
  ['Плевок мясника']={t=2500,icon='Spell_Nature_CorrosiveBreath'},
  ['Плевок разъедающей кислоты']={t=3000,icon='Spell_Nature_Acid_01'},
  ['Пленение Грарка']={t=3000,icon='Temp'},
  ['Пленение щенка ворга']={t=2500,icon='Temp'},
  ['Повышенная быстрота']={t=3000,icon='Spell_Nature_Invisibilty'},
  ['Погибель яда']={t=2000,icon='Temp'},
  ['Поглощающая Тьма']={t=1500,icon='Spell_Shadow_LifeDrain02'},
  ['Погребение останков Самуэля']={t=2000,icon='Temp'},
  ['Погружение - визуальный эффект']={t=1500,icon='Spell_Fire_Volcano'},
  ['Подгородский таракан']={t=1000,icon='Ability_Seal'},
  ['Поджаренная булочка']={t=1000,icon='INV_Misc_Food_11'},
  ['Подключение гномской камеры']={t=3000,icon='Temp'},
  ['Подношение Утера']={t=2000,icon='Temp'},
  ['Подношения Грому']={t=2000,icon='Temp'},
  ['Подпитка от раба']={t=1000,icon='Spell_Shadow_ChillTouch'},
  ['Подрыв']={t=5000,icon='Spell_Fire_SelfDestruct'},
  ['Поиск фрагмента артефакта']={t=5000,icon='Temp'},
  ['Ползучая плесень']={t=3000,icon='Spell_Shadow_CreepingPlague'},
  ['Полная заморозка']={t=2500,icon='Spell_Frost_Glacier'},
  ['Полное исцеление']={t=1000,icon='Temp'},
  ['Положить голову Гор\'теша']={t=5000,icon='Temp'},
  ['Полосатый ледопард']={t=3000,icon='Ability_Mount_WhiteTiger'},
  ['Полосатый саблезуб']={t=3000,icon='Ability_Mount_BlackPanther'},
  ['Поместить арканитовый буй']={t=2000,icon='Temp'},
  ['Поместить магический кристалл']={t=3000,icon='Temp'},
  ['Поместить некованную печать']={t=500,icon='Temp'},
  ['Поместить неопалимый клинок']={t=1000,icon='Temp'},
  ['Поместить призрачный магнит']={t=1500,icon='Temp'},
  ['Поместить распылитель ядовитого тумана']={t=3000,icon='INV_Cask_01'},
  ['Поместить труп жесткозуба']={t=2500,icon='INV_Misc_Bowl_01'},
  ['Поместить труп льва']={t=2500,icon='INV_Misc_Bowl_01'},
  ['Помещение подвески']={t=5000,icon='Temp'},
  ['Попадание снайпера']={t=2000,icon='Ability_Marksmanship'},
  ['Пополнение']={t=2000,icon='Spell_Misc_Drink'},
  ['Порабощение демона']={t=3000,icon='Spell_Shadow_EnslaveDemon'},
  ['Портал Златоземья']={t=5000,icon='Temp'},
  ['Портал Изрубленного Щита']={t=1500,icon='Spell_Arcane_TeleportOrgrimmar'},
  ['Портал Призывания принцессы']={t=10000,icon='Spell_Arcane_PortalIronForge'},
  ['Портал Тени']={t=250,icon='Spell_Shadow_AntiShadow'},
  ['Портал Тьмы']={t=1000,icon='Spell_Shadow_SealOfKings'},
  ['Портал в Громовой Утес']={t=10000,icon='Spell_Arcane_PortalThunderBluff'},
  ['Портал в Дарнас']={t=10000,icon='Spell_Arcane_PortalDarnassus'},
  ['Портал в Каражан']={t=10000,icon='Spell_Arcane_PortalUnderCity'},
  ['Портал в Оргриммар']={t=10000,icon='Spell_Arcane_PortalOrgrimmar'},
  ['Портал в Подгород']={t=10000,icon='Spell_Arcane_PortalUnderCity'},
  ['Портал в Стальгорн']={t=10000,icon='Spell_Arcane_PortalIronForge'},
  ['Портал в Штормград']={t=10000,icon='Spell_Arcane_PortalStormWind'},
  ['Портал демонов']={t=500,icon='Spell_Arcane_TeleportOrgrimmar'},
  ['Порча']={t=2000,icon='Spell_Shadow_AbominationExplosion'},
  ['Порыв ветра']={t=2000,icon='Spell_Nature_EarthBind'},
  ['Посадить волшебные бобы']={t=2000,icon='INV_Misc_Food_Wheat_02'},
  ['Посадить семена']={t=5000,icon='Temp'},
  ['Постоянная иллюзия - Тирион']={t=3000,icon='Ability_Rogue_Disguise'},
  ['Постоянная иллюзия - Тирония']={t=3000,icon='Ability_Rogue_Disguise'},
  ['Похищение духа']={t=2000,icon='Spell_Shadow_Possession'},
  ['Пошутить']={t=2000,icon='Spell_Shadow_LifeDrain'},
  ['Появление Рагнароса']={t=2900,icon='Spell_Fire_LavaSpawn'},
  ['Появление вызова Арроку']={t=2000,icon='Temp'},
  ['Праведное пламя Вкл']={t=4000,icon='Spell_Holy_InnerFire'},
  ['Превращение']={t=1500,icon='Spell_Nature_Polymorph'},
  ['Превращение красного дракона DND']={t=1000,icon='Temp'},
  ['Превращение синего дракона DND']={t=1000,icon='Temp'},
  ['Превращение студента из смотровой - эффект']={t=1000,icon='Temp'},
  ['Превращение: корова']={t=1500,icon='Spell_Nature_Polymorph_Cow'},
  ['Превращение: свинья']={t=1500,icon='Spell_Magic_PolymorphPig'},
  ['Превращение: черепаха']={t=1500,icon='Ability_Hunter_Pet_Turtle'},
  ['Преображение жертвы']={t=2000,icon='Spell_Magic_LesserInvisibilty'},
  ['Преображение зеленого дракона - DND']={t=1000,icon='Temp'},
  ['Преобразование Вароша']={t=1000,icon='Temp'},
  ['Прерывание важного дела']={t=2000,icon='Spell_Shadow_CurseOfAchimonde'},
  ['Прерывание дела']={t=2000,icon='Spell_Shadow_CurseOfAchimonde'},
  ['Приглашение на фестиваль']={t=5000,icon='Spell_Arcane_TeleportMoonglade'},
  ['Призвание Рагнароса']={t=10000,icon='Spell_Fire_LavaSpawn'},
  ['Призванный Урок']={t=1000,icon='Temp'},
  ['Призвать ветерана легиона Чернорука']={t=5000,icon='Spell_Nature_Purge'},
  ['Призвать страхопряда легиона Чернорука']={t=5000,icon='Spell_Nature_Purge'},
  ['Призрачный волк']={t=3000,icon='Spell_Nature_SpiritWolf'},
  ['Призыв']={t=1000,icon='Spell_Arcane_Blink'},
  ['Призыв - воздействие']={t=5000,icon='Spell_Shadow_AnimateDead'},
  ['Призыв Дагуна']={t=5000,icon='Temp'},
  ['Призыв Иллюзорного кошмара']={t=2000,icon='Spell_Fire_SealOfFire'},
  ['Призыв Мизраэли']={t=10000,icon='Spell_Shadow_LifeDrain'},
  ['Призыв Огнезолов']={t=2000,icon='Spell_Fire_Fire'},
  ['Призыв Циклониана']={t=10000,icon='Spell_Nature_EarthBind'},
  ['Призыв Шмыгуноса']={t=2000,icon='Spell_Nature_ProtectionformNature'},
  ['Призыв белоснежной совы']={t=1000,icon='Ability_Seal'},
  ['Призыв беса']={t=10000,icon='Spell_Shadow_SummonImp'},
  ['Призыв болотного духа']={t=1500,icon='Spell_Nature_AbolishMagic'},
  ['Призыв болотного слизнюка']={t=2500,icon='Spell_Shadow_BlackPlague'},
  ['Призыв громового удара']={t=10000,icon='Temp'},
  ['Призыв демона Бездны']={t=10000,icon='Spell_Shadow_SummonVoidWalker'},
  ['Призыв демона сферы']={t=5000,icon='Temp'},
  ['Призыв дистанционно управляемого голема']={t=3000,icon='Ability_Repair'},
  ['Призыв дракончика Ониксии']={t=2000,icon='Temp'},
  ['Призыв древесника']={t=3000,icon='Spell_Nature_ProtectionformNature'},
  ['Призыв духа вепря']={t=1500,icon='Spell_Magic_PolymorphPig'},
  ['Призыв ездового Грифона']={t=3000,icon='Ability_BullRush'},
  ['Призыв желтого мотылька']={t=1000,icon='Ability_Seal'},
  ['Призыв живого жара']={t=2000,icon='Spell_Fire_Fire'},
  ['Призыв жутеволка']={t=1300,icon='Spell_Shadow_ChillTouch'},
  ['Призыв иллюзорного призрака']={t=1000,icon='Spell_Shadow_Teleport'},
  ['Призыв иллюзорного сновидца']={t=1000,icon='Spell_Shadow_Teleport'},
  ['Призыв иллюзорного фантазма']={t=2000,icon='Spell_Fire_SealOfFire'},
  ['Призыв иллюзорных волков']={t=1000,icon='Spell_Shadow_Teleport'},
  ['Призыв инфернала-слуги']={t=2000,icon='Spell_Shadow_SummonInfernal'},
  ['Призыв какаду']={t=1000,icon='Ability_Seal'},
  ['Призыв коня погибели']={t=3000,icon='Ability_Mount_Dreadsteed'},
  ['Призыв лягушки-попрыгушки']={t=1000,icon='Ability_Seal'},
  ['Призыв маленького бронзового дракончика']={t=1000,icon='Ability_Seal'},
  ['Призыв марионеток Хелькулара']={t=3000,icon='Spell_Shadow_Haunting'},
  ['Призыв островной лягушки']={t=1000,icon='Ability_Seal'},
  ['Призыв охотника Скверны']={t=10000,icon='Spell_Shadow_SummonFelHunter'},
  ['Призыв охотника Скверны из племени Сухокожих']={t=3000,icon='Spell_Shadow_SummonFelHunter'},
  ['Призыв призрака Синдиката']={t=1000,icon='Spell_Shadow_Twilight'},
  ['Призыв прислужника Тервоша']={t=4000,icon='Spell_Frost_Wisp'},
  ['Призыв скакуна']={t=3000,icon='Ability_Mount_Charger'},
  ['Призыв скелета из племени Атал\'ай']={t=1000,icon='Spell_Shadow_RaiseDead'},
  ['Призыв степной курицы']={t=1000,icon='Ability_Seal'},
  ['Призыв стража-заклинателя']={t=5000,icon='Spell_Nature_Purge'},
  ['Призыв суккуба']={t=10000,icon='Spell_Shadow_SummonSuccubus'},
  ['Призыв тени Гунтера']={t=2000,icon='Temp'},
  ['Призыв удара Тьмы']={t=10000,icon='Temp'},
  ['Призыв фейлинга']={t=1000,icon='Ability_Seal'},
  ['Призыв филина']={t=1000,icon='Ability_Seal'},
  ['Призыв чудотворца']={t=5000,icon='Spell_Nature_Purge'},
  ['Призыв щитовой стражи']={t=5000,icon='Spell_Nature_Purge'},
  ['Призыв элементаля воды']={t=2000,icon='Spell_Shadow_SealOfKings'},
  ['Призывание Духа древности']={t=4000,icon='Spell_Nature_Purge'},
  ['Призывание гадюки']={t=1500,icon='Spell_Nature_ResistMagic'},
  ['Призывание коня Скверны']={t=3000,icon='Spell_Nature_Swiftness'},
  ['Прикосновение Когтя Ворона']={t=1500,icon='Spell_Shadow_Requiem'},
  ['Приманка Миблона']={t=2000,icon='INV_Misc_Food_50'},
  ['Применение мази']={t=1300,icon='Temp'},
  ['Применение соблазняющей железы']={t=2500,icon='INV_Misc_Bowl_01'},
  ['Природная слабость']={t=5000,icon='INV_Misc_QirajiCrystal_03'},
  ['Природное равновесие']={t=3000,icon='Temp'},
  ['Прислужник Морганта']={t=2500,icon='Spell_Totem_WardOfDraining'},
  ['Прислужники Малатрома']={t=1000,icon='Spell_Shadow_CorpseExplode'},
  ['Приступ кровожадности']={t=2000,icon='Spell_Nature_BloodLust'},
  ['Прицельный выстрел']={t=3000,icon='INV_Spear_07'},
  ['Приятный сюрприз']={t=1000,icon='INV_ValentinesChocolate03'},
  ['Пробуждение Аркедаса - визуальный эффект (DND)']={t=1500,icon='Spell_Nature_Earthquake'},
  ['Пробуждение Керлониана']={t=4500,icon='Temp'},
  ['Пробуждение Меритры']={t=2000,icon='Temp'},
  ['Пробуждение Свежевателя Душ']={t=5000,icon='Temp'},
  ['Пробуждение тюремщика подземелья']={t=5000,icon='Spell_Nature_Earthquake'},
  ['Прогнать питомца']={t=5000,icon='Spell_Nature_SpiritWolf'},
  ['Проклятие Мертвого Леса']={t=2000,icon='Spell_Shadow_GatherShadows'},
  ['Проклятие Огненного клейма']={t=2000,icon='Ability_Creature_Cursed_03'},
  ['Проклятие Сталвана']={t=1000,icon='Spell_Shadow_ShadowPact'},
  ['Проклятие Тимми']={t=1000,icon='Spell_Shadow_ShadowPact'},
  ['Проклятие Тула']={t=2000,icon='Spell_Shadow_ShadowPact'},
  ['Проклятие Шахрама']={t=1000,icon='Spell_Magic_LesserInvisibilty'},
  ['Проклятие банши']={t=2000,icon='Spell_Nature_Drowsy'},
  ['Проклятие восстановления']={t=1000,icon='Spell_Shadow_AntiShadow'},
  ['Проклятие крови']={t=2000,icon='Spell_Shadow_RitualOfSacrifice'},
  ['Проклятие нежити']={t=1000,icon='Spell_Shadow_CurseOfMannoroth'},
  ['Проклятие скверны']={t=4000,icon='Temp'},
  ['Проклятие слабости']={t=1000,icon='Spell_Shadow_CurseOfMannoroth'},
  ['Проклятие темного наставника']={t=2000,icon='Spell_Shadow_AntiShadow'},
  ['Проклятие чумной крысы']={t=1500,icon='Spell_Shadow_UnholyFrenzy'},
  ['Проклятие шипов']={t=2000,icon='Spell_Shadow_AntiShadow'},
  ['Проклятье Хаккара']={t=2500,icon='Spell_Shadow_GatherShadows'},
  ['Проклятье павших Маграм']={t=2000,icon='Spell_Shadow_UnholyFrenzy'},
  ['Проклятье племен']={t=2000,icon='Spell_Shadow_CurseOfMannoroth'},
  ['Пронзающая тень']={t=2000,icon='Spell_Shadow_ChillTouch'},
  ['Проникающий молот из ивы']={t=1000,icon='Spell_Nature_CorrosiveBreath'},
  ['Просветление']={t=2000,icon='Spell_Shadow_Fumble'},
  ['Простая групповая телепортация']={t=2000,icon='Spell_Magic_LesserInvisibilty'},
  ['Простая невидимость']={t=3000,icon='Spell_Magic_LesserInvisibilty'},
  ['Простая телепортация']={t=1000,icon='Spell_Magic_LesserInvisibilty'},
  ['Простая телепортация другого игрока']={t=1000,icon='Spell_Magic_LesserInvisibilty'},
  ['Простое волшебное масло']={t=3000,icon='Temp'},
  ['Простое масло маны']={t=3000,icon='Temp'},
  ['Пространственный портал']={t=2000,icon='Temp'},
  ['Прощение']={t=1000,icon='Temp'},
  ['Птенец летучего хамелеона']={t=1000,icon='Ability_Seal'},
  ['Пулемет']={t=500,icon='Ability_Marksmanship'},
  ['Пустая праздничная кружка']={t=2000,icon='Temp'},
  ['Пушечный огонь']={t=1000,icon='Spell_Fire_FireBolt02'},
  ['Пушечный огонь Южноморья']={t=5000,icon='Spell_Fire_FireBolt02'},
  ['Пыльное облако']={t=1500,icon='Ability_Hibernation'},
  ['Пышка']={t=2000,icon='Spell_Holy_Heal'},
  ['Пьяная команда на пит-стопе']={t=2000,icon='Temp'},
  ['Пятнистая пантера']={t=3000,icon='Ability_Mount_BlackPanther'},
  ['Пятнистый кролик']={t=1000,icon='Ability_Seal'},
  ['Пятнистый полярный ледопард']={t=3000,icon='Ability_Mount_WhiteTiger'},
  ['Радиационный удар']={t=3000,icon='Spell_Shadow_CorpseExplode'},
  ['Разбитая душа']={t=2000,icon='Spell_Fire_Fire'},
  ['Разведчик Синдиката (МУРП) DND']={t=1000,icon='Spell_Arcane_Blink'},
  ['Разговор с головами']={t=5000,icon='Spell_Shadow_LifeDrain'},
  ['Раздвоенная молния']={t=2000,icon='Spell_Nature_ChainLightning'},
  ['Размах Червя']={t=1000,icon='INV_Misc_MonsterScales_05'},
  ['Разрушение']={t=3000,icon='Temp'},
  ['Разрушитель душ']={t=2000,icon='Spell_Shadow_Haunting'},
  ['Разрывной выстрел']={t=1000,icon='Spell_Fire_Fireball02'},
  ['Разъедающая кислота']={t=1500,icon='Spell_Nature_Acid_01'},
  ['Разящий удар']={t=2000,icon='Temp'},
  ['Раскатистый рев']={t=1500,icon='Spell_Fire_Fire'},
  ['Раскопки кобальта']={t=1500,icon='Temp'},
  ['Расплавленный металл']={t=2000,icon='Spell_Fire_Fireball'},
  ['Распыление']={t=3000,icon='Spell_Holy_RemoveCurse'},
  ['Рассветный гамбит']={t=1500,icon='Temp'},
  ['Рассекающий удар']={t=2500,icon='Ability_Warrior_Cleave'},
  ['Рассечение крылом']={t=1000,icon='INV_Misc_MonsterScales_14'},
  ['Рассеяние']={t=1000,icon='Spell_Holy_DispelMagic'},
  ['Рассеять яд']={t=2000,icon='Spell_Holy_Purify'},
  ['Расширение кругозора']={t=30000,icon='Spell_Shadow_LifeDrain'},
  ['Рвотная чума']={t=2000,icon='Spell_Shadow_CallofBone'},
  ['Реалистичная жаба']={t=1000,icon='Ability_Seal'},
  ['Резак']={t=2000,icon='Spell_Fire_Incinerate'},
  ['Ремонт ожерелья Лаваша']={t=4500,icon='Spell_Holy_Restoration'},
  ['Римблат выращивает цветок DND']={t=2000,icon='Temp'},
  ['Ритуал Рока']={t=10000,icon='Spell_Shadow_AntiMagicShell'},
  ['Ритуал призыва']={t=5000,icon='Spell_Shadow_Twilight'},
  ['Род Ноздорму - фракция +1000']={t=1000,icon='Temp'},
  ['Рождение']={t=2000,icon='Temp'},
  ['Ром Ромси "Черный ярлык"']={t=1000,icon='INV_Drink_04'},
  ['Ром Рэмси']={t=1000,icon='INV_Drink_03'},
  ['Рука Ируксоса']={t=5000,icon='Temp'},
  ['Руна Открытия']={t=5000,icon='Temp'},
  ['Рыжая полосатая кошка']={t=1000,icon='Ability_Seal'},
  ['Рыжий волк']={t=3000,icon='Ability_Mount_BlackDireWolf'},
  ['Рыжий саблезуб']={t=3000,icon='Ability_Mount_JungleTiger'},
  ['Рык']={t=1000,icon='Ability_Racial_Cannibalize'},
  ['Рыцарский щит Воздаяния']={t=1000,icon='INV_Shield_19'},
  ['Саженец Таммры']={t=1300,icon='Temp'},
  ['Самовоскрешение']={t=5000,icon='Temp'},
  ['Самоподрыв']={t=7000,icon='Spell_Fire_SelfDestruct'},
  ['Самоуничтожение']={t=7000,icon='Spell_Fire_SelfDestruct'},
  ['Самоцвет Змеи']={t=5000,icon='Temp'},
  ['Самоцвет Хаоса']={t=3000,icon='Temp'},
  ['Сапфирон DND']={t=20000,icon='Temp'},
  ['Сбивание']={t=1500,icon='Spell_Nature_Thorns'},
  ['Сбор трав']={t=5000,icon='Spell_Nature_NatureTouchGrow'},
  ['Сбор яиц силитидов']={t=5000,icon='Temp'},
  ['Сверкающее волшебное масло']={t=3000,icon='Temp'},
  ['Сверкающее масло маны']={t=3000,icon='Temp'},
  ['Сверхзнание']={t=5000,icon='Spell_Holy_Restoration'},
  ['Свет алтаря Аталаи - визуальный эффект (DND)']={t=1000,icon='Temp'},
  ['Свет небес']={t=2500,icon='Spell_Holy_HolyBolt'},
  ['Свеча Элуны']={t=500,icon='Temp'},
  ['Свиток заклятия Проявления']={t=2000,icon='Spell_Magic_LesserInvisibilty'},
  ['Священный огонь']={t=3500,icon='Spell_Holy_SearingLight'},
  ['Сглаз']={t=2000,icon='Spell_Nature_Polymorph'},
  ['Сглаз Когтя Ворона']={t=2000,icon='Spell_Shadow_Charm'},
  ['Сдвиг полярности']={t=3000,icon='Spell_Nature_Lightning'},
  ['Сенегальский попугай']={t=1000,icon='Ability_Seal'},
  ['Серая полосатая кошка']={t=1000,icon='Ability_Seal'},
  ['Сердце Хаккара - Молтор бросает сердце']={t=2000,icon='Temp'},
  ['Серебристая полосатая кошка']={t=1000,icon='Ability_Seal'},
  ['Серебряная отмычка']={t=5000,icon='Temp'},
  ['Серый баран']={t=3000,icon='Ability_Mount_MountainRam'},
  ['Серый волк']={t=3000,icon='Ability_Mount_WhiteDireWolf'},
  ['Серый кодо']={t=3000,icon='Ability_Mount_Kodo_01'},
  ['Сеть с крючьями']={t=500,icon='Ability_Ensnare'},
  ['Сиамская кошка']={t=1000,icon='Ability_Seal'},
  ['Сила Арко\'нарин']={t=4000,icon='Spell_Nature_AstralRecal'},
  ['Сила Снежной Гривы']={t=1000,icon='Spell_Nature_UndyingStrength'},
  ['Сила веков']={t=2000,icon='Spell_Shadow_Requiem'},
  ['Силитидова чума']={t=2000,icon='Spell_Nature_NullifyDisease'},
  ['Сильная боль']={t=1000,icon='Spell_Shadow_ShadowWordPain'},
  ['Сильный исцеляющий идол']={t=2000,icon='Spell_Holy_LayOnHands'},
  ['Символ Жизни']={t=10000,icon='Spell_Holy_Resurrection'},
  ['Симуляция выстрела']={t=2000,icon='Ability_Marksmanship'},
  ['Синий баран']={t=3000,icon='Ability_Mount_MountainRam'},
  ['Синий конь-скелет']={t=3000,icon='Ability_Mount_Undeadhorse'},
  ['Синий механодолгоног']={t=3000,icon='Ability_Mount_MechaStrider'},
  ['Синий полоз']={t=1000,icon='Ability_Seal'},
  ['Скачущая молния']={t=3000,icon='Spell_Nature_Lightning'},
  ['Сковывание нежити']={t=1500,icon='Spell_Nature_Slow'},
  ['Слабая ледяная стрела']={t=2200,icon='Spell_Frost_FrostBolt02'},
  ['Слабое волшебное масло']={t=3000,icon='Temp'},
  ['Слабое масло маны']={t=3000,icon='Temp'},
  ['Слабоумие']={t=1000,icon='Spell_Shadow_MindSteal'},
  ['Слабоумие II']={t=1000,icon='Spell_Shadow_MindSteal'},
  ['Слабоумие III']={t=1000,icon='Spell_Shadow_MindSteal'},
  ['Сливочное блаженство']={t=1000,icon='INV_ValentinesChocolate01'},
  ['Слияние слизей']={t=500,icon='INV_Potion_12'},
  ['Слово оттепели']={t=5000,icon='Temp'},
  ['Смертельная отрава']={t=3000,icon='Spell_Nature_CorrosiveBreath'},
  ['Смертельный яд']={t=3000,icon='Ability_Rogue_DualWeild'},
  ['Смертельный яд II']={t=3000,icon='Ability_Rogue_DualWeild'},
  ['Смертельный яд III']={t=3000,icon='Ability_Rogue_DualWeild'},
  ['Смертельный яд IV']={t=3000,icon='Ability_Rogue_DualWeild'},
  ['Смертельный яд V']={t=3000,icon='Ability_Rogue_DualWeild'},
  ['Смертное ложе']={t=2000,icon='Spell_Shadow_Twilight'},
  ['Смерть Виндзора DND']={t=1500,icon='Temp'},
  ['Смерть Таэлана']={t=2000,icon='Temp'},
  ['Смерть и разложение']={t=2000,icon='Spell_Shadow_DeathAndDecay'},
  ['Снеговик']={t=1500,icon='INV_Ammo_Snowball'},
  ['Снежная буря']={t=2000,icon='Spell_Frost_IceStorm'},
  ['Снежный баран']={t=3000,icon='Ability_Mount_MountainRam'},
  ['Снежный волк']={t=3000,icon='Ability_Mount_WhiteDireWolf'},
  ['Снятие печати']={t=2000,icon='Temp'},
  ['Снятие шкур']={t=2000,icon='INV_Misc_Pelt_Wolf_01'},
  ['Собирание осадков']={t=4000,icon='Temp'},
  ['Соблазн']={t=1500,icon='Spell_Shadow_MindSteal'},
  ['Совмещение факела']={t=5000,icon='Temp'},
  ['Соединение камеры гоблинов']={t=3000,icon='Temp'},
  ['Сожжение маны']={t=3000,icon='Spell_Shadow_ManaBurn'},
  ['Сожжение плоти']={t=2000,icon='Spell_Fire_Fire'},
  ['Создание PX83-Энигматрона']={t=2000,icon='INV_Misc_Bowl_01'},
  ['Создание Тотема очищения']={t=5000,icon='Spell_Shadow_LifeDrain'},
  ['Создание воды провидцев']={t=5000,icon='Spell_Shadow_LifeDrain'},
  ['Создание гадальной чаши']={t=2500,icon='INV_Misc_Bowl_01'},
  ['Создание камня здоровья']={t=3000,icon='INV_Stone_04'},
  ['Создание камня здоровья (большого)']={t=3000,icon='INV_Stone_04'},
  ['Создание камня здоровья (крошечного)']={t=3000,icon='INV_Stone_04'},
  ['Создание камня здоровья (крупного)']={t=3000,icon='INV_Stone_04'},
  ['Создание камня здоровья (малого)']={t=3000,icon='INV_Stone_04'},
  ['Создание крошера']={t=1000,icon='INV_Misc_Gear_01'},
  ['Создание одеяния мага']={t=4000,icon='Temp'},
  ['Создание полной шкатулки-духоловки']={t=2000,icon='Temp'},
  ['Создание провала']={t=3000,icon='Temp'},
  ['Создание пусковой установки батарей фейерверков']={t=2000,icon='INV_Misc_EngGizmos_03'},
  ['Создание пусковой установки фейерверков']={t=2000,icon='INV_Musket_04'},
  ['Создание сапты']={t=3000,icon='INV_Misc_Food_09'},
  ['Создание сверток с реликвиями']={t=1000,icon='Temp'},
  ['Создание свитка']={t=5000,icon='INV_Scroll_05'},
  ['Создание сферы мага']={t=4000,icon='Temp'},
  ['Создание тотемного узла Сухокожих']={t=2000,icon='Spell_Lightning_LightningBolt01'},
  ['Создание шкатулки-духоловки']={t=500,icon='Temp'},
  ['Сокрушение духа']={t=2000,icon='Spell_Holy_HarmUndeadAura'},
  ['Сол Л']={t=3000,icon='Spell_Frost_ManaRecharge'},
  ['Сол М']={t=3000,icon='Spell_Frost_ManaRecharge'},
  ['Сол У']={t=3000,icon='Spell_Frost_ManaRecharge'},
  ['Сол Х']={t=3000,icon='Spell_Frost_ManaRecharge'},
  ['Сон']={t=1500,icon='Spell_Nature_Sleep'},
  ['Сопротивление магии льда']={t=1000,icon='Spell_Frost_WizardMark'},
  ['Сопротивление темной магии']={t=1000,icon='Spell_Frost_WizardMark'},
  ['Сосредоточение']={t=5000,icon='Temp'},
  ['Сосулька']={t=1500,icon='Spell_Frost_FrostBolt02'},
  ['Сотворение алтаря Призыва']={t=10000,icon='Temp'},
  ['Сотворение коня Скверны МАНЕКЕН DND']={t=5000,icon='Temp'},
  ['Сотворение круга Зова']={t=10000,icon='Temp'},
  ['Сотворение предмета - визуальный эффект (DND)']={t=5000,icon='Spell_Shadow_SoulGem'},
  ['Сотворение ущелья Снов']={t=10000,icon='Temp'},
  ['Спокойный механический йети']={t=1000,icon='Ability_Seal'},
  ['Спячка']={t=1500,icon='Spell_Nature_Sleep'},
  ['Сражен']={t=1000,icon='INV_Ammo_Arrow_02'},
  ['Средство Тарнариуна 1']={t=750,icon='Spell_Nature_RemoveDisease'},
  ['Стальной механодолгоног']={t=3000,icon='Ability_Mount_MechaStrider'},
  ['Страж-демон Бездны']={t=3000,icon='Spell_Shadow_SummonVoidWalker'},
  ['Стражи Илкруда']={t=5000,icon='Spell_Shadow_SummonVoidWalker'},
  ['Страх']={t=1500,icon='Spell_Shadow_Possession'},
  ['Страх (NYI)']={t=3000,icon='Spell_Shadow_Possession'},
  ['Стрела Айнаши']={t=500,icon='Temp'},
  ['Стрела Купидона']={t=1000,icon='Temp'},
  ['Стрела Тьмы']={t=3000,icon='Spell_Shadow_ShadowBolt'},
  ['Стрела Тьмы - осечка']={t=2000,icon='Spell_Shadow_ShadowBolt'},
  ['Стремительный белый баран']={t=3000,icon='Ability_Mount_MountainRam'},
  ['Стремительный белый механодолгоног']={t=3000,icon='Ability_Mount_MechaStrider'},
  ['Стремительный белый рысак']={t=3000,icon='Ability_Mount_RidingHorse'},
  ['Стремительный бурый баран']={t=3000,icon='Ability_Mount_MountainRam'},
  ['Стремительный бурый волк']={t=3000,icon='Ability_Mount_BlackDireWolf'},
  ['Стремительный гнедой рысак']={t=3000,icon='Ability_Mount_RidingHorse'},
  ['Стремительный грозовой саблезуб']={t=3000,icon='Ability_Mount_BlackPanther'},
  ['Стремительный желтый механодолгоног']={t=3000,icon='Ability_Mount_MechaStrider'},
  ['Стремительный зеленый механодолгоног']={t=3000,icon='Ability_Mount_MechaStrider'},
  ['Стремительный зулианский тигр']={t=3000,icon='Ability_Mount_JungleTiger'},
  ['Стремительный игреневый конь']={t=3000,icon='Ability_Mount_RidingHorse'},
  ['Стремительный ледопард']={t=3000,icon='Ability_Mount_WhiteTiger'},
  ['Стремительный лесной волк']={t=3000,icon='Ability_Mount_WhiteDireWolf'},
  ['Стремительный оливковый ящер']={t=3000,icon='Ability_Mount_Raptor'},
  ['Стремительный оранжевый ящер']={t=3000,icon='Ability_Mount_Raptor'},
  ['Стремительный рассветный саблезуб']={t=3000,icon='Ability_Mount_JungleTiger'},
  ['Стремительный серый баран']={t=3000,icon='Ability_Mount_MountainRam'},
  ['Стремительный серый волк']={t=3000,icon='Ability_Mount_WhiteDireWolf'},
  ['Стремительный синий ящер']={t=3000,icon='Ability_Mount_Raptor'},
  ['Стремительный туманный саблезуб']={t=3000,icon='Ability_Mount_BlackPanther'},
  ['Стремительный ящер Раззаши']={t=3000,icon='Ability_Mount_Raptor'},
  ['Студеное дыхание']={t=1000,icon='Spell_Frost_Wisp'},
  ['Супер Кристалл']={t=6000,icon='Temp'},
  ['Твердый динамит']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Телепорт']={t=1000,icon='Spell_Magic_LesserInvisibilty'},
  ['Телепорт Алтаря Приливов']={t=2000,icon='Temp'},
  ['Телепорт Ашкромба']={t=2000,icon='Spell_Fire_SelfDestruct'},
  ['Телепорт в Аббатство Североземья']={t=2000,icon='Temp'},
  ['Телепорт в Дарнас - событие']={t=1000,icon='Temp'},
  ['Телепорт в Западный край']={t=2000,icon='Temp'},
  ['Телепорт в Златоземье']={t=2000,icon='Temp'},
  ['Телепорт в Казармы']={t=2000,icon='Temp'},
  ['Телепорт в Луноречье']={t=2000,icon='Temp'},
  ['Телепорт в Монастырь']={t=2000,icon='Temp'},
  ['Телепорт в Старую Наковальню']={t=2000,icon='Temp'},
  ['Телепорт в Сумрачный лес']={t=2000,icon='Temp'},
  ['Телепорт в Темнолесье']={t=2000,icon='Temp'},
  ['Телепорт в Элвиннский лес']={t=2000,icon='Temp'},
  ['Телепорт в башню Азшары']={t=1000,icon='Spell_Nature_AstralRecalGroup'},
  ['Телепорт древня']={t=2000,icon='Temp'},
  ['Телепорт из башни Азшары']={t=1000,icon='Spell_Nature_EarthBind'},
  ['Телепорт на Кладбище']={t=2000,icon='Temp'},
  ['Телепорт на Маяк']={t=2000,icon='Temp'},
  ['Телепортация Айвуса - визальный эффект DND']={t=1000,icon='Temp'},
  ['Телепортация мажордома - визуальный эффект']={t=1000,icon='Spell_Arcane_Blink'},
  ['Телепортация: Громовой Утес']={t=10000,icon='Spell_Arcane_TeleportThunderBluff'},
  ['Телепортация: Дарнас']={t=10000,icon='Spell_Arcane_TeleportDarnassus'},
  ['Телепортация: Лунная поляна']={t=10000,icon='Spell_Arcane_TeleportMoonglade'},
  ['Телепортация: Оргриммар']={t=10000,icon='Spell_Arcane_TeleportOrgrimmar'},
  ['Телепортация: Подгород']={t=10000,icon='Spell_Arcane_TeleportUnderCity'},
  ['Телепортация: Стальгорн']={t=10000,icon='Spell_Arcane_TeleportIronForge'},
  ['Телепортация: Штормград']={t=10000,icon='Spell_Arcane_TeleportStormWind'},
  ['Темная жижа']={t=5000,icon='Spell_Shadow_CreepingPlague'},
  ['Темное Желание']={t=1000,icon='INV_ValentinesChocolate04'},
  ['Темное восстановление']={t=2000,icon='Ability_Hunter_MendPet'},
  ['Темный шепот']={t=3000,icon='Spell_Shadow_Haunting'},
  ['Теневая слабость']={t=5000,icon='INV_Misc_QirajiCrystal_05'},
  ['Теневое пламя']={t=2000,icon='Spell_Fire_Incinerate'},
  ['Тест заточки клинка']={t=3000,icon='Temp'},
  ['Тестовое заклинание редактора']={t=250,icon='Temp'},
  ['Тигр']={t=3000,icon='Ability_Mount_JungleTiger'},
  ['Токсичный плевок']={t=2500,icon='Spell_Nature_CorrosiveBreath'},
  ['Ториевая граната']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Тотем молний']={t=500,icon='Spell_Nature_Lightning'},
  ['Тотем хватки Земли']={t=500,icon='Spell_Nature_NatureTouchDecay'},
  ['Транспортер: Круговзор']={t=10000,icon='Spell_Fire_SelfDestruct'},
  ['Тысяча Клинков']={t=250,icon='INV-Sword_53'},
  ['Тычок Силы']={t=1000,icon='INV_Gauntlets_31'},
  ['Тяжелый динамит']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Убойное пойло Крига']={t=1000,icon='INV_Drink_05'},
  ['Увеличение']={t=2000,icon='Spell_Nature_Strength'},
  ['Увечье']={t=3000,icon='Spell_Shadow_Cripple'},
  ['Увядание души']={t=4000,icon='Ability_Racial_Cannibalize'},
  ['Угасание']={t=2000,icon='Temp'},
  ['Углеглаз']={t=5000,icon='Spell_Nature_EarthBindTotem'},
  ['Угрожающее рычание']={t=1000,icon='Ability_Racial_Cannibalize'},
  ['Угрожающий взгляд']={t=2000,icon='Spell_Shadow_Charm'},
  ['Удаление знака отличия']={t=1000,icon='Temp'},
  ['Удали меня']={t=4000,icon='INV_Scroll_02'},
  ['Удар горгульи']={t=1500,icon='Spell_Shadow_ShadowBolt'},
  ['Удар пламенем']={t=2200,icon='Spell_Fire_Fireball'},
  ['Ударная волна']={t=2000,icon='Ability_Whirlwind'},
  ['Узы Чертополохха']={t=2000,icon='Spell_Shadow_Haunting'},
  ['Укрепление отношений']={t=1000,icon='Temp'},
  ['Улучшение дробящего оружия']={t=3000,icon='Temp'},
  ['Улучшение ударного оружия II']={t=3000,icon='Temp'},
  ['Улучшение ударного оружия III']={t=3000,icon='Temp'},
  ['Улучшение ударного оружия IV']={t=3000,icon='Temp'},
  ['Улучшение ударного оружия V']={t=3000,icon='Temp'},
  ['Уменьшение']={t=3000,icon='Spell_Shadow_AntiShadow'},
  ['Умиротворение животного']={t=1500,icon='Ability_Hunter_BeastSoothe'},
  ['Умный напиток Мебока']={t=3000,icon='Temp'},
  ['Уничтожение призрачного магнита']={t=10000,icon='Temp'},
  ['Уничтожение шатра']={t=2500,icon='Temp'},
  ['Уничтожение яйца']={t=3000,icon='INV_Misc_MonsterClaw_02'},
  ['Управление шмыгуносом']={t=1500,icon='Spell_Shadow_LifeDrain'},
  ['Урожай жизни']={t=1000,icon='Spell_Shadow_Requiem'},
  ['Усиление питомца']={t=500,icon='Spell_Shadow_DeathPact'},
  ['Усиленное пламя']={t=1000,icon='Spell_Fire_Fireball'},
  ['Усиленный урон']={t=2000,icon='Spell_Nature_AbolishMagic'},
  ['Установка бомбомета Дымка']={t=3000,icon='Temp'},
  ['Установка знамени']={t=2300,icon='Temp'},
  ['Установка ловушки на медведя']={t=2000,icon='Temp'},
  ['Установка маяка Гуса']={t=5000,icon='Temp'},
  ['Установка маяка Джезтора']={t=5000,icon='Temp'},
  ['Установка маяка Змейера']={t=5000,icon='Temp'},
  ['Установка маяка Ичмена']={t=5000,icon='Temp'},
  ['Установка маяка Малверика']={t=5000,icon='Temp'},
  ['Установка маяка Рисона']={t=5000,icon='Temp'},
  ['Установка маяка Слидора']={t=5000,icon='Temp'},
  ['Установка сигнального факела']={t=2300,icon='Temp'},
  ['Устрашающий рык']={t=1000,icon='Ability_Racial_Cannibalize'},
  ['Утраченный навык']={t=2500,icon='Spell_Shadow_AntiShadow'},
  ['Факел вызова демонов']={t=3000,icon='Temp'},
  ['Фейерверк']={t=500,icon='Temp'},
  ['Фиолетовые руки']={t=4000,icon='Spell_Shadow_SiphonMana'},
  ['Фиолетовый ящер']={t=3000,icon='Ability_Mount_Raptor'},
  ['Флаг Кадрака']={t=2000,icon='INV_Banner_03'},
  ['Флейта крысолова']={t=1000,icon='Temp'},
  ['Флюоресцирующий зеленый механодолгоног']={t=3000,icon='Ability_Mount_MechaStrider'},
  ['Фугасная бомба']={t=1000,icon='Spell_Fire_SelfDestruct'},
  ['Хваткие лозы']={t=1000,icon='Spell_Nature_Earthquake'},
  ['Холод']={t=4000,icon='Spell_Frost_Glacier'},
  ['Хрустальная вспышка']={t=2000,icon='Spell_Shadow_Teleport'},
  ['Хрустальный взгляд']={t=2000,icon='Ability_GolemThunderClap'},
  ['Хрустальный сон']={t=2000,icon='Spell_Nature_Sleep'},
  ['Целебный круг']={t=3000,icon='Spell_Holy_BlessingOfProtection'},
  ['Целительное прикосновение']={t=3500,icon='Spell_Nature_HealingTouch'},
  ['Цепная молния']={t=2500,icon='Spell_Nature_ChainLightning'},
  ['Цепное исцеление']={t=2500,icon='Spell_Nature_HealingWaveGreater'},
  ['Цепной ожог']={t=3000,icon='Spell_Shadow_ManaBurn'},
  ['Цепной удар']={t=2500,icon='Spell_Nature_ChainLightning'},
  ['Цыпленок Западного края']={t=1000,icon='Ability_Seal'},
  ['Чародейская бомба']={t=1500,icon='Spell_Holy_Silence'},
  ['Чародейская слабость']={t=5000,icon='INV_Misc_QirajiCrystal_01'},
  ['Чародейская стрела']={t=1000,icon='Spell_Arcane_StarFire'},
  ['Чародейский взрыв']={t=1500,icon='Spell_Nature_WispSplode'},
  ['Чародейский дух II']={t=1000,icon='Spell_Holy_MagicalSentry'},
  ['Чародейский дух III']={t=1000,icon='Spell_Holy_MagicalSentry'},
  ['Чародейский дух IV']={t=1000,icon='Spell_Holy_MagicalSentry'},
  ['Чародейский дух V']={t=1000,icon='Spell_Holy_MagicalSentry'},
  ['Чарующая колыбельная']={t=1000,icon='Spell_Shadow_SoothingKiss'},
  ['Чары Мор\'рогала']={t=1300,icon='Temp'},
  ['Чары для нагрудника - дух I']={t=5000,icon='Spell_Holy_GreaterHeal'},
  ['Чары для оружия - истребитель животных']={t=5000,icon='Spell_Holy_GreaterHeal'},
  ['Чары для палаща - защита l']={t=5000,icon='Spell_Holy_GreaterHeal'},
  ['Червоточина']={t=1000,icon='Ability_Vanish'},
  ['Черная королевская змейка']={t=1000,icon='Ability_Seal'},
  ['Черная слизь']={t=3000,icon='Spell_Shadow_CallofBone'},
  ['Черная стрела']={t=2000,icon='Ability_TheBlackArrow'},
  ['Чернильные брызги']={t=1000,icon='Spell_Nature_Sleep'},
  ['Черный баран']={t=3000,icon='Ability_Mount_MountainRam'},
  ['Черный боевой баран']={t=3000,icon='Ability_Mount_MountainRam'},
  ['Черный боевой волк']={t=3000,icon='Ability_Mount_BlackDireWolf'},
  ['Черный боевой кодо']={t=3000,icon='Ability_Mount_Kodo_01'},
  ['Черный боевой механодолгоног']={t=3000,icon='Ability_Mount_MechaStrider'},
  ['Черный боевой тигр']={t=3000,icon='Ability_Mount_BlackPanther'},
  ['Черный боевой ящер']={t=3000,icon='Ability_Mount_Raptor'},
  ['Черный волк']={t=3000,icon='Ability_Mount_BlackDireWolf'},
  ['Черный киражский боевой танк']={t=3000,icon='INV_Misc_QirajiCrystal_05'},
  ['Черный ночной саблезуб']={t=3000,icon='Ability_Mount_BlackPanther'},
  ['Черный ром Ромси']={t=1000,icon='INV_Drink_04'},
  ['Читательные пластины Виндзора (DND)']={t=10000,icon='Temp'},
  ['Чтение слов Келебраса']={t=3000,icon='Temp'},
  ['Чумное облако']={t=2000,icon='Spell_Shadow_CallofBone'},
  ['Шаровая молния']={t=1000,icon='Spell_Lightning_LightningBolt01'},
  ['Широкий размах']={t=4000,icon='Ability_Whirlwind'},
  ['Шок']={t=1000,icon='Temp'},
  ['Щелкоклюв-альбинос']={t=1000,icon='Ability_Seal'},
  ['Щенок ворга']={t=1000,icon='Ability_Seal'},
  ['Щит отражения']={t=1000,icon='Spell_Shadow_Teleport'},
  ['Экзорцизм Атиеша']={t=20000,icon='Temp'},
  ['Электрическая сеть']={t=500,icon='Ability_Ensnare'},
  ['Элементали Сарилуса']={t=3000,icon='Spell_Shadow_RaiseDead'},
  ['Элементаль земли']={t=3000,icon='Ability_Temp'},
  ['Элементаль огня']={t=3000,icon='Ability_Temp'},
  ['Эльфийский огонек']={t=1000,icon='Ability_Seal'},
  ['Энергетический инкапсулятор кодо']={t=5000,icon='Trade_Fishing'},
  ['Эффект Ритуала Рока']={t=10000,icon='Spell_Arcane_PortalDarnassus'},
  ['Эффект Сергры Черный Шип']={t=3000,icon='Temp'},
  ['Эффект пыли северного оленя']={t=8000,icon='Temp'},
  ['Эффект ритуала призывания']={t=5000,icon='Temp'},
  ['Явление духа']={t=5000,icon='Spell_Totem_WardOfDraining'},
  ['Явление смерти']={t=1000,icon='Spell_Shadow_ShadeTrueSight'},
  ['Яд паучьего монстра']={t=2000,icon='Spell_Nature_NullifyPoison'},
  ['Ядовитая слюна']={t=500,icon='Spell_Nature_CorrosiveBreath'},
  ['Ядовитое облако']={t=1000,icon='Spell_Nature_Regenerate'},
  ['Ядовитый выстрел']={t=2000,icon='Ability_Poisons'},
  ['Ядовитый гарпун']={t=2000,icon='Ability_Poisons'},
  ['Ядовитый плевок']={t=2000,icon='Spell_Nature_CorrosiveBreath'},
  ['Ядовитый удар']={t=2500,icon='Spell_Nature_CorrosiveBreath'},
  ['Ядовитый хвостокол']={t=2000,icon='INV_Misc_MonsterTail_03'},
  ['Яйцо из Питомника']={t=500,icon='Temp'},
  ['Ями Снежное Копыто - оборотничество (DND)']={t=1000,icon='Temp'},
  ['Яркая блесна']={t=5000,icon='INV_Misc_Orb_03'},
  ['Яркий костер']={t=10000,icon='Spell_Fire_Fire'},
  ['Яркий свет']={t=500,icon='Temp'},
  ['Яркое пламя']={t=3000,icon='Spell_Fire_SelfDestruct'},
  ['Яростный вой']={t=5000,icon='Ability_BullRush'},
  ['Ярость Тула']={t=1500,icon='Spell_Shadow_UnholyFrenzy'},
  ['Ястребиная сова']={t=1000,icon='Ability_Seal'},
  ['Ящеричья молния']={t=2000,icon='Spell_Nature_Lightning'},
}

UF.castInterrupts = {
  ["Удар щитом"] = true,
  ["Зуботычина"] = true,
  ["Пинок"] = true,
  ["Земной шок"] = true,
  ["Громовая поступь"] = true,
  ["Оглушающий удар"] = true,
  ["Атака-оглушение"] = true,
  ["Перехват оглушение."] = true,
  ["Молот правосудия"] = true,
  ["Подлый трюк"] = true,
  ["Парализующий удар"] = true,
  ["Удар по почкам"] = true,
  ["Безмолвие"] = true,
  ["Антимагия"] = true,
  ["Антимагия - немота"] = true,
  ["Оглушить"] = true,
  ["Страх"] = true,
  ["Вой ужаса"] = true,
  ["Ментальный крик"] = true,
  ["Устрашающий крик"] = true,
  ["Звездный огонь - оглушение"] = true,
  ["Реванш - оглушение"] = true,
  ["Улучшенный контузящий выстрел"] = true,
  ["Сотрясение"] = true,
  ["Огнесдвиг"] = true,
  ["Затмение"] = true,
  ["Оглушение"] = true,
  ["Эффект оглушения дробящего оружия"] = true,
  ["Землетрясущий"] = true,
  ["Покаяние"] = true,
  ["Дезориентирующий выстрел"] = true,
  ["Ослепление"] = true,
  ["Спячка"] = true,
  ["Укус виверны"] = true,
  ["Грубая медная бомба"] = true,
  ["Большая медная бомба"] = true,
  ["Небольшая бронзовая бомба"] = true,
  ["Большая бронзовая бомба"] = true,
  ["Большая железная бомба"] = true,
  ["Мифриловая осколочная бомба"] = true,
  ["Фугасная бомба"] = true,
  ["Бомба из черного железа"] = true,
  ["Железная граната"] = true,
  ["Осколочная граната M73"] = true,
  ["Ториевая граната"] = true,
  ["Гоблинская мортира"] = true,
}
